### ISSUE TITLE
[TASK] decision to either move to ArgoCD or to stick with ShipIt as our CD tool

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#10]
We need to make a decision on whether to use ArgoCD or Shipit as our CD tool. Something to keep in mind: Before going to prod, it is fairly simple to swap to one or the other if we want. Some further reading to understand what the features of ArgoCD are should be done and a set of risk/benefits defined for both options.

- [x] Further reading of ArgoCD docs & features
- [x] Risks & benefits of each option
- [x] Decision on which to use

**Comment by hannavovk** [comment]
Awesome! Thanks @dleard!
