### ISSUE TITLE
Frontend image runs in openshift

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#100]
Split from #35
We need to be able to deploy the frontend image to openshift. This means adding helm templates to our bcgov-c argoCD manifest repository.

- [x] Add a template to deploy the frontend from our image
- [x] The frontend image runs on openshift
- [x] The frontend can communicate with the backend (network policies)
- [x] Resource tuning if necessary

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Moose-Sprint-Board-60d216175a2689000ec774d0/issues/bcgov/cas-registration/100?planning-poker) with Zenhub @dleard @andrea-williams @Sepehr-Sobhani @BCerki @JoshLarouche

**Comment by Dianadec** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Moose-Sprint-Board-60d216175a2689000ec774d0/issues/bcgov/cas-registration/100?planning-poker) with Zenhub @joshgamache
