### ISSUE TITLE
Breadcrumbs: Replace UUID crumb with descriptive text

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#1000]
###Description of the Tech Debt###
With the change of operator and operations ID to a UUID the breadcrumb links look overwhelmingly complex.

Suggest changing the `ID` segment of the breadcrumb to a descriptive text obtained form the selected record's data

**Dev Tasks:**
- [x] Add operator "title" as querystring information to operator links
- [x] Add operation "title" as querystring information to operation links
- [x] Modify `translateNumericPart` in Bread component to display "title" querystring information

**AC:**
- [ ] the `Select Operator` flow displays selected operator "title" information in the breadcrumb
- [ ] the `My Operator` flow displays operator "title" information in the breadcrumb
- [ ] the `View Operator` flow displays operator "title" information in the breadcrumb
- [ ] the `Create Operation` flow displays available operation "title" information in the breadcrumb
- [ ] the `View Operation` flow displays operation "title" information in the breadcrumb

**Comment by hannavovk** [comment]
@shon-button, I'm not seeing this Dev for some reason. Unless I'm misunderstanding this ticket maybe?



![Image](https://github.com/bcgov/cas-registration/assets/87211104/7e0fe72b-7184-4af6-8bdf-82191920b16b)

**Comment by hannavovk** [comment]
Awesome! Thanks @shon-button
