### ISSUE TITLE
Automated Email for Scenario 1.i "External user logs in for the first time - Operator data exists, but there’s NO admin"

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-registration#1012]
When external user logs in for the first time, 
and If Operator data exists, 
but there’s NO admin, 
the user sees the screen below after submitting the admin access request
![Image](https://github.com/bcgov/cas-registration/assets/58751681/6a08aeb1-4897-4f23-9d5b-869b36489866)

- [x] when BCIERS receives an admin access request for an existing Operator, an email is automatically sent to the external user confirming that the system has received their request for access.
- [x] `from` field of the email uses "no-reply.cas@gov.bc.ca", body of the email will indicate that any replies should be sent to GHG Regulator email address
- [x] once request to send email has been received by CHES (using our `EmailService`), response will include properties `msgId` and `txId`, which need to be saved in our database to be able to query their status later

- [x]  Submission confirmation
- [x]  Approved
- [x]  Declined

emails are required. Please see the [email templates copy](https://bcgov.sharepoint.com/teams/00608-CPRInternal/_layouts/15/Doc.aspx?sourcedoc={0d7ce55e-da9d-42d2-94b6-05171abd4452}&action=edit&wd=target%28Registration.one%7Ca745a153-ea3f-4b6e-8f16-9163bfe64932%2FScenario%201%28i%5C%29%20Existing%20operator%5C%2FNo%20admin%7C7130f089-cb25-4849-99bc-02a892c884d5%2F%29&wdorigin=703) here.

Blocked by #141, #266

**Comment by nanyangpro** [comment]
Hi @hannavovk - Details are added to this ticket. Feel free to review/refine!

Once Jairo finished breaking down the email templates copy into separated pages, I'll add in the url, and move the ticket to the "Next up" column.

**Comment by andrea-williams** [comment]
@hannavovk do we want to be sending these emails from GHG Regulator or is there some no-reply address we want to use instead?

**Comment by hannavovk** [comment]
@andrea-williams Can we do the same thing as we do in CIIP? the BA would prefer "having a no-reply address that is more descriptive and use GHGRegulator as the reply to. CIIP system generated email come from [no-reply.cas@gov.bc.ca](mailto:no-reply.cas@gov.bc.ca)"
