### ISSUE TITLE
Automated Email for Scenario 2.i "BORO ID application - Non opted-in operation"

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-registration#1015]
User sees the screen below after submitting a BORO ID application for a non opted-in operation
![Image](https://github.com/bcgov/cas-registration/assets/58751681/ed271bed-a60a-45ec-b263-bd36ab97328a)

- [ ] Submission confirmation
- [ ] Approved
- [ ] Declined
- [ ] Changes Requested

emails are required. Please see the [email templates copy](https://bcgov.sharepoint.com/teams/00608-CPRInternal/_layouts/15/Doc.aspx?sourcedoc={0d7ce55e-da9d-42d2-94b6-05171abd4452}&action=edit&wd=target%28Registration.one%7Ca745a153-ea3f-4b6e-8f16-9163bfe64932%2FScenario%202%28i%5C%29%20Non-opted-in%20%7Cb664711c-6fc5-435c-81a9-e4c81b81a7b6%2F%29&wdorigin=703) here.

Blocked by #141, #266

**Comment by nanyangpro** [comment]
Hi @hannavovk - Details are added to this ticket. Feel free to review/refine!

Once Jairo finished breaking down the email templates copy into separated pages, I'll add in the url, and move the ticket to the "Next up" column.

**Comment by Sepehr-Sobhani** [comment]
Both the Point of Contact of the BORO ID application and the user who submitted the application should receive these emails, based on the conversation with @nanyangpro .
