### ISSUE TITLE
"OBPS" needs to be added in Home page [10]

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#1029]
Describe the Bug:
![image](https://github.com/bcgov/cas-registration/assets/120038448/b4ff049c-379f-4bde-8465-df7a3100f8df)

Probability (how likely the bug is to happen, scored from 1-5):5
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):5
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by hannavovk** [comment]
Hi @shon-button , for some reason I'm not seeing the text update (neither this one, nor @marcellmueller 's one) in Dev.
