### ISSUE TITLE
Unique identifier seen by internal users in the "Request ID" field in Operator table

### ISSUE THREAD

**Issue by hannavovk** [bcgov/cas-registration#1037]
As an internal CAS user, I want to see a meaningful user friendly unique identifier of the user access requests in the Operator access table instead of the current "Request ID". See screenshot below.

Could this be a user-friendly 'User ID' of some sort? This could also connect to a 'user ID' in the User Management table of external users.

Initial request from BA: "As an internal user, in the Operators dashboard, the request ID appears as a long key (see screenshot). Business area is requesting sequential numbers starting at 1."

![Image](https://github.com/bcgov/cas-registration/assets/87211104/2ca4f4a0-e87f-475c-b255-e99a2307cd1d)

Acceptance Criteria:
- [ ] keep UUID as the Primary Key on the `UserOperator` table, add a secondary column with auto-integer type (calling it "Friendly ID" for the sake of this ticket)
- [ ] populate the `RequestID` values in the UI table with the "Friendly ID" values instead of the UUID
- [ ] if necessary, write a script that back-populates existing prod data with values for "Friendly ID"

**Comment by andrea-williams** [comment]
We want to keep the record identifier in the database as is (UUID), but we can choose to add another column with a more user-friendly unique identifier (?)

**Comment by nanyangpro** [comment]
Re: Refinement - @andrea-williams  will refine the ticket description to include more technical details. Thanks!
