### ISSUE TITLE
Incorporate Opt-in and New Entrant screens/workflows into the design

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-registration#104]
#### Describe the task
The goal of this ticket is to design the proposed screens/workflows for New Entrants and Opt-ins in Figma, so that **we have visuals to refer to** when we later communicate with the business area and iterate on their input.

Context below:

> **Hanna:** Hi Scrum Team, it seems like there's been a decision in the business area that industrial operations will be allowed to opt in starting in the first year, i.e. at the same time as the other OBPS registrants. We will need to account for this in the Registration App. The implications I can think of off the top of my head are:
-we'll probably need some checkbox to indicate an opt-in (not sure at what stage, i.e. user access approval, operator, operation?)
-we may need to collect additional data from an opt-in, e.g. the BA seems to indicate that they will need to demonstrate that they are ready to participate - we should find out how that demonstration should happen and whether we need to support that in the app. E.g. an additional form they need to fill out, or attach a document, or sign something, etc. 
These are initial thoughts ... we should add this to things to discuss with business area.

> **Patricia:** I was able to confirm that Adria made this decision official, so yes, Opt-ins (smaller industry under 10KT) can apply to participate in OBPS. The process will include first applying to the Director (Adria), who will confirm whether or not they can join. Once approved by the Director, they should be allowed to register in (mostly?) the same manner as Regulated Operations and will also received a carbon tax exemption the same way. Apparently Opt-ins will have until Feb 2024 to apply. More info to come on this as we learn more!!

> **Dylan:** Something to consider is an allow-list for operators. Not totally sure if it would work for our use case, but if some operators need to be approved by adria, we'll probably have to record that approval somehow (either online or offline).

> **Hanna:** Based on what John said in our SME check-in today, it seems like they are strongly leaning to just have the registration process also double as the "applying to / approval" for opt-ins. (I think this would totally make sense). I.e. the business area is saying that there doesn't need to be a separate process for this outside the registration app.
In this case, if they are an opt-in, they would need to self-identify (this would also apply to new entrants, so we should add something for them as well) and would just need to sign a "statutory declaration" (I believe that's what John called it) or maybe attach one, and potentially provide some other additional info.

#### Acceptance Criteria

- [x] Review relevant slide in the [Sep 21 Registration Engagement deck](https://bcgov.sharepoint.com/:p:/r/teams/06817/_layouts/15/Doc.aspx?sourcedoc=%7B5E09142A-804F-4603-A130-7F6CD00F9552%7D&file=Sept%2021%20-%20Reg%20engagement%20deck.pptx&wdLOR=c91DBA20A-8069-B74B-AF54-24337EBD6CD2&action=edit&mobileredirect=true)
- [x] Create wireframes for the features/workflows Opt-ins in Figma
- [x] Get input from the business area
- [x] Refine design based on the input gathered

**Comment by nanyangpro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-registration/104?planning-poker) with Zenhub @jaimiebutton @nanyangpro @NicoleGovvy

**Comment by nanyangpro** [comment]
Hi @hannavovk - This ticket is ready for you to review and can be closed with the design updates below in Figma:
- [(New) Workflow | Add Operator](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?page-id=4%3A2&type=design&node-id=514-83&viewport=365%2C284%2C0.29&t=4frrrAOPoEC9MQ8k-1&scaling=scale-down&starting-point-node-id=514%3A83&show-proto-sidebar=1&mode=design) - for when operator profile doesn't exist
- [(New) Screen | New Entrant and/or Opt-in](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?page-id=4%3A2&type=design&node-id=19-2197&viewport=365%2C284%2C0.29&t=4frrrAOPoEC9MQ8k-1&scaling=scale-down&starting-point-node-id=19%3A2197&show-proto-sidebar=1&mode=design) - for when registering an operation
- [(New) Screen | Carbon Tax Exemption](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?page-id=4%3A2&type=design&node-id=19-2197&viewport=365%2C284%2C0.29&t=4frrrAOPoEC9MQ8k-1&scaling=scale-down&starting-point-node-id=19%3A2197&show-proto-sidebar=1&mode=design) - for when an operation is registered

As described in the ticket, further refinements/iterations should be made based on future input we get/collect. The design updates above serve as a visual reference to support communications between us and the business area. (cc: @suhafa :)

**Comment by hannavovk** [comment]
Thanks @nanyangpro !
