### ISSUE TITLE
Remove  'User ID' column from external user management table

### ISSUE THREAD

**Issue by hannavovk** [bcgov/cas-registration#1060]
#### Description:

As an external Admin user, I want to see a meaningful user friendly unique user identifier in the "User ID" column  instead of the uuid.

![Image](https://github.com/bcgov/cas-registration/assets/87211104/b39eab22-2848-4366-8ba7-25ce735ebf5e)

#### Acceptance Criteria:

Given I am an authenticated external (operator) admin user
When I view the User Management page
Then I don't see the User IDs (UUIDs) in the table because they're useless to me

### Additional Context
- just delete the column from the table (on the frontend only), no further action necessary

#### Dependencies

- Blocked by
- Blocking

**Comment by nanyangpro** [comment]
Re: Refinement
@dleard suggested removing the column from external view since it brings no value to industry users.
@hannavovk suggested allowing searching by name to help with locating the proper record.

**Comment by nanyangpro** [comment]
@andrea-williams will refine this.

**Comment by hannavovk** [comment]
Awesome, thanks @marcellmueller
