### ISSUE TITLE
Set up terraform to provision GCS buckets without using terraform cloud

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#11]
Terraform Cloud is a shared resource and has been a bottleneck for us at times. We should create our own terraform scripts to provision our storage buckets and store our state in GCS. 
How the terraform job we have been running works: https://github.com/bcgov/cas-shelf
A repo with examples on manually provisioning resources with terraform: 
- https://github.com/button-inc/emissions-elt-demo/tree/develop/terraform
Terraform Docs: https://developer.hashicorp.com/terraform/docs

This also relates to CIF 1333

- [x] Create terraform scripts to provision our GCS resources
- [x] Create an action or helm chart with a job that we can re-use across our projects that uses these terraform scripts
- [x] Documentation written about how to use the action/job
- [ ] Terraform scripts run as a job (with pre-upgrade, pre-install hooks) in openshift in the cas-reg-backend manifest
- [x] Credentials and bucket name are saved to a secret in the openshift namespace

(Note) Some things that have been created manually & should be done by terraform:
- registration & data warehouse GCS buckets/service accounts
- openshift secrets for the bucket/service accounts

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-registration/11?planning-poker) with Zenhub @andrea-williams @BCerki @dleard @JoshLarouche @Sepehr-Sobhani

**Comment by hannavovk** [comment]
Hi @dleard, can you help me understand the priority of this one? Is it about the same priority level as #35 and #21 or doesn't need to be done by end of next sprint? I.e. is it needed for beta-version release?

**Comment by dleard** [comment]
This streamlines our process for provisioning GCS buckets and service accounts but it is not necessary for beta release
