### ISSUE TITLE
Update User Story Map Miro Board and Zenhub tickets accordingly

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-registration#110]
#### Describe the task

We created zenhub tickets based on the miro board user story map, cross-referencing it with pre-created zenhub tix from the hackathon as well as using info from the service blueprints and dev process maps.

Now we need to ensure that the miro board is up to date.

#### Acceptance Criteria

- [x] Touch base with Andrea for release plan context
- [x] Touch base with Nicole for service blueprint context
- [x] Touch base with Hannah for context on how she would prefer to see the user story map
- [x] Consolidate [Andrea's Release plan](https://miro.com/app/board/o9J_klH4Omo=/?moveToWidget=3458764564111646816&cot=14) +  [Registration User Story mapping](https://miro.com/app/board/uXjVMvY07ts=/?moveToWidget=3458764562861568834&cot=14) + [Service Blueprint](https://miro.com/app/board/uXjVM0yeqXQ=/?moveToWidget=3458764561146162318&cot=14) into user flows
- [ ] Touch base with Diana for user stories and epics context
- [ ] Cross-reference Miro board black sticky notes with Zenhub user stories and epics and ensure they say the same thing and that nothing is missing 

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by Dianadec** [comment]
@NicoleGovvy and @suhafa  - is this something you would be able to help with? Hanna and I started to look at things, but we can connect more about this at the 1pm call today. cc @hannavovk

**Comment by suhafa** [comment]
Certainly can! Looking forward to the call to get any additional insight before helping out

**Comment by Dianadec** [comment]
@suhafa  should we close this ticket since #209 has been created as next steps?
