### ISSUE TITLE
Duplicate/repetitive e2e tests

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#1135]
#### Describe the task

In `client/e2e/pages/authenticated/routes/page.spec.ts` we check that each user role can access all the routes they should be able to access. This overlaps with the workflow tests as they inherently test route access (e.g., you have to be able to access the operations page if you're going to edit an operation). This card is about evaluating test coverage and removing tests that are duplicates.

Note:  `client/e2e/pages/authenticated/routes/page.spec.ts`  also checks that users CAN'T access certain pages. These tests should stay in because not-allowed routes aren't tested anywhere else.

Note note: if the duplicate testing isn't actually causing problems (e.g., e2e tests run fast enough, no resource wasting) then this card may not need to be done.

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by shon-button** [comment]
I consider having a dedicated E2E test for authorization of routes by role neccessary, even if other tests may indirectly cover route access, for the following reasons:

- it makes it clear that  we are  specifically testing role-based access control
-  if we ever need to review or audit access control, it's helpful to have clear, distinct tests verifying that roles are enforced correctly on all protected routes.

Also,  we have tried to avoid redundancy by extracting the common routing to the shared POm helpers

**Comment by patriciarussellCAS** [comment]
@shon-button - should I icebox this, or do you think it's ok to close?

**Comment by shon-button** [comment]
> [@shon-button](https://github.com/shon-button) - should I icebox this, or do you think it's ok to close?

I vote close
