### ISSUE TITLE
Use ruff linter

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-registration#114]
###Description of the Tech Debt###
We have added `pylint` as the Python linter, but it may be more efficient to use `ruff` instead, as it is faster and can accelerate our CI process.

Link to `ruff` pre-commit hook: https://beta.ruff.rs/docs/usage/

**Comment by andrea-williams** [comment]
@Sepehr-Sobhani do we still need this ticket?

**Comment by Sepehr-Sobhani** [comment]
@andrea-williams Yes, ruff is much faster and can speed up our local development and CI.
![Screenshot 2024-03-26 at 8 41 46 AM](https://github.com/bcgov/cas-registration/assets/52381975/94e25997-ca25-4868-82c8-bdef24b756b7)
