### ISSUE TITLE
Add carbon tax exemption page link

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-registration#1153]
We removed the carbon tax exemption page link across the app before the prod release, since Ministry of Finance hadn't published the page then. Now that it's up, let's add the **link** (https://www2.gov.bc.ca/gov/content/taxes/sales-taxes/motor-fuel-carbon-tax/business/exemptions/obps-carbon-tax-exemption) and **copy** back to
- The [landing page ](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2688-6375&mode=design&t=sAEjSDwKnNgBZ7bs-4)
![Image](https://github.com/bcgov/cas-registration/assets/58751681/92563929-e952-4547-85f7-c8f39de0a40b)

- The [BORO ID page](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=340-383&mode=design&t=sAEjSDwKnNgBZ7bs-4)
![Image](https://github.com/bcgov/cas-registration/assets/58751681/5ded53f5-c8db-4d7c-8d8f-8b23d99665c5)

**Comment by nanyangpro** [comment]
Hi @hannavovk - This ticket is created as discussed. Feel free to review or refine. Thanks!

**Comment by hannavovk** [comment]
Thanks @marcellmueller
