### ISSUE TITLE
Create more tickets for Jest testing

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#1175]
###Description of the Tech Debt###

- [ ] write tickets breaking down Jest testing epic (#1174 )

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |       |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |       |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |       |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |       |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |       |
| TOTAL SCORE:                                                                                                                  |       |       |

**Comment by BCerki** [comment]
I've created the following tickets:
- test the `page.tsx` components: https://github.com/bcgov/cas-registration/issues/1217 (light, many of the page components don't do anything except render a different component and that's what does the work)
- test error/layout/not found components: https://github.com/bcgov/cas-registration/issues/1218
- simple component tests: https://github.com/bcgov/cas-registration/issues/1219, https://github.com/bcgov/cas-registration/issues/1220, https://github.com/bcgov/cas-registration/issues/1221
- form widgets: 
- form components: https://github.com/bcgov/cas-registration/issues/1223
- select operator forms: https://github.com/bcgov/cas-registration/issues/1224
- user operator form: https://github.com/bcgov/cas-registration/issues/1226
- operations form: https://github.com/bcgov/cas-registration/issues/1225
- review forms: https://github.com/bcgov/cas-registration/issues/1227
