### ISSUE TITLE
Make Sentry happy

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#1189]
#### Describe the task

We're approaching our transaction limit in Sentry. We need to reduce the number of transactions being sent.

#### Acceptance Criteria

- [x] update configs to decrease rate of transactions being sent to Sentry
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by Sepehr-Sobhani** [comment]
Thank you @pbastia for reviewing the PR for this card.
cc: @andrea-williams @hannavovk

**Comment by hannavovk** [comment]
Thanks @Sepehr-Sobhani!
