### ISSUE TITLE
Wireframes for contact management

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-registration#1194]
Once agreements are achieved between Moose & Giraffe designers on the wireframes based on the finalized IA, more detailed wireframes are needed for **contact management** to allow starting the feature development work for Reg Pt. II.

**AC:**
- [x] Review and discuss the [contact management process map](https://miro.com/app/board/uXjVNp8-wRc=/?moveToWidget=3458764581493470687&cot=14)
- [x] Create wireframes to showcase the contact management related pages and processes
- [x] Collect feedback from PO, developers and business area
- [x] Refine wireframes to address feedback
- [x] Create user story tickets with the design linked for development

**Comment by nanyangpro** [comment]
Hi @hannavovk - I drafted this ticket as discussed. Feel free to review/refine as you see fit, thanks!

**Comment by nanyangpro** [comment]
For the Contact Details page, @andrea-williams suggested to 
- allow admin to see a list of places where the contact is assigned to
- prevent admin from deleting a contact if there are still items in the list above (new contact should be assigned to those places)

**Comment by nanyangpro** [comment]
As discussed with @hannavovk, moving this ticket to the Backlog column due to the change of priority. We'll pick it up again after our problem definition meeting.

**Comment by nanyangpro** [comment]
Hi @hannavovk - This ticket is ready for you to review and can be closed with:
- The following pages designed and prototyped in Figma
    - External
        - [Contacts page](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?page-id=7692%3A2&type=design&node-id=7763-4553&viewport=193%2C219%2C0.04&t=uUj5WRuETRBzOwIz-1&scaling=scale-down&starting-point-node-id=7692%3A3728&mode=design)
        - [Add Contact page](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?page-id=7692%3A2&type=design&node-id=7763-4690&viewport=193%2C219%2C0.04&t=uUj5WRuETRBzOwIz-1&scaling=scale-down&starting-point-node-id=7692%3A3728&mode=design)
        - [Contact Details page](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?page-id=7692%3A2&type=design&node-id=7817-6&viewport=193%2C219%2C0.04&t=uUj5WRuETRBzOwIz-1&scaling=scale-down&starting-point-node-id=7692%3A3728&mode=design)
    - Internal
        - [Contacts page](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?page-id=7781%3A6398&type=design&node-id=7854-90&viewport=25%2C169%2C0.07&t=LjFXRP81lwQ0dIko-1&scaling=scale-down&starting-point-node-id=7781%3A6471&mode=design)
        - [Contact Details page](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?page-id=7781%3A6398&type=design&node-id=7854-45&viewport=25%2C169%2C0.07&t=LjFXRP81lwQ0dIko-1&scaling=scale-down&starting-point-node-id=7781%3A6471&mode=design)
- Design links added to tickets 1350, 1351, 1352, 1355, 1356
- Designs for assigning Contacts to a specific place are outside scope of ticket, and will be handled separately when I work on that specific place/page later.

**Comment by zoeyli-46** [comment]
@nanyangpro I have left a comment for you Nan on the figma page :)
