### ISSUE TITLE
Set up a CI pipeline - security scanning & checks

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#12]
We should start our CI pipeline creation by adding some security scanning & code quality checks.
There is a good set of templates here from OCIO: https://github.com/bcgov/pipeline-templates/tree/main/.github/workflows
CCBC also has a good set of these implemented in their test-code and test-containers workflow directories: https://github.com/bcgov/CONN-CCBC-portal/tree/main/.github/workflows

We can leave the unit/integration/e2e testing CI step for another ticket. This ticket should focus on security & code quality.

Checklist:
- [x] codeQL
- [x] Trivy container
- [x] Trivy Repo
- [x] SonarCloud
- [x] OWASP-Zap
- [x] Precommit (with the same hooks as CIF ie: gitleaks, detect-secrets, etc)

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-registration/12?planning-poker) with Zenhub @andrea-williams @BCerki @dleard @JoshLarouche @Sepehr-Sobhani

**Comment by JoshLarouche** [comment]
I'd love to work on this
