### ISSUE TITLE
Database setup for email notifications

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#1211]
#### Describe the task

Before we're able to tackle the user stories to send automated emails, we need to create a new database migration.

#### Acceptance Criteria

- [x] create new Django app for storing data that will be shared across multiple modules in BCIERS
- [x] create new DB table to store email content (templates)
- [x] create another new DB table to track `txId` from CHES (can serve as PK), as well as `msgId`, list of recipients, and FK to know which email template was sent 
- [x] *pending decision* - how should we handle the object lifecycle for `EmailService()`? Some options include singleton, factory for creating and destroying EmailService objects. Once strategy chosen, implement an example that can be used for email user stories. 

#### Additional context

- Some things to consider when choosing a strategy for object lifecycle: Reporting module may likely know in advance when it needs to send emails (e.g., sending reminders that a report is due on specific date), but expectation is that Registration module's emails won't be predictable as they will be triggered by human actions (e.g., requesting access, approving, etc.). This may impact how often an `EmailService` object is created/destroyed. Another consideration is that the process of renewing the access_token to the CHES API is handled automatically within the `EmailService` class.
- Blocked by #141 
- Blocking #1012, #1013, #1014 , #1015

**Comment by Sepehr-Sobhani** [comment]
If this data model is used in both the reporting and registration apps, where should it live? Maybe we need a new app where a common data model can reside!

**Comment by andrea-williams** [comment]
@Sepehr-Sobhani  I assumed we'd be creating a new db schema for common data - does that necessarily equate to a new "app" in Django?

**Comment by Sepehr-Sobhani** [comment]
@andrea-williams Kinda, but it might be a good separation in the actual code, too. We don't always look at the schema a data model belongs to. I'd like to hear Giraffe devs thoughts on this too.

**Comment by pbastia** [comment]
I think it would be odd for this to live in a registration-specific schema. I would be tempted to put each service's own data in a separate schema, since in this particular case nothing says it has to even live in the same database

**Comment by Sepehr-Sobhani** [comment]
@pbastia By `put each service's own data in a separate schema` do you mean each data model or each app? currently, both registration and reporting apps and all of their data models have the same DB schema.

**Comment by pbastia** [comment]
I think a django app to manage the email stuff wouldn't be a bad idea. It separates the service from the other layers and allows it to track its own dataset in its own schema, and deploy migrations independently.

**Comment by Sepehr-Sobhani** [comment]
@pbastia Any suggestions for naming the app that holds common services and data?

**Comment by pbastia** [comment]
I'd create a small `email_service` app? we can also nest them:
- a `common` app which would contain an `email_service` app

**Comment by pbastia** [comment]
I think if we need to share a token across multiple instances of a service, we might want to look into a Singleton instead. Otherwise we're engineering nice race conditions and ambiguity to which instance updates the cache.

With a singleton, we'll still need to be aware that we might have multiple instances running on replicas of the backend, and that each might be accessed concurrently depending on whether we have multiple gunicorn workers

**Comment by andrea-williams** [comment]
I've set up the EmailService class so that it stores its own access token and expiry info, and will only connect to CHES's auth endpoint for a new access token when its previous token has expired, so we might not need to store the token in our cache.
