### ISSUE TITLE
Update text in BORO ID approval messages

### ISSUE THREAD

**Issue by hannavovk** [bcgov/cas-registration#1258]
#### Describe the task

As an internal user clicking "approve" to issue a BORO ID, I want to see corrected language in the pop-up messages (screenshots 1 and 2).  
In both messages, "... request for carbon tax exemption" should be replaced with "application for a B.C. OBPS Regulated Operation ID". 
 

![Image](https://github.com/bcgov/cas-registration/assets/87211104/31a1db55-1e82-4bc0-a349-d2c914e1715d)

![Image](https://github.com/bcgov/cas-registration/assets/87211104/88de8ea0-ca90-4057-a41c-0d4b6412115f)

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by BCerki** [comment]
@hannavovk , should the message be changed when declining applications too? "You have declined the application for a B.C. OBPS Regulated Operation ID." and "Are you sure you want to decline this application for a B.C. OBPS Regulated Operation ID?"?

**Comment by hannavovk** [comment]
@BCerki Yes, please! Thanks

**Comment by hannavovk** [comment]
Awesome! Thanks @BCerki
