### ISSUE TITLE
Purge Jest from project

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#1260]
###Description of the Tech Debt###

As we discussed at the developer agreement session we would leave the Jest setup in the project for now and remove it once we were sure that Vitest was the correct path forward. 

- [x] Remove all jest packages and setup files
- [x] Don't remove `testing-library` packages or anything we use with `Vitest`

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |  0     |       |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |     1  |       |
| System Fault Risk - Risk of system errors or application downtime                                                             |   0    |       |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |  1     |       |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |    2   |       |
| TOTAL SCORE:                                                                                                                  |    4   |       |

**Comment by marcellmueller** [comment]
@hannavovk For your consideration I moved this to next sprint backlog if that is okay. Giraffe is going forward with Vitest and we are liking it as well so we should remove the broken Jest setup, also it won't be too much work. Thanks!

**Comment by hannavovk** [comment]
Thanks @BCerki !
