### ISSUE TITLE
Task: Create ERD for Registration app database

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#13]
Acceptance Criteria
- [x] Create an Entity Relationship Diagram (ERD) that captures the structure of the database schema for records specific to the Registration app.
- [x] Save this diagram somewhere that's accessible to everyone (maybe in the cas-registration repo?)

Additional Context
- would be helpful to create this artifact in such a way that it can be modified relatively easily, without having to recreate it every time if changes are required. With this in mind, [Mermaid](http://mermaid.js.org/) might be a good option

**Comment by Dianadec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-registration/13?planning-poker) with Zenhub @JoshLarouche @dleard @BCerki @Sepehr-Sobhani @andrea-williams
