### ISSUE TITLE
Make service layer functions @classmethod

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#1326]
###Description of the Tech Debt###

Currently in the service functions, if one function calls another in the same class, we have to repeat the full names. Instead, we could make them class methods and call them with `cls.functionname`.

- [x] put @classmethod above all service functions
- [x] add `cls` as the first argument to all service functions
- [x] when calling a class function within another function in the same class, call them like this `cls.functionname`

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |       |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |       |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |       |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |       |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |       |
| TOTAL SCORE:                                                                                                                  |       |       |

**Comment by Sepehr-Sobhani** [comment]
Addressed in: https://github.com/bcgov/cas-registration/pull/1657
