### ISSUE TITLE
How best to use forms with Django

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#135]
#### Describe the task

[RJSF](https://rjsf-team.github.io/react-jsonschema-form/) is a quick-ish way to create a form. There's a [schema file](https://github.com/bcgov/cas-registration/pull/120/files#diff-e76d100f89071523f1f6b35caa963827b1e7ef55958b9d6c266c506b3ceb4d1a:~:text=export%20const%20operationSchema%3A%20RJSFSchema%20%3D) that explains what goes in the form and [UI schema ](https://github.com/bcgov/cas-registration/pull/120/files#diff-e76d100f89071523f1f6b35caa963827b1e7ef55958b9d6c266c506b3ceb4d1a:~:text=export%20const%20operationUiSchema)that explains how it looks. 

When we retrieve data from django we receive it in a similar but not-quite-the-same format to an RJSF schema. For example, we get:
![image](https://github.com/bcgov/cas-registration/assets/77306764/d0ed4e15-ae09-49eb-b800-358eb24631e3)
But when we want to update the form, we need to tweak it to match the keys and types django accepts: https://github.com/bcgov/cas-registration/pull/120/files#diff-f59e5713d166cbc3a2a6da863f2151841301303d2db28492836a1fcc4bf646d2:~:text=const%20transformedFormData%20%3D,%7D%3B

[Django has form functionality](https://docs.djangoproject.com/en/4.2/ref/forms/) but everything I'm reading says it doesn't work well with React.

@Sepehr-Sobhani found some info on [Django forms with the Django Rest Framework](https://hackmd.io/@jish/BJ_AEzuhq#6-Helper-functions), but now that we're using Ninja instead, I don't think it transfers. 

It would nice if there was a way to use the form functionality django already has so we don't have to redo and transform data on the front end.

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by shon-button** [comment]
**Issue:** when we want to update the form, we need to tweak it to match the keys and types django accepts
**Possible Solution:** perhaps a serializers.py file to formatting the data would work better than transforming the data in the Next.js page 

**Issue:** Is there a way to use the form functionality of django within Next.js
**Possible Solution:** Use  an <iframe> to embed the Django form within a Next.js component where the src attribute points to the URL of the Django form rendered by the Django view.
