### ISSUE TITLE
Admin\Contacts - Internal User can view contacts

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-registration#1355]
#### Description:
As an Internal User, I can see the contacts page for each operator and their operations, so that I can contact the right person for the right thing

#### Acceptance Criteria:
Given that I am on the dashboard 
When I click Contacts tile
Then I am brought to the contacts grid [Figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?node-id=7854-90&t=lP4wgjHuBjopAaSN-4)

#### Development Checklist:

- [ ]

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by Sepehr-Sobhani** [comment]
Addressed in: https://github.com/bcgov/cas-registration/pull/1913

**Comment by shon-button** [comment]
@patriciarussellCAS

Reachable at:
https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/administration/contacts

**Comment by patriciarussellCAS** [comment]
Reviewed in Dev. 
Design backlog notes for future: 
-No search box for Operation or Operator column yet. [Internal users will likely need to search by Operation/Operator]
- When you click on "view details" to see a contact detail page there should be a back button (not just cancel)
