### ISSUE TITLE
Admin\Facilities - External User can view an operation's facilities and details of a facility

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-registration#1360]
#### Description:
As an industry user, given that I have access, I can view the facilities of an operation.
- [Design](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?node-id=7817-186&t=pmKjK1RmQeLYOb04-4)
- [Prototype](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?page-id=7692%3A2&type=design&node-id=7781-6342&viewport=153%2C235%2C0.04&t=9CHcuF7tZEcxkUP7-1&scaling=scale-down&starting-point-node-id=7692%3A3728)

#### Acceptance Criteria:
Given I am an industry user
When I click on the Facilities tile from the [Operation Details](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?page-id=7692%3A2&type=design&node-id=7781-6342&viewport=153%2C235%2C0.04&t=9CHcuF7tZEcxkUP7-1&scaling=scale-down&starting-point-node-id=7692%3A3728) page of an operation ,
Then I am brought to the Facilities page with the Facility grid as in the design
Then I can sort/search by columns

When I click on the View Details link of an facility
Then I'm brought to the Facility Information page of the Facility as in the prototype => **Sepehr: we need to handle this AC in** https://github.com/bcgov/cas-registration/issues/1608

#### Development Checklist:

- [x] include server-side pagination

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by zoeyli-46** [comment]
@hannavovk I think we dont need this user story because the developers are already working on the facility table?

**Comment by patrickisaac** [comment]
Notes:
- Additional refinement

**Comment by zoeyli-46** [comment]
@andrea-williams  should this ticket be also for the internal user or not? I noticed on the 1557 ticket you added cas user permission to the AC. In the description, I put that as an external user (operator), they can see the facilities table, but should the internal user part be on this ticket as well, or a separate ticket?

**Comment by nanyangpro** [comment]
Design/Prototype links are added or updated with AC refined further.

**Comment by shon-button** [comment]
@patriciarussellCAS

Reachable at:
https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/administration/operations/002d5a9e-32a6-4191-938c-2c02bfec592d/facilities?operations_title=Operation+2

**Comment by patriciarussellCAS** [comment]
Works :)
