### ISSUE TITLE
Search and sort tables/grids

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-registration#1363]
As an internal user, I want to the ability to search for, or sort alphabetically for an operator or operation, so that I can quickly find what I am looking for.
- [ ] operator table
- [ ] operation table 
- [ ] sort for columns

**Comment by hannavovk** [comment]
@zoeyli-46 is going to specify which tables / refine

**Comment by patrickisaac** [comment]
Team is already building this within each grid
