### ISSUE TITLE
Admin\Operator - External user can view "My Operator"

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-registration#1367]
#### Description:
As an External User, given that I have registered in BCIERS, I can view and update my existing operator information, and fill in any new operator information fields asked in registration part 2
[Figma link](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=8638-2726&mode=design&t=KFDAnKMzwJ3b1l14-4)

#### Acceptance Criteria:

Given I am an authenticated user with the `industry-user` or `industry-user-admin` role,
When I click on the My operator tile,
Then I am brought to my operator page
[Operator page](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=7763-4336&mode=design&t=KFDAnKMzwJ3b1l14-4) 

Given that I am on my operator page,
When I click edit
Then it turns into editing mode 
[Figma link](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=8638-2726&mode=design&t=KFDAnKMzwJ3b1l14-4)

Given that I am on the Operator Information form,
When I select General Partnership or Limited Liability Partnership 
Then the fields for a Partner appear 

Given that I am on the Operator Information form,
When I select “yes” to “Does the operator have one or more parent companies?” 
Then the fields for a parent company appear

Given that I am on the Operator Information form,
When I select “yes” to “Is the parent company registered in Canada?” 
Then I see the field “Parent Company 
CRA Business Number:” 

Given that I am on the Operator Information form,
When I select “no” to “Is the parent company registered in Canada?” 
Then I see the field “Parent Company 
Tax ID Number:” 

Edit-mode of operator information
https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=8638-2726&t=oDdZLbbRzQ0FvNal-4

#### Development Checklist:

Updates to `Parent Operator` data model:
- [ ] make `cra_business_number` field nullable
- [ ] add field `tax_id_number` (nullable, varchar)

Create new data model `Partner Company` with fields:
- [ ] `partner_legal_name` (varchar, required)
- [ ] `partner_trade_name` (varchar, nullable)
- [ ] `partner_business_structure` (FK to Business Structures table, required)
- [ ] `partner_cra_business_number` (required)
- [ ] `partner_bc_corporate_registry_number` (required)

Some other changes to data models will be required later, but because they impact existing prod data, I suggest leaving them as-is for now until we confirm with the biz area when they'd like the changes to take effect in prod.

Posibly updates dashboard tiles:
- [ ] In `bc_obps/common/fixtures/dashboard/administration/external.json\My Operator` ensure tile href is correct
- [ ] In `bc_obps/common/fixtures/dashboard/bciers/external.json\My Operator` ensure tile href is correct

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by zoeyli-46** [comment]
@nanyangpro this ticket's AC is ready for your review

**Comment by BCerki** [comment]
> @BCerki edited this ticket to include the conditional fields, does it make sense or does it require more details?

Yup, looks great, thank you!

**Comment by shon-button** [comment]
@patriciarussellCAS

Reachable at:
https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/administration/my-operator


### Test Dashboard Tile Link - My Operator:

1. Navigate to `http://localhost:3000`
2. Click button "Log in with Business BCeID"
3. Sign in to Keycloak using `bc-cas-dev`
**Expected results:** 
- Redirection to http://localhost:3000/dashboard page for role `industry_user_admin`
- Administration tile has link `My Operator`

**Comment by patriciarussellCAS** [comment]
Some initial notes on review: 
- The order of information on this page is confusing. It goes: 
     - Operator info
     - Partner company info - partner company 1
     - Operator Address
As a user I would expect all Operator information (address included) to be listed first, then partner company info after. 
- flagging that this will be a good page to include a link to the glossary, so users can confirm the terms "operator" "partner company" and "parent company" @suhafa 
- Would we allow users to continue without knowing everything for their partner company or parent company? Or do all those fields HAVE to be mandatory? (I'm wondering if they may not know the biz numbers for these off-hand and may want to skip that and come back to it later - is that an option or no?)

**Comment by zoeyli-46** [comment]
Hey @patriciarussellCAS the partner company information appears directly below if a "partnership" was selected as the business structure. We could swap the section order though if we feel it's confusing? 

Order is operator info, operator address. If they select partnership then the order is operator info, partner info, operator address. I think it makes sense cause immediately after selecting the structure is a partnership you are prompted to enter info about the partner?

**Comment by zoeyli-46** [comment]
RE: "Would we allow users to continue without knowing everything for their partner company or parent company?" I think another question is: do we allow users to continue through the entire form even without filling the fields, but they just can't submit until mandatory fields are filled?

**Comment by BCerki** [comment]
> RE: "Would we allow users to continue without knowing everything for their partner company or parent company?" I think another question is: do we allow users to continue through the entire form even without filling the fields, but they just can't submit until mandatory fields are filled?


> do we allow users to continue through the entire form even without filling the fields, but they just can't submit until mandatory fields are filled?
This is a single-page form, so the user has always been able to scroll through the whole form but can't submit it until the mandatory fields are filled. 
We don't currently have a way for users to halfway fill out a form and save it--all mandatory fields must be filled correctly before submission. But if a field actually isn't mandatory (it's ok for it to be blank for all time), we can make it optional.

**Comment by patriciarussellCAS** [comment]
> Hey [@patriciarussellCAS](https://github.com/patriciarussellCAS) the partner company information appears directly below if a "partnership" was selected as the business structure. We could swap the section order though if we feel it's confusing?
> 
> Order is operator info, operator address. If they select partnership then the order is operator info, partner info, operator address. I think it makes sense cause immediately after selecting the structure is a partnership you are prompted to enter info about the partner?

Thanks Zoey - I'm happy to leave as is, and see if it makes sense to users. :)

**Comment by patriciarussellCAS** [comment]
Unable to review in TEST but works in Dev.
