### ISSUE TITLE
Metabase Alert: Addressing False Positive Alerts Caused by Historical Records[9]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-registration#1369]
Describe the Bug:

Our current alert system in Metabase is designed based on historical records. Unfortunately, we are facing an issue where these historical records are causing false positive alerts every time the save method is invoked, even when there are no changes made to the related data model instance. This has resulted in false positive alerts from Metabase.

This ticket is for investigating modifications to Metabase SQL to address the issue and prevent false alerts.

The alert only lives in the prod metabase intance, in order to test/debug different scenarios and get it to fire in dev:
- copy the SQL code from the alert in prod metabase
- create a question in the dev metabase with that code
- change the 1 day interval to a smaller timeframe (5 minutes?)
- run the question (it should show no results at first)
- make a change to an operation that has a boro id in the dev app
- run the question (it should show results)

Probability (how likely the bug is to happen, scored from 1-5): 4
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 5
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

As an industrial user, you need to create a new operation by filling out all the fields and then submit it. Once done, log in as an IRC user and approve the operation. Then, log in again as an industrial user and go to the same operation. Before moving to different pages of an operation, you need to check the number of historical records. You can achieve this by running the below Python code snippet in the shell_plus:
```python
operation_instance = Operation.objects.get(pk='primary key of the newly created operation')
operation.history.count()
```
Now, without changing any field in the first form section of the operation, click the save and continue button. After that, check the number of historical records again. It has increased, this indicates an error because we didn't change anything.

**Comment by Sepehr-Sobhani** [comment]
@dleard Would you please take a look at these two SQL queries:

- [ ] https://cas-metabase.nrs.gov.bc.ca/question/2552-operations-with-boro-id-alert
- [ ] https://cas-metabase.nrs.gov.bc.ca/question/2553-approved-operator-alert

**Comment by dleard** [comment]
These look good! I checked some results by changing the interval to 100 days & looked at the diff that's presented and it all makes sense.
- When you replace the old alerts with the new ones, make sure to update the question description to reflect how we're now showing the diffs (in a single line now). My old descriptions will not make sense anymore (when we had a 2 line diff of everything)
- Adding a comment line in the SQL to each CTE might be helpful just to identify what each one is querying and why, it'll make it more clear what's happening to anyone that may need to read the sql in the future
