### ISSUE TITLE
Add form fields that require multiselect or foreign keys

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#138]
#### Description:

Wireframes: https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?page-id=4%3A2&type=design&node-id=5-6&viewport=365%2C284%2C0.29&t=4frrrAOPoEC9MQ8k-1&scaling=scale-down&starting-point-node-id=5%3A6&show-proto-sidebar=1&mode=design

We decided to split document upload and many-to-many field handling out of the forms tickets. This ticket is about adding many to many elements to forms. (Documents handled in https://github.com/bcgov/cas-registration/issues/325)

#### Acceptance Criteria:

Given I am logged in to the Registration app with my Business BCeID account and I have been granted "admin" role for my operator
When I navigate to the create Operation (facility) form
Then I can add regulated products, reporting activities and an exemption ID application lead to the form

Given I am logged in to the Registration app with my Business BCeID account and I have been granted "admin" role for my operator
When I navigate to the Operation (facility) Details page
Then I can view the existing regulated products, reporting activities and an exemption ID application lead associated with my operator
And I can edit regulated products, reporting activities and an exemption ID application leadfor an operation associated with my operator

~Given I am logged in to the Registration app with my Business BCeID account and I have been granted "admin" role for my operator
When I navigate to the create OperatOR form
Then I can add senior operator to the form~ already completed

~Given I am logged in to the Registration app with my Business BCeID account and I have been granted "admin" role for my operator
When I navigate to the create OperatOR form
Then I can view the existing senior operator 
And I can edit the senior operator~ already completed

#### Development Checklist:

- [ ] Add many-to-many field handling
- [ ] Add foreign key (for the contacts) handling
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by Dianadec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Moose-Sprint-Board-60d216175a2689000ec774d0/issues/bcgov/cas-registration/138?planning-poker) with Zenhub @BCerki @Sepehr-Sobhani @JoshLarouche @joshgamache @dleard @shon-button

**Comment by Dianadec** [comment]
@joshgamache  and @dleard  reminder for your estimates :)

**Comment by hannavovk** [comment]
TBD - we may leave document upload out of MVP

**Comment by BCerki** [comment]
I'm skipping design for regulated products and reporting activities (they currently look like [this] (https://www.loom.com/share/fac4414d33824944b6917a6243568b43)) because the [multiselect widget](https://github.com/bcgov/cas-registration/issues/318) will handle it and I don't want to duplicate anything.
