### ISSUE TITLE
Operations endpoint refactoring

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#1387]
Blocking #1304 
Blocked by #1282 (Has conflict)

We need to figure out how to best split the operations endpoints into different files. See the quoted comment below for some suggestions.

              > * We don't have a `user_operator` endpoint--everything is more specific--so there wasn't an example of what to do with operations/operators etc. I made a file with the plural, and a folder for the singular for anything that's more specific. Not sure about this approach--thoughts very welcome!

I suggest having API folder structure that reflects the structure of the endpoint, for example for `Operations` related endpoints we could have endpoints like:
- get all operations => `router.get("/operations")`
- get single operation => `router.get("/operations/{operation_id}")`
-  update single operation => `router.put("/operations/{operation_id}")`
- create operation => `router.post("/operations")`
- update status of operation => `router.put("/operations/{operation_id}/status")`
So, all these endpoints start with `operations` so I think it makes more sense to put them all in a folder called `operations` and split them into separate files based on each endpoint. (The confusing part here would be how to name each file 🤔)

@pbastia feel free to correct me if I'm wrong.

_Originally posted by @Sepehr-Sobhani in https://github.com/bcgov/cas-registration/issues/1323#issuecomment-2048150682_

**Comment by Sepehr-Sobhani** [comment]
Blocked by #1282 (Has conflict)

**Comment by BCerki** [comment]
This is the plan: 
operations.py
operations/{id}.py or operations/index.py or _id/details (check if you can have curly braces in filenames)
operations/id/update_status.py
