### ISSUE TITLE
IDIR Integration 

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#14]
As an internal IRC staff member, I want to be able to log in to the Registration app using my IDIR.

Acceptance Criteria:
- [x] plug in IDIR sign-in page to the Registration app homepage
- [x] add page that indicates when a user has successfully logged in with their IDIR
- [x] add Logout button to page

**User Authorization**: 
NextAuth.js is commonly used in Next.js applications when you need to add authentication and user management features to an application.

Features:
- Easy Configuration: NextAuth.js simplifies configuration with a set of providers and options.
- Multiple Identity Providers: Supports a wide range of identity providers out of the box.
- Custom Providers: You can create custom authentication providers if needed.
- Session Management: Handles session management, user sessions, and storing user data.
- JWT Support: Supports JSON Web Tokens (JWT) for secure communication between your app and the authentication server.
- Webhooks: Allows you to respond to various events, like user creation and login.

Dev Steps:
Keycloak can be used as a custom authentication provider with NextAuth.js following these general steps:

1. **Set up Keycloak**:
Set up and configure your Keycloak instance with the necessary realms, clients, and users. 

2. **Create a Custom Provider**:
  In NextAuth.js configuration, specify keycloak as custom provider including the provider name, client ID, client secret, authorization URL, token URL, etc.

3. **Implement the Provider Functions**:
   In the custom provider, implement functions are responsible for handling the authentication process and returning user data. (functions like `signIn`, `callback`, `profile`, and `session`)

4. **Define Callback and Profile Routes**:
   In Next.js, define routes for callback and profile endpoints. These routes should point to the corresponding provider functions.

5. **Configure NextAuth.js**:
   In NextAuth.js configuration, specify your custom provider and its configuration. This includes the provider name, client ID, client secret, authorization URL, token URL, and any other necessary settings.

6. **Implement User Sessions**:
   Configure NextAuth.js user session with user session data used within the DAL.

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-registration/14?planning-poker) with Zenhub @andrea-williams @BCerki @dleard @JoshLarouche @Sepehr-Sobhani

**Comment by Sepehr-Sobhani** [comment]
I think this card is also blocked by: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-registration/19
