### ISSUE TITLE
Investigate why e2e didn't catch wrong API endpoint issue[4]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-registration#1419]
Describe the Bug:

During our refactoring process, we discovered that we inadvertently used `user_operator` instead of `user-operator` in the call to check if the user is an admin. Consequently, our frontend failed to locate the corresponding API endpoint. Surprisingly, our end-to-end (e2e) test failed to flag this issue. Although we rectified the problem in this [PR](https://github.com/bcgov/cas-registration/pull/1403/files#diff-e8232ca7dcca8bd3c84ede8d9ac119d4034d115aac6afeebf3795d92b7b1ba3c), It's crucial to figure out why our e2e test didn't catch the mistake.

For this particular instance, despite having a check in our e2e, it failed to generate an error: https://github.com/bcgov/cas-registration/pull/1403#pullrequestreview-2003627569

Probability (how likely the bug is to happen, scored from 1-5):2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- Revert the change in the fix PR
- Run e2e tests especially the one mentioned here: https://github.com/bcgov/cas-registration/pull/1403#pullrequestreview-2003627569

**Comment by shon-button** [comment]
Since we have moved from generating a user's storageState using "live" login to using a "static" storageState within a GitHub secret, the storageState user session information for industry_user_admin tests has a valid app_role. Therefore, it is expected the test should pass if the GutHub secret E2E_INDUSTRY_USER_ADMIN_STORAGE is valid.

**Comment by Sepehr-Sobhani** [comment]
Link to thread: https://teams.microsoft.com/l/message/19:81544b60877c4a5eb4fc7946ecbcb525@thread.tacv2/1713376478721?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&groupId=29821293-3244-455d-beae-e01d27762cfe&parentMessageId=1713376478721&teamName=External%3A%20CAS%20-%20Clean%20Growth%20Digital%20Service%20Team&channelName=Developers&createdTime=1713376478721&ngc=true
