### ISSUE TITLE
Reg\Events - Internal User can  view transfers

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-registration#1432]
#### Description:
As an internal user, I want to see a grid of all transfers that have been reported by internal users 

#### Acceptance Criteria:

Given that I click the link "Transfers", or the Transfer tile
Then I am brought to the transfers grid
[Figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=23653-2739&t=CnLP68Qxg5Djl2uf-4)

The statuses for the grid are
- to be transferred (if the effective date has not occurred yet)
- transferred (if the effective date has occurred) 

#### Dependencies

- Blocking #1949 

#### Development Checklist:

- [x] Provide mock data (We already have a `transfer_event.json` file; we just need to confirm that it works as expected.)
- [x] modify the existing PENDING textChoice for Statuses to instead say "To be transferred" (to match wireframe)
- [x] Create a directory for transfers under the `idir` directory.
- [x] Develop a page to display the transfers grid.
- [x] Create a component to show all transfers (for example, `TransferDataGrid.tsx`).
- [x] Implement the logic for displaying the correct Status column.
- [x] Do the folder structure for both `cas_admin` and `cas_analyst`
- [x] Ensure that `Suspense` is implemented correctly.
- [x] Develop an API to list all transfers, which is accessible only to authorized internal users (including filtering functionality).
- [x] Add tests for both the back end and front end.
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by zoeyli-46** [comment]
@patriciarussellCAS @Sepehr-Sobhani here is the refined ticket for the the internal users Transfer grid

**Comment by zoeyli-46** [comment]
@andrea-williams

**Comment by patrickisaac** [comment]
Refinement Notes:
- @andrea-williams to provide Dev Checklist

**Comment by BCerki** [comment]
Until https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=85282961&issue=bcgov%7Ccas-registration%7C2427 is complete, this can only be tested by those with a cas_analyst role

**Comment by vesselak** [comment]
Tested in dev. The grid is visible.
