### ISSUE TITLE
Prepare a usability test script for registration

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-registration#151]
####Goal of Ticket

#### Describe the task

We need to prepare a usability test script for the registration module

#### Acceptance Criteria

- [x] prepare draft
- [x] prepare Registration specific questions
- [x] get review from Jairo
- [x] Review with Hanna
- [x] Confirm if we are going to test in dev or Figma

#### Additional context

- Add any other context about the task here.
- Definition of Ready
  Note: If any of the points are not applicable: delete or mark N/A
- [ ] Topic is clearly Defined.
- [ ] Task Description is Clear.
- [ ] People to speak to are identified (if applicable).
- [ ] Acceptance Criteria is Clear.
- [ ] Ticket Title is Clear.
- [ ] Ticket is reasonably Split up/sized.
- [ ] Value/Pain is Clear.
- [ ] Relevant Team Members are assigned.
- [ ] Ticket Estimated.

Definition of Done.
Note: If any of the points are not applicable: delete or mark N/A

- [ ] Rough User Stories Proposed.
- [ ] Follow-up Tickets created (if necessary).
- [ ] Findings are documented (if necessary).
- [ ] Reference docs/spreadsheets identified and indexed.
- [ ] Value Proposition Canvas (if required)

**Comment by suhafa** [comment]
@NicoleGovvy bare bones of the usability test script is here! cc: @nanyangpro @CantSeemToTagJaimie

**Comment by suhafa** [comment]
Good to be closed, created tickets #228, #233 and #214 for further work

**Comment by hannavovk** [comment]
Awesome, thanks @suhafa!
