### ISSUE TITLE
Add new route as placeholder for Part 2's revised IA structure

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#1516]
#### Describe the task

For Registration Part 2, we want to rearrange the paths of our dashboard tiles (see the IA diagram in Miro for more details). As we build out new features for Part 2 and transition to the new structure, we need to ensure that Part 1 remains as-is until we're fully prepared to roll out the new structure.

With this in mind, we can have the `/dashboard` page remain as it has been for Part 1, and create a new dashboard page called `/part-2` that will reflect the updated IA structure. There won't be any buttons/links to this `/part-2` route, so it'll just be for us insiders to navigate to and build out our new Part 2 pages. When we're ready to transition over to the new structure, we'll have the /dashboard url link to our new Part 2 structure and delete the /part-2 url.

#### Acceptance Criteria

- [ ] add a new route at the root called `/part-2` (or similar, it doesn't matter very much) that we can use as a placeholder while we transition to our new IA structure
- [ ] add a placeholder landing page for the new route
- [ ] app roles `cas_analyst`, `cas_admin`, `industry_user`, and `industry_user_admin` are able to reach the /part-2 URL
- [ ] write E2E tests asserting that each of the above app roles is able to navigate to /part-2 page (and sees placeholder content)
- [ ] the new route is NOT available in our production environment

#### Additional context

- For background info, here's the envisioned IA structure for Registration Part 2: https://miro.com/app/board/uXjVNtgEVCs=/?share_link_id=834334195000
- this is based on Andrea's proposed solution for how we manage our transition to the new IA; open to hearing other ideas
- note that this ticket is only for creating the new route (plus a placeholder landing page) - all other new pages and routing will be captured in follow-up tickets

**Comment by patrickisaac** [comment]
Notes:
- Additional discussion (Andrea to create a follow up meeting)
