### ISSUE TITLE
State Machine diagram for managing flows of data

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#1518]
#### Describe the task

Create a [state machine](https://www.itemis.com/en/products/itemis-create/documentation/user-guide/overview_what_are_state_machines#:~:text=A%20state%20machine%20is%20a,state%20transitions%20and%20produces%20outputs.) diagram that captures the flow/s of data between the Registration and Reporting modules.

Writing out a state machine that takes into account the state of data in registration (ie: operator/operation tables) and the state of the data in reporting (what an individial report data's operator/operation says) given an action or set of actions taken by the reporter may give us some insight into where we think the reporter should be able make these changes and consider the side effects of our choices here.

state: registration data
state: report 1 (complete)
state report 2 (in progress)
action: change operation name in report 2
^ How does this affect the other states (if at all)

Example of a set of states and actions that we could consider mapping:
If we change the operation data in report 2 from the reporting app, should it update the registration's operation data? Should that state change in turn trigger a state change in the data for report 1?

#### Acceptance Criteria

- [ ] how & when is Operation data from Registration fed into Reporting?
- [ ] how & when is Facility data from Registration fed into Reporting?
- [ ] what (if any) Reporting data needs to feed back into Registration?

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by patrickisaac** [comment]
Notes:
- Timebox: Half day

**Comment by patrickisaac** [comment]
Timebox - Dylan and Pierre to meet next week

**Comment by patriciarussellCAS** [comment]
Tagging @pbastia

**Comment by patrickisaac** [comment]
This ticket was followed up during Moose stand-up today (May 16) and based on Dylan's feedback, this ticket can be closed.
