### ISSUE TITLE
Update database as per form field changes

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-registration#152]
#### Describe the task

Since we created the models, we've received updated information from the business area about what information we need to collect.

The link below (tabs Admin request and Operation registration fields) shows a spreadsheet of all the information that needs to be collected in forms and stored in our db.

Link: https://bcgov.sharepoint.com/:x:/r/teams/00608-CPRInternal/Shared%20Documents/Carbon%20Pricing%20Transition%20SMEs/Registration%20Fields.xlsx?d=w30d0c9c9540644f4930683d9db06f8c3&csf=1&web=1&e=5Gk5Wd 

#### Acceptance Criteria

- [x] update the ERD. If not all the form fields seem to fit within an existing table, discuss with devs about adding more tables/changing the db structure. Contacts, senior officers, ASOs are particular ones to watch.
- [x] update the tables in `models` and make a migration
- [x] update any forms (at the time of writing this ticket, only the operations one) that were created using the old db
  - [x] rjsf form schema
  - [x] ninja schema
  - [x] django endpoints
- [ ] db tests

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by BCerki** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Moose-Sprint-Board-60d216175a2689000ec774d0/issues/bcgov/cas-registration/152?planning-poker) with Zenhub @BCerki @dleard @joshgamache @JoshLarouche @shon-button @mikevespi @Sepehr-Sobhani

**Comment by hannavovk** [comment]
Thank you @BCerki ! 
As we discussed, all the new updates based on the most recent table revisions can be a separate ticket.
