### ISSUE TITLE
Explore how Program Admin will flag issues for the Industrial Operator to fix in the app

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-registration#153]
####Goal of Ticket

#### Describe the task

We need to do some exploration on how we want to handle 'change requests' from the admin to the industrial operator. Will this be a status indicator? What would a user flow for this look like between both? We have a solution in CIIP, could we implement that? What worked for CIIP and what didn't? Do we even need this functionality? 

We will need to talk with devs to understand implications of proposed solutions. Finally, we will need to reflect the decision on a wireframe, if applicable.

#### Acceptance Criteria

- [x] explore CIIP Admin workflow for change request
- [x] explore CIIP reporter workflow for change request
- [x] make draft solution, minimum of two
- [x] Discuss solutions with Hanna
- [x] Conduct 3 amigos with SME + Devs
- [x] Finalize wireframes

#### Additional context

- Add any other context about the task here.
- Definition of Ready
  Note: If any of the points are not applicable: delete or mark N/A
- [ ] Topic is clearly Defined.
- [ ] Task Description is Clear.
- [ ] People to speak to are identified (if applicable).
- [ ] Acceptance Criteria is Clear.
- [ ] Ticket Title is Clear.
- [ ] Ticket is reasonably Split up/sized.
- [ ] Value/Pain is Clear.
- [ ] Relevant Team Members are assigned.
- [ ] Ticket Estimated.

Definition of Done.
Note: If any of the points are not applicable: delete or mark N/A

- [ ] Rough User Stories Proposed.
- [ ] Follow-up Tickets created (if necessary).
- [ ] Findings are documented (if necessary).
- [ ] Reference docs/spreadsheets identified and indexed.
- [ ] Value Proposition Canvas (if required)

**Comment by suhafa** [comment]
@hannavovk created the ticket from our discussion in refinement here, feel free to add in any more context you deem fit!

**Comment by suhafa** [comment]
Andrea's notes:
- having a comment box to capture the business area's requests for changes to an applicant's (operation's) form is considered a nice-to-have, but not essential for MVP (so we won't be building the comment functionality before Jan 2024). For MVP release, we'll have a 4th status label (in addition to "Pending", "Approved", and "Rejected") saying "Changes Requested". When reviewing an application, the program admin can set the status to Changes Requested, and then they'll email the operation outside of the app to provide explanation of what changes are needed
- once carbon tax exemption has been granted, some fields of the form will be locked (non-editable), others should remain open and editable. The business area will get back to us with their decisions for what should remain editable - at the moment we're thinking of fields that don't impact the decision of whether an exemption is granted, e.g. contact info
- versioning: for MVP, we want to minimize how many versions of an application are stored in our app, but we've identified that at a minimum we want to store the version of the application as it was when carbon tax exemption was granted, and another version (if necessary) of the most recent changes (that would exist if any of the editable fields have been updated)

**Comment by suhafa** [comment]
hey @hannavovk! Wireframes of the proposed changes requested workflow [can be found here](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=1341%3A3929&mode=design&t=kSPN5xjPb3Tj8As1-1). This ticket can be closed after your review

**Comment by hannavovk** [comment]
Great discussion! thanks @suhafa!
