### ISSUE TITLE
Fix flakey Happo screenshots

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#1538]
#### Describe the task

Now that all major workflows are tested we should fix our flakey Happo screenshots. There are quite a few now and there is a growing risk of fatigue as we see almost every run have a Happo failure. 

The two most common issues seem to be:

- The accordion screenshots due to the time it takes to animate. Suggest removing these altogether if it seems difficult to solve as we are getting rid of the accordions.
- Something weird is happening and causing missing rows in some of the tables. Since these rows are missing the DataGrid screenshots have diffs and the test is selecting the wrong row causing diffs in the forms themselves.

This may need a primary PR and then a follow up PR to catch any stragglers.

#### Acceptance Criteria

- [ ] Check all recent runs and attempt to fix flakey Happo screenshots
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by BCerki** [comment]
For the diff where a different operation is selected (sometimes the details page shows Operation 3, sometimes 5), this new function `clickViewDetailsButtonByOperationName` might help--I think we're currently selecting by index, and if the sorting changes, then we get the wrong operation. New function will come in with this PR: https://github.com/bcgov/cas-registration/pull/1596/files#diff-6950e136d90129303f1e6e1c0722547cb26f0bad15a7530faf352bbad35c0f5a

**Comment by Sepehr-Sobhani** [comment]
@marcellmueller Maybe counting table rows before taking the screenshot could help!!

**Comment by BCerki** [comment]
> @marcellmueller Maybe counting table rows before taking the screenshot could help!!

This is a good idea!
Another thing we might try is using tmate to get into the CI database and confirming that all of the mock data is definitely in the db (I don't know how it couldn't be because the test-setup endpoint couldn't have responded successfully otherwise, but @shon-button was also having some trouble with data not showing up on the details page so it might be worth confirming)
