### ISSUE TITLE
IO user can save form progress

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#155]
#### Description:

Entered form data should save (either automatically or provide a "save" button) so users can fill out form at their convenience.

Hanna/Dylan: MVP should be a save button. Stretch goal would be save as you go.
Suha:
we will also need some UI if we go ahead with the save button. 'You have unsaved changes, are you sure you want to leave this page?'

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by Dianadec** [comment]
Slightly related to form pagination ticket.

**Comment by Dianadec** [comment]
Dylan + Devs to go over the "exploration" part of this ticket.

**Comment by Dianadec** [comment]
This ticket will be adjusted to be exploration as "save as you go". The Save button has been captured in 243.

**Comment by Dianadec** [comment]
Determining whether or not we need a 3 amigos

**Comment by Dianadec** [comment]
@dleard  would you be able to update this card based on the discussions you've been having?

**Comment by Dianadec** [comment]
Update from Refinement: This work is captured in another ticket (https://app.zenhub.com/workspaces/team-moose-sprint-board-60d216175a2689000ec774d0/issues/gh/bcgov/cas-registration/359) so it might not be relevant.

**Comment by Dianadec** [comment]
Confirmed to close. cc @ Andrea, Dylan, Hanna, Nan
