### ISSUE TITLE
Update e2e test scenario: Create new operation and visit that operation details

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-registration#1555]
###Description of the Tech Debt###

We have an e2e test to create a new operation, but we don't verify if the user can see the details of the operation.

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |   2    |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |   3    |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |    2   |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |    3   |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |   1    |
| TOTAL SCORE:                                                                                                                  |       |    11   |

**Comment by BCerki** [comment]
Our e2e tests currently do not successfully create an operation (I believe we need GCS set up): 

![Image](https://github.com/bcgov/cas-registration/assets/77306764/508997c0-05e6-4ffc-9b54-c48bdc88b8b0)
