### ISSUE TITLE
Improve documentation organization

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#1556]
#### Describe the task

We have been doing a great job keeping up with documentation though it would be good to take some time and better organize it and create a table of contents so things are easy to find.

#### Acceptance Criteria

- [ ] Break the developer guide into separate files
- [ ] Create a table of contents which organizes and links all files in `/docs`

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by Sepehr-Sobhani** [comment]
@marcellmueller based on the recent changes in docs, do we still need this ticket?

**Comment by marcellmueller** [comment]
I think we can close it, nice work 🤩
