### ISSUE TITLE
(Prod) UserOperator sometimes missing from table [5]

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#1563]
Describe the Bug: CAS staff reported bug where a specific Operator was not appearing in the "Operator" (actually UserOperator) table in the UI at all, even though that operator has users and operations associated with it. 

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

See production data and UI:

- user_friendly_id=11 (another `admin` user) doesn't appear in the UserOperator table that CAS staff see because 11 was approved by user_friendly_id=10, another external user from the same operator. Thus user_friendly_id 11 should not appear in the table - in this case, the observed behaviour is correct (desired).
- user_friendly_id=19 is a `reporter` user who was approved by user_friendly_id=50 (external user), so we don't expect to see 19 in the UserOperator table (and don't), but we do expect 50 to be found in the table because they are the prime admin user who was approved by CAS. However, user_friendly_id=50 is not shown in the UserOperator table in the UI.

Screenshots:

I refuse to include screenshots because it's production data.

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by Sepehr-Sobhani** [comment]
Discussion thread: https://teams.microsoft.com/l/message/19:143b7487e8a34e28b0660f9e39d8d502@thread.tacv2/1714431856190?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&groupId=29821293-3244-455d-beae-e01d27762cfe&parentMessageId=1714431856190&teamName=External%3A%20CAS%20-%20Clean%20Growth%20Digital%20Service%20Team&channelName=Carbon%20Pricing%20Transition%20SMEs&createdTime=1714431856190&ngc=true
