### ISSUE TITLE
Add shared scaffolding for dashboard tiles

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#1577]
#### Describe the task

Need to add scaffolding for dashboard tile permissions management for all dashboards

**As a** Front-End Developer
**I want to** dynamically obtain JSON data based on a permissions from an API endpoint
**So that I can** create a dashboard navigation tiles from the JSON that reflect user role and permissions.

#### Dev Notes

- [x] Create a shared function to call dashboard API endpoint with parameters of `dashboard` type returning JSON by IdP and user app_role
- [x] Create a shared Tile component that accepts JSON data to map as dashboard tiles

#### Ac
- [ ] The API endpoint response returns JSON data by dashboard, by internal/external provider, by user app role
- [ ] The dashboard displays tiles relevant to the app, the provider, and the user's role 

#### Additional context

- Relates to #1617
Blocked by https://github.com/bcgov/cas-registration/issues/1735

**Comment by patrickisaac** [comment]
Notes:
- More conversation around this during next backlog refinement (May 7)

**Comment by marcellmueller** [comment]
https://github.com/bcgov/cas-registration/pull/1662

Tiles demo PR with updated styling for both bciers shared dashboard and registration part 2 might be helpful for this.
