### ISSUE TITLE
Registration part II components - Task list: Single-page form version

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#1587]
#### Describe the task

Check with giraffe before scheduling this--they have a ticket too: https://github.com/bcgov/cas-reporting/issues/237

Registration part II has some new components such as the side tabs and note.

#### Acceptance Criteria

- [ ] create the `Task list: Single-page form version` (not the multi page one) component using the instructions here: https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?node-id=9812%3A1767&t=i99A8cQ2Z2W6IGzP-1
- [ ] create a mock page somewhere in registration part II to show the two components (this will be deleted later but is important for testing this PR)

#### Additional context

- Needs talking to Giraffe

**Comment by patrickisaac** [comment]
Notes:
- Dev and Designer to pair on refining ticket

**Comment by hannavovk** [comment]
@nanyangpro , can you work with a dev to refine this ticket?

**Comment by nanyangpro** [comment]
Hi @marcellmueller - I see you've started development of this ticket. Just wondering if we can remove the "Backlog Refinement" label already or if there's anything that I can help clarify?

**Comment by shon-button** [comment]
@marcellmueller 

For the `Task list: Single-page form version`; specifically, the state management of the "completed checkmark" per section...
![Image](https://github.com/bcgov/cas-registration/assets/120038448/af0973e2-793e-4a64-b721-7001aa06ca5f)



I believe you mentioned in your demo that you are currently using separate forms but, would prefer to use one form; so, I thought perhaps you could use `Jotai` to listen to field section updates and manage the checkmarks.

This example demonstrates a basic form of reactive state management using Jotai, where the state of one part of your application can automatically affect other parts.

### Steps:

1. **Install Jotai**:
   If you haven't already installed Jotai, you can do so using npm or yarn:
   ```sh
   npm install jotai
   # or
   yarn add jotai
   ```

2. **Create Atoms for Your Fields**:
   Create atoms for the fields you want to listen to.

3. **Create a Derived Atom**:
   Create a derived atom that checks if the fields are complete.

4. **Update the `div` Based on the Derived Atom**:
   Use the derived atom to conditionally render or update the `div`.

### Example:

Here’s a complete example demonstrating how to listen to input fields and update a `div` when both fields are complete:

```jsx
import React from 'react';
import { atom, useAtom } from 'jotai';

// Create atoms for the fields
const field1Atom = atom('');
const field2Atom = atom('');

// Create a derived atom to check if both fields are complete
const areFieldsCompleteAtom = atom((get) => {
  const field1 = get(field1Atom);
  const field2 = get(field2Atom);
  return field1.trim() !== '' && field2.trim() !== '';
});

const Form = () => {
  const [field1, setField1] = useAtom(field1Atom);
  const [field2, setField2] = useAtom(field2Atom);
  const [areFieldsComplete] = useAtom(areFieldsCompleteAtom);

  return (
    <div>
      <input
        type="text"
        value={field1}
        onChange={(e) => setField1(e.target.value)}
        placeholder="Field 1"
      />
      <input
        type="text"
        value={field2}
        onChange={(e) => setField2(e.target.value)}
        placeholder="Field 2"
      />
      {areFieldsComplete && <div>All fields are complete!</div>}
    </div>
  );
};

export default Form;
```

### Explanation:

1. **Atoms for Fields**:
   - `field1Atom` and `field2Atom` are created to store the values of the input fields.

2. **Derived Atom**:
   - `areFieldsCompleteAtom` is a derived atom that checks if both fields have non-empty values.

3. **Input Fields**:
   - The `input` elements are controlled components that update their respective atoms on change.

4. **Conditional Rendering**:
   - The `div` element renders a message when `areFieldsCompleteAtom` evaluates to `true`.

### How It Works:
- When you type in either of the input fields, the corresponding atom (`field1Atom` or `field2Atom`) updates.
- The derived atom `areFieldsCompleteAtom` recalculates its value whenever either `field1Atom` or `field2Atom` changes.
- If both fields have non-empty values, `areFieldsCompleteAtom` returns `true`, causing the `div` to display the message "All fields are complete!".

**Comment by hannavovk** [comment]
Awesome! Thanks @marcellmueller ! Closing this out
