### ISSUE TITLE
Feature: Business BCeID for external user login

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#16]
As an "external" user (user working in heavy industry), I want to be able to sign in to the Registration app using my Business BCeID account

IO operator is able to login to OBPS to register business.

Acceptance Criteria:
- [ ] create appropriate roles in Common SSO for external users ("admin" and "reporter"?)
- [x] add Business BCeID login option to Registration app homepage
- [x] When I sign in as an external user with my Business BCeID, I should see an indication that I have successfully logged in
- [ ] ~When I'm signing in with my Business BCeID, if my user account is associated with more than one business, I should be given the option to select which business/organization I'm signing in to the Registration app for~ **Each BCeID account is only associated to one business**
- [x] After I've signed in, I want to be able to log out of my BCeID account (add logout button)

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-registration/16?planning-poker) with Zenhub @andrea-williams @BCerki @dleard @JoshLarouche @Sepehr-Sobhani

**Comment by Dianadec** [comment]
@dleard to add example of business bceid login option.

**Comment by Sepehr-Sobhani** [comment]
I think this card is also blocked by: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-registration/19

**Comment by Dianadec** [comment]
Blocked until we have an integration at least for dev cc @dleard

**Comment by hannavovk** [comment]
Link to 'roles' table: [https://miro.com/app/board/uXjVMpeqLr4=/?moveToWidget=3458764567856328665&cot=14](url)
