### ISSUE TITLE
Add sysdig alerts for registration app

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#161]
#### Describe the task

We need to set up sysdig alerts for the registration app to let us know if something we've deployed isn't healthy. A place to start is to create the alerts that we've created for CIF in registration. We should also take a look at the alerts library in sysdig and see if there are additional alerts that would be helpful.

We can copy the CIF alerts to the registration sysdig via the UI, though the promql may need tweaking because some of it is dependent on how we named things in CIF.

#### Acceptance Criteria

- [x] Create the same alerts for registration that we have in CIF. 
- [x] Make any tweaks necessary to the promql selectors
- [ ] Assess if there are more alerts from the library that would be helpful

**Comment by nanyangpro** [comment]
Re: Refinement discussion - Suggested pairing with @dleard if further context is required.

**Comment by dleard** [comment]
A set of alerts has been created in sysdig. Not sure if we should close this card & create a new one for assessing improvements or expanded metrics to alert on.
