### ISSUE TITLE
Move the logic currently done in the Tiles component to the backend & return via API

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#1617]
In navigation/Tiles.tsx we are currently doing a bunch of logic that determines which tiles to display to a user based on their role. This can probably be offloaded to the backend & returned via the API. For registration part 2 implementation, lets create an endpoint to do this work on the backend.

**Possible Architecture** (SH)
Leveraging JSONField to simplify database schema while providing the flexibility needed for dynamic or evolving data structures and requirements.
JSONField natively supports nested structures, allowing storing and querying complex hierarchical data directly within a single field.

Advantages:
- Flexibility: JSONField offers a flexible way to store various data structures, including dictionaries, lists, and nested objects. This eliminates the need for multiple database tables to represent complex relationships between data points.
- Simplified Model Definition: Compared to defining multiple relational tables and foreign keys, JSONField keeps your model definition concise and easier to maintain.
- Efficient Storage: JSONField stores data in a compact format, potentially using less space than multiple relational tables.

**Steps:**

1. Create common API Router:
- [x] create `bc_obps/common/api/router.py` using `Router`
- [x] create `bc_obps/common/api/__init__.py` to allow import of API code from other parts of your project using dot notation
- [x] create  `bc_obps/common/api/v1/dashboard_data/tiles.py/example_endpoint`
- [x] create `bc_obps/common/api/v1/__init__.py` 
- [x] in  `bc_obps/common/api/v1/__init__.py`  import tile
- [x] in `bc_obps/bc_obps/api.py` import `common.api.router`
- [x] start API server `make run`
- [x] validate endpoint `example_endpoint`
2. Create common API DashboardData endpoint service
- [x] add `class DashboardData` to `bc_obps/common/models.py`
- [x] create `bc_obps/common/schema/v1/dashboard_data.py`
- [x] create `bc_obps/common/schema/v1/__init__.py` to `from .dashboard_data import *`
- [x] create `bc_obps/service/data_access_service/dashboard_service.py`
- [x] create  `bc_obps/common/api/v1/dashboard_data/tiles.py/dashboard-data` get endpoint
- [x] create `bc_obps/common/fixtures/bciers/external.json`
- [x] create `bc_obps/common/fixtures/bciers/internal.json`
- [x] load prod data using fixtures ^
- [x] run terminal command `make migrations` which will make model migrations 
- [x] run terminal command `make reset_db` which will run model migrations and load fixtures.

AC:
- [x] an API endpoint exists for returning the dashboard tiles
- [x] the logic that is currently in Tiles.tsx is moved to the service layer for the new endpoint (the logic will be different for reg part 2 because we have different tiles)
- [ ] assess the endpoint's performance using django-silk

Additional Context:
- see bcgov/cas-registration#1653 for tiles in common dashboard
- see AC in bcgov/cas-registration#1609 for list of tiles associated with each user role
- see AC in  [1557](https://github.com/bcgov/cas-registration/issues/1557) for condition display of "Contacts Management"

~~Blocked by bcgov/cas-registration#1544~~

**Comment by dleard** [comment]
@marcellmueller @shon-button Anything to add to this ticket?

**Comment by patrickisaac** [comment]
Notes:
- Additional discussion needed (Pat to set up with Moose)

**Comment by Sepehr-Sobhani** [comment]
Better to work on this after #1544 otherwise has conflicts
