### ISSUE TITLE
Add release-it to handle release tagging & changelog generation

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#162]
#### Describe the task

Add [release-it](https://github.com/release-it/release-it) to the registation repo. Documentation for setup is on their github page & there is an example of how we have set this up previously in the CIF repo.

#### Acceptance Criteria

- [x] Add release-it to the registration repo
- [x] Create a make target `make release` to handle releases
- [x] release-it creates a changelog from conventional commits & tags release

**Comment by Dianadec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Moose-Sprint-Board-60d216175a2689000ec774d0/issues/bcgov/cas-registration/162?planning-poker) with Zenhub @BCerki @dleard @joshgamache @JoshLarouche @Sepehr-Sobhani @shon-button
