### ISSUE TITLE
Nx apps for Reg Part 1 & Reg Part 2

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#1621]
#### Describe the task
In preparation for the development of Registration Part 2's UI, we've decided to:

- Rename the current Registration Nx App to Registration1. This will prevent conflicts and maintain a clear separation between the existing functionality and the upcoming UI changes.

- Create a new Registration Nx App to serve as the foundation for building Registration Part 2's UI and should reflect codebase determined by blocking ticket  [274](https://github.com/bcgov/cas-obps/issues/274)

#### Steps

- [x] Use `nx generate @nx/workspace:move...` (see below) to move Registration part 1 into a new folder and project.
- [x] Relocate any `.env` and related untracked files (provide notes in PR for others to follow).
  - [x] Check path to folder is updated in `/bciers/tsconfig.base.json`.
- [ ] Create new commands in any referencing scripts for `registration` to the new project name. (existing ones can be reused for Registration part 2 if needed).
  - [x] `/bciers/package.json`.
  - [x] `/.github/workflows/*`.
  - [ ] `/helm/cas-registration/templates/*` and `/helm/cas-registration/values*.yaml`.
- [ ] Update any relavant docs.

> Nx has a command to move/rename projects. `nx generate @nx/workspace:move --project registration --destination apps/{NEW-PROJECT-NAME} --projectNameAndRootFormat=as-provided`, where `{NEW-PROJECT-NAME}` is the new location for the original registration applications. Almost all files will be moved from the old folder to the new one, but you may need to manually move any `.env`, `.env.local` or similar files manually.

#### Acceptance Criteria

- [x] The existing Nx workspace should contain a new app named Registration1.
- [x] Any references to the Registration app name in project configuration files or code should be updated to reflect the new name Registration1.
- [x] The original code and functionality of the Registration app is be preserved within the renamed Registration1 app.

#### Steps

- [x] Run `nx generate @nx/next:application registration...` (see below)
- [x] Copy in relevant `.env*` files from Registration part 1
- [x] Add/extend configs for:
  - [x] NextJS
  - [x] Vitest
  - [x] Tailwind/PostCSS
  - [x] Playwright 
  - [x] Happo

> Use the command `nx generate @nx/next:application registration --directory apps/registration --appDir --src=false --unitTestRunner=none --e2eTestRunner=playwright --projectNameAndRootFormat=as-provided` to use the flags that are consistent with the rest of our setup. Vitest config will need to be added. Check that `/bciers/.prettierrc` has `"singleQuote": false` or doesn't exist, as we don't enforce single quotes.

#### Acceptance Criteria

- [x] A new Nx application named Registration based on Registration1 is created within the Nx workspace.
- [ ] The Registration code is based on codebase determined by blocking ticket  [274](https://github.com/bcgov/cas-obps/issues/274)

#### Additional considerations

- [x] configure SonarCloud to ignore duplication measures on this new folder (will remove this later once we're fully switched over to Part 2)
- [x] where possible, move components over to the shared library folder of components (to be shared across Registration, Reporting, and COAM) in bciers/libs/shared/components
- [ ] include instructions for how to add/edit front-end components for Registration Parts 1 & 2 (including E2E tests and Vi-tests)
- [ ] include instructions for how to run/access Registration Parts 1 & 2 simultaneously in both local and DEV environments

 Blocked by [274](https://github.com/bcgov/cas-obps/issues/274)

**Comment by hannavovk** [comment]
To be refined post dev meeting

**Comment by marcellmueller** [comment]
Note to whoever picks up this ticket, for the acceptance criteria: `where possible, move components over to the shared library folder of components (to be shared across Registration, Reporting, and COAM) in bciers/libs/shared/components` 

I am moving some of the form components to the shared library as part of #1587

**Comment by joshgamache** [comment]
Removed blocking tag:
bcgov/cas-obps#274 is functionally complete. A draft PR (since it's not intended to be merged) [exists here](https://github.com/bcgov/cas-registration/pull/1652) as a combination between @shon-button and I's work. Comments have been left in the ticket for 274 and the PR that may be relvant during the execution for this ticket.

**Comment by hannavovk** [comment]
Added to Giraffe board as this is closely tied to the work @joshgamache is doing and once it's ready to be picked up we may need his and/or maybe @dleard DevOps guidance. (cc: @patrickisaac @patriciarussellCAS @rdromey )

**Comment by hannavovk** [comment]
FYI @marcellmueller that this ticket is no longer blocked :)
