### ISSUE TITLE
Set up Sentry for error reporting

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#164]
#### Describe the task

add Sentry to cas-registration, [example](https://github.com/bcgov/cas-ciip-portal/blob/7c6d4f21230ed703bdd2fdd38334b6e5c64212b4/app/pages/_app.tsx#L67) from CIIP

#### Acceptance Criteria

- [x] create project in Sentry interface
- [x] add necessary env vars for registration instance 
- [x] add the sentry boundary to registration app

**Comment by Dianadec** [comment]
Could be pulled in to sprint 4 or 5.
