### ISSUE TITLE
Admin\Operations - External User can view Operations grid column link "View Operation"

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-registration#1686]
#### Description:
As an industry user, given that I have access, I can view the operations owned by my operator.
- [Design](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?node-id=7763-4636&t=pmKjK1RmQeLYOb04-4)
- [Prototype](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?page-id=7692%3A2&type=design&node-id=7763-4636&viewport=153%2C235%2C0.04&t=9CHcuF7tZEcxkUP7-1&scaling=scale-down&starting-point-node-id=7692%3A3728)

#### Acceptance Criteria:
Given I am an industry user
When I click on the Operations sub link from the [BCIERS Dashboard](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?page-id=7692%3A2&type=design&node-id=7692-3728&viewport=153%2C235%2C0.04&t=9CHcuF7tZEcxkUP7-1&scaling=scale-down&starting-point-node-id=7692%3A3728) or the Operations tile from the [Registration Dashboard](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?page-id=7692%3A2&type=design&node-id=7702-4102&viewport=153%2C235%2C0.04&t=9CHcuF7tZEcxkUP7-1&scaling=scale-down&starting-point-node-id=7692%3A3728),
Then I am brought to the Operations page with the Operations grid as in the design
Then I can sort/search by columns

When I click on the View Details link of an operation
Then I'm brought to the Operation Details page of the Operation as in the prototype

#### Development Checklist:

- [x] v2 grid components
- [x] tests for v2 components
- [x] v2 operations endpoint
- [x] v2 endpoint tests
- [x] route for operations that links from the dashboard
- [x] put v2 tests into the `registration` folder (they're currently in v1 because of import errors that will be solved in the auth PR)
- [x] `getServerSession` will only be used in v1 so move it out of the global mocks and into a v1-specific mock file

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by nanyangpro** [comment]
Design/Prototype links are added or updated.

**Comment by BCerki** [comment]
Some of the work in this ticket has been completed in this merged PR: https://github.com/bcgov/cas-registration/pull/1746 and the operations components are tested. The work remaining is to hook up the grid to the dashboard and correct the routes, as well as a couple other things listed in the PR linked above.

**Comment by shon-button** [comment]
@patriciarussellCAS

Reachable at:
https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/administration/operations

**Comment by patriciarussellCAS** [comment]
Looks good!
