### ISSUE TITLE
E2E testing - which browsers to run playwright jobs in CI?

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#1742]
###Description of the Tech Debt###

We are spending a lot of time fixing issues due to flakey e2e in CI, especially with the webkit job. Shon proposed that we are letting perfect be the enemy of good and this was wasting more time and money than it was helping. Furthermore, we are also taking screenshots in 4 separate browsers in addition to running the tests in multiple browsers.

If we removed the Firefox and Webkit job in CI what would the risks be? It's worth a discussion. If we just ran the Chromium job we could also shard that and likely significantly decrease the e2e running time which will slowly balloon as we add more tests.

There is likely a small amount of risk but it's worth exploring whether that is worth all the developer hours we are spending keeping e2e going. There is a strong argument to be made that running the job in Chromium + Happo screenshots in multiple browsers is good enough.

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

**Comment by shon-button** [comment]
Resolved in https://github.com/bcgov/cas-registration/issues/1931#issue-2401314528
