### ISSUE TITLE
Setup Pylint properly

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-registration#176]
Pylint is not set up properly as a pre-commit hook. We need to add `pylint-django`, correctly point pylint to the directory, and resolve all lining issues. Examples can be found at https://github.com/bcgov/cas-registration/pull/171.

**Comment by andrea-williams** [comment]
@Sepehr-Sobhani  do you think we still need this ticket?

**Comment by Sepehr-Sobhani** [comment]
Implementing #114 so closing this one.
