### ISSUE TITLE
Task: Initialize basic React and Next.js app

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#18]
Description:
This is basic setup of frontend.

Acceptance Criteria:
- [x] use yarn for dependency management
- [x] install basic dependencies (react, next, RJSF, maybe redux?)
- [x] use next.js as webserver
- [x] initialize basic React app using next.js
- [x] create dummy homepage
- [x] add readme instructions for local frontend development
- [x] linting & formatting
- [x] is an .env file required for the frontend?
- [x] unit testing
- [ ] ~E2E testing (Dylan: might split out of this card)************************~ split into #21

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-registration/18?planning-poker) with Zenhub @andrea-williams @BCerki @dleard @JoshLarouche @Sepehr-Sobhani

**Comment by BCerki** [comment]
We didn't install redux yet since it's under discussion in dev agreements tomorrow
