### ISSUE TITLE
Configure coam app for auth sharing

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#1836]
#### Describe the task

New Nx project COAM must be configured as a Next.js multi-zone app in order to share authentication from the dashboard login session.

#### Dev Steps

- [x] In `bciers/apps/dashboard/next.config.js/./async rewrites()` add
```
{
        source: "/coam",
        destination: `${HOST_COAM}/coam`,
      },
```
- [x] In `bciers/apps/coam/next.config.js/const nextConfig` update to
```
  // To deploy a Next.js application under a sub-path of a domain you can use the basePath config option
  basePath: "/coam"
```
- [x] In `bciers/.env.example/# MULTI ZONES` add
```
HOST_COAM="http://localhost:6000"
```
- [x] In `bciers/.env/# MULTI ZONES` add
```
HOST_COAM="http://localhost:6000"
```
- [x] In `bciers/package.json/scripts/coam`  update to
```
"coam": "nx dev coam -p 6000"
```
- [x] In `bciers/package.json/scripts/dev-all`  update to
```
  "dev-all": "nx run-many -t dev -p dashboard,registration,reporting,coam",
```
- [x] Implement middleware routing similar to `bciers/apps/reporting/src/middleware.ts`
- [x] In `bciers/apps/coam/app/layout.tsx` update code to:
```
/*
A layout is UI that is shared between routes.
The app directory must include a root app/layout.js.
*/

import "@bciers/styles/globals.css";
import { RootLayout } from "@bciers/components/server";
const defaultLinks = [
  { label: "Dashboard", href: "/" },
  { label: "COAM", href: "/coam" },
];
export default function COAMLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <RootLayout defaultLinks={defaultLinks} zone="coam">{children}</RootLayout>;
}


```
- [x] In  `bciers/apps/coam/app` create `/page.tsx` 
- [x] In  `bciers/apps/coam/app/page.tsx` update code to:
```
import Tiles from "@bciers/components/navigation/Tiles";
import { fetchDashboardData } from "@bciers/actions/server";
import { ContentItem } from "@bciers/types";

export default async function Page() {
  // 🚀 API fetch dashboard tiles
  // 🚩 Source: bc_obps/common/fixtures/dashboard/coam/[IdProviderType]/role?
  const data = (await fetchDashboardData(
    "common/dashboard-data?dashboard=coam",
  )) as ContentItem[];

  return (
    <>
   // Display role based tiles here
        <Tiles tiles={data} />
    </>
  );
}
```

- [x] Optional: In folder `bc_obps/common/fixtures/dashboard/coam` add fixtures for coam dashboard tiles
- [x] Run  `cd bc_obps && make reset_db`
- [x] Run  `cd bc_obps && make run`
- [x] Run terminal command `cd bciers && yarn dev-all`
- [x] Navigate to `http://localhost:3000`
- [x] Login using bceid or idir ID
- [x] Navigate to `http://localhost:3000/coam`
- [x] Ensure the  `bciers/apps/coam/app/page.tsx`  route is displayed
- [x] Ensure the authentication session is correct

#### Acceptance Criteria

- [x] coam app shares authentication from dashboard app

#### Additional context

- Add any other context about the task here.
- Or here

#### Dependencies

- ~~Blocked by #1755~~

**Comment by gdalcengio** [comment]
Changing port 6000 to port 7000 due to port 6000 being a reserved port in use for "x11".

https://fetch.spec.whatwg.org/#port-blocking

**Comment by gdalcengio** [comment]
Yarn dev-all needed a --maxParallel flag since it was capped at 3, skipping the registration module
