### ISSUE TITLE
Use Pytest for Django testing

### ISSUE THREAD

**Issue by joshgamache** [bcgov/cas-registration#186]
Per some discussion on the the ticket initially integrating tests for Django model, it was recommended that we use Pytest (and pytest-Django) to handle testing rather than Django's testing aparatus. Pytest was already added. At a minimum, the Django tests are compatible with Pytest, so the initial move should be quick. The tests should then be refactored to match Pytest's formatting & standards for consistency and best practices.

**Comment by Sepehr-Sobhani** [comment]
Addressed in: https://github.com/bcgov/cas-registration/pull/208
