### ISSUE TITLE
Convert Registration frames into MUI components

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-registration#189]
#### Describe the task

We need to do some design exploration to get our current wireframes compatible with MUI components using Figma's design library. 

#### Acceptance Criteria

- [ ] Update the [Figma MUI](https://www.figma.com/community/file/912837788133317724/material-ui-for-figma-and-mui-x) to reflect BC Gov's design
- [ ] Implement the components for Internal user view
- [ ] Implement the components for External user view
- [ ] Create custom components if needed
- [ ] Set up session to review with devs

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by patriciarussellCAS** [comment]
@nanyangpro or @zoeyli-46 - do you think this ticket is still needed? Or can we close this? Thanks!

**Comment by nanyangpro** [comment]
Thanks for confirming, @patriciarussellCAS!

This ticket is quite outdated, and yes, we can close it unless @zoeyli-46 suggests otherwise. Thanks!
