### ISSUE TITLE
Reg\Register an Operation\Page "Operation Representative" - External user can register the operation

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-registration#1896]
#### Description:
As an industry user, given that the operation has been added to my operator, I can register the operation for IRC approval.

#### Acceptance Criteria:
Given that I am on the preceding page (either new entrant, opt in, or facility information), When I click on the save and continue button,
Then I am brought to the Operation Representative page of the form
https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=10222-77&t=5omgZedIN5xnnFFl-4

Given that I am on the Operation Representative page,
When I click on the Operation Representative dropdown, 
Then I see a list of operation representatives

Given that a contact is selected, 
display the Contact form of the selected contact for review.

Given that a new contact is added,
display the empty Contact form to be filled out.

#### Development Checklist:

- [x] edit `Operation` db model to have a many-to-many relationship on `Contact` model (django auto-generates new table `operation_contacts`)
- [x] the `operation_contacts` table must have FKs to `operation_id` and `contact_id` (django will handle this for us), and our standard audit colums (created by/at, updated by/at, archived by/at), and another column for `contact_business_role`, which contains a FK to our existing `BusinessRole` model
- [x] each step of the Registration workflow form should hit a different API endpoint
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Dependencies

- Blocked - new tickets about multi-step forms
- Blocking

**Comment by Sepehr-Sobhani** [comment]
@andrea-williams Currently, the Contacts data grid displays all contacts associated with the user's operator. However, in this ticket we are now adding contacts to the operation as well, and I believe there may be a conflict. When we add a new operation representative, should we also add them to the operator contacts? Or should we undo our recent changes and only display contacts associated with all operations of an operator?

**Comment by Sepehr-Sobhani** [comment]
@zoeyli-46 I have a couple of questions:

- What should happen when a user selects an Operation Representative from the dropdown? Should we fill the first Operation Representative form with its data?
- What is the function of the "Add them below" link?
- When a user selects an existing user from the "Is this contact a user in BCIERS?" dropdown, should we only fill in the user's first name and last name? In the contact form, we also fill in the email, phone number, and position title.

**Comment by zoeyli-46** [comment]
When a user opens the dropdown, it should display the contacts that the operator already has in their contacts grid, so the user can select from existing added contacts

Add them below function will open the “add contact” form. If the drop down doesn’t have the contact I want to use for this operation, then i will add them. The add contact form should only appear if the user click “add then below” 

If the contact is a user in BCIERS then it should prepopukate with whatever information the system has about the contact so the user doesn’t have the enter the same information twice

**Comment by Sepehr-Sobhani** [comment]
> When a user opens the dropdown, it should display the contacts that the operator already has in their contacts grid, so the user can select from existing added contacts
- **Sep**: Does anything happen to the Operation Representative form below the dropdown?
> Add them below function will open the “add contact” form. If the drop down doesn’t have the contact I want to use for this operation, then i will add them. The add contact form should only appear if the user click “add then below”
- **Sep**: Will the contact form pop up under the dropdown like a nested form?

**Comment by zoeyli-46** [comment]
The form only appears if the user clicked “add below”, by default the page does not show the form

Yes the form should pop up below the dropdown..not sure about a nested form :O

**Comment by zoeyli-46** [comment]
By default the page only has the dropdown. Then the user can pick a contact from the dropdown. Or if they click add below then the form appears :)

**Comment by shon-button** [comment]
@patriciarussellCAS

Reachable at:
https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/registration/register-an-operation

**Comment by patriciarussellCAS** [comment]
Was able to review this step using the New Entrant flow. I'll close this ticket for now but will need to review/confirm this works for each registration type/purpose.
