### ISSUE TITLE
Reg\Register an Operation\Page "Submission" - External user can register the operation

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-registration#1897]
#### Description:
As an industry user, given that the operation has been added to my operator, I can register the operation for IRC approval.

#### Acceptance Criteria:
Given that I am on the Operation Representative page,
When I click on the save and continue button,
Then I am brought to the submission page
https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=10222-146&t=5omgZedIN5xnnFFl-4

Given that I am on the submission page
The checkboxes are mandatory and must be checked in order to enable the submission button. 
If any checkbox is not checked, the submission button is disabled.

#### Development Checklist:

- [x] the checkbox data doesn't need to be saved in the DB, but we do want validation in our API to ensure that the checkboxes are actually clicked before the form can officially be submitted
- [x] Add a new Status to `Operation` data model -> `REGISTERED` and mark the operation as registered when user submits the form
- [x] each step of the Registration workflow should hit a different API endpoint
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Dependencies

- Blocked - new tickets about multi-step forms, #2133 
- Blocking #1905

**Comment by shon-button** [comment]
@patriciarussellCAS

Reachable at:
https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/registration/register-an-operation

**Comment by patriciarussellCAS** [comment]
Unable to review and test this workflow. Blocked until #2133 is complete.

**Comment by patriciarussellCAS** [comment]
The workflow is still incorrect in that every registration purpose is a New Entrant. I am closing this ticket, as the intended steps (from Operation Representative page to Submission page, and then checking all 3 boxes to click Submit) work properly.
