### ISSUE TITLE
Task: Create initial db models in Django ORM

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#19]
Based on the models created for the prototype during the hackathon, create Django ORM models for:
- organization
- facility/operation
- user_organization
- user

Note: check against data fields provided by business area/check with wireframes - there will be more data fields required than what were used in the hackathon. 

Remember to differentiate between required and optional data fields.

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-registration/19?planning-poker) with Zenhub @andrea-williams @BCerki @dleard @JoshLarouche @Sepehr-Sobhani

**Comment by Dianadec** [comment]
Dylan: Once the ERD is complete, the bullets of this card will need to be updated.

**Comment by Sepehr-Sobhani** [comment]
Do we need to test those tables too? to make sure we don't change those tables later by mistake.

**Comment by BCerki** [comment]
Creating models based on the ERD rather than the bulleted list in this card
