### ISSUE TITLE
Multi-step form: conditional number of steps depending on prior data fields

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#1910]
#### Describe the task

We want to implement a modification to our multi-step form component so that the number of steps in the form can be a conditional based on a user's inputs to certain data fields within the form.

For reference, see Step 3 of the Registration workflow in wireframe: https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=13340-2186&t=n7xnXaDQ4XbjsVDD-1
where steps in the form are dependent on the registration category/ies the external user selects

#### Acceptance Criteria

- [x] book a session with Moose devs to brainstorm/discuss implications
- [x] form schema to be generated on the frontend
- [ ] component testing performed
- [ ] python unit tests included

#### Additional context

- an external user can select multiple options from the registration category dropdown
- waiting to hear back from biz area in terms of which combos of registration category are allowed/not allowed

**Comment by patrickisaac** [comment]
Pat - Book Session for Moose devs (first AC)
