### ISSUE TITLE
Add Happo to Playwright and CI

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-registration#192]
#### Describe the task

Happo is a cross-browser screenshot testing service. It helps you test the visual appearance of your application by automatically comparing the UI with a previous version. The [happo-playwright](https://docs.happo.io/docs/playwright) module makes it easy to integrate a Playwright test suite with Happo.io. 
We also need to add Happo to our CI checks

#### Acceptance Criteria

- [x] Add Happo to e2e tests
- [x] Add Happo to CI checks

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by BCerki** [comment]
Happpo also seems to have some native screenshot testing that might work: https://playwright.dev/docs/test-snapshots
