### ISSUE TITLE
Monorepo - e2e testing setup 

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#1923]
#### Describe the task

With the shared dashboard, Registration part II and reporting development underway we need to explore how we are going to organize our e2e testing setup and run e2e tests. 

**Note:** this may need to be broken up into multiple tickets for registration and the shared dashboard

- The current Registration I auth setup should work for Registration II and shared dashboard
- We will want separate runs per project in CI to keep times down and also make failures easy to pinpoint
- Those runs will need to finalize with `e2e-finalize` and `happo-finalize`
- We can copy the POMS from registration part 1 and remove things specific to those forms 

##### Registration Part 2
- [ ] Create e2e project in the nx shared `libs` folder to add shared setup, helpers and POMS
- [ ] Create basic Registration Part II e2e test that goes to the dashboard
- [ ] Add new github action `run-registration-app` that mirrors `run-registration1-app`
- [ ] Add new Registration Part II CI e2e run - this will have to complete as a separate matrix and get merged in with e2e-finalize and Happo-finalize jobs.

##### BCIERS Dashboard: 
- [ ] Setup Dashboard e2e - this one will require `yarn dev-all` locally to run all the apps together 
- [ ] Create new github action - `run-all-apps` (or maybe there is a better name) that mirrors the current `run-registration1-app` although it will run all of the shared apps for testing the dashboard with correct . 
- [ ] Add new BCIERS dashboard CI e2e run - this will have to complete as a separate matrix and get merged in with e2e-finalize and Happo-finalize jobs.
- [ ] Create a very basic Dashboard test that goes to each app - lots of things are still changing so we don't need to waste time with thorough tests at this point

#### Technical considerations

When debugging the upload fix we tried using the shared Dockerfile in `/bciers` for registration1, however it wouldn't connect in our e2e tests for some reason. We were unable to figure out why this was, however the new Dockerfile uses the `next.config.js` setting `output: standalone` which uses a different entrypoint to start the app. 

We were able to get it to connect to the docker container by changing `--network=host` to `-p 3000:3000` in `run-registration-app` github action however many auth tests still failed. Hopefully this issue doesn't crop up, though this information may be helpful if it does.

**Comment by Sepehr-Sobhani** [comment]
![Image](https://github.com/user-attachments/assets/15cd2d66-6edd-4451-9a76-ef566b66527e)

**Comment by shon-button** [comment]
Spike for a solution leveraging [Nx inferred tasks](https://nx.dev/concepts/inferred-tasks#existing-nx-workspaces) by [migrating workpace to inferred](https://nx.dev/recipes/running-tasks/convert-to-inferred) so to allow task [atomizing/splitting of Playwright e2e tests](https://nx.dev/ci/features/split-e2e-tasks) to be used in CI for distributed task execution using [Nx agents](https://nx.dev/ci/features/distribute-task-execution) for [fast, effortless CI](https://blog.nrwl.io/fast-effortless-ci-67812514ffb4)

**Comment by shon-button** [comment]
@marcellmueller Related to our discussion on sharding; perhaps, this is a good opportunity to try and run our e2e tests in parallel and [shard the runs](https://medium.com/@divyarajsinhdev/leveraging-power-of-sharding-with-playwright-for-faster-and-scalable-testing-e3834b77f2b5)

**Comment by joshgamache** [comment]
@marcellmueller https://nx.dev/ci/features/affected#specify-which-shas-to-use-to-calculate-affected-code

The docs here include a bit of background on NX Affected in CI, and https://github.com/marketplace/actions/nx-set-shas is an action that lets you have a bit more control over what it's checking against.

**Comment by shon-button** [comment]
@marcellmueller ...some minutes from stand-up meeting:

Joshua Gamache (Unverified)
Marcel I have this saved in my notes but haven't read it in a while:  [redhat-actions/openshift-actions-runner-installer: GitHub Action to detect and create a self-hosted runner in Kubernetes.](https://github.com/redhat-actions/openshift-actions-runner-installer)
Joshua Gamache (Unverified)
I'd have to look into it again, but I think what I linked just runs github actions on the cluster, rather than in Github pods. So theoretically it could still be used for our PRs.
Bastianelli, Pierre WLRS:EX
We could make the e2e workflow a manual run: https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow
and still have it as a PR check

**Comment by patriciarussellCAS** [comment]
Thanks Marcel, I wouldn't mind an overview of this if you have time!

**Comment by marcellmueller** [comment]
Sounds good, let me know when you want a walkthrough!

**Comment by patriciarussellCAS** [comment]
@vesselak - I wonder if it makes sense to have you do a walkthrough of this instead of me. Thoughts?
