### ISSUE TITLE
Add a job to populate the dev environment with data

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#198]
We are going to need some dev data in order to be able to explore what has been deployed to dev in openshift. We should have a job that runs on pre-upgrade that clears out the database & then a job that runs post-upgrade that populates the database with dev data. These jobs should not run in prod (use the hasSuffix template and an if statement in the job to ensure this). There's an example of this conditional in the route.yaml template in the cas-reg-backend manifests.

AC:
- [ ] a job exists in the cas-reg-backend manifests with a pre-upgrade hook that drops the erc schema & cascades
- [ ] a job exists in the cas-reg-backend manifests with a post-upgrade hook that populates the database with data. There is a `make loadfixtures` target that does this locally that can probably be used here
- [ ] the jobs will not run in prod
- [ ] after deploy, the postgres datababse in openshift has dev data

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Moose-Sprint-Board-60d216175a2689000ec774d0/issues/bcgov/cas-registration/198?planning-poker) with Zenhub @Sepehr-Sobhani @dleard @mikevespi @joshgamache @JoshLarouche

**Comment by BCerki** [comment]
There's also a `make` command for dropping the db, and `reset_db` could be helpful

**Comment by dleard** [comment]
There's an api endpoint in #139 that can potentially make this work much easier. Blocking this card until that is merged to dev.

**Comment by patriciarussellCAS** [comment]
@dleard this looks like a ticket I could close. Do we still need this??

**Comment by dleard** [comment]
Yes, this can be closed. We have a process that does this for the dev environment
