### ISSUE TITLE
reg1 auth always redirects back to landing page after login

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#1981]
In the openshift dev environment for the registration1 app, `https://cas-reg-frontend-dev.apps.silver.devops.gov.bc.ca/`, auth is currently always redirecting back to the landing page instead of going to the dashboard.

To reproduce:
Go to the reg1 app & log in. After login, you will be redirected back to the landing page insead of the dashboard

**Comment by marcellmueller** [comment]
Thanks to a suggestion from Josh, setting the `cookieName` in `route.ts` seems to have fixed it same as we do in the bciers `route.ts` file:

```
import { getToken } from "next-auth/jwt";
import { NextRequest, NextResponse } from "next/server";

const cookieName =
  process.env.NODE_ENV === "production"
    ? "__Secure-authjs.session-token"
    : "authjs.session-token";

export async function GET(request: NextRequest) {
  const token = await getToken({
    req: request,
    secret: `${process.env.NEXTAUTH_SECRET}`,
    salt: cookieName,
    cookieName: cookieName,
  });
  return NextResponse.json(token, { status: 200 });
}
```

**Comment by shon-button** [comment]
@marcellmueller thank-you for taking this on 🤸‍♀️ and praise to the man @joshgamache 🦸‍♂️
