### ISSUE TITLE
BCIERS deployment to TEST

### ISSUE THREAD

**Issue by patrickisaac** [bcgov/cas-registration#2012]
**TO DO:**

~- [ ] squash migrations after the latest release tag (Not reporting app)~
- [x] Fix Deployment issues (right @marcellmueller?)
- [x] Run migrations on PROD data(test [PR](https://github.com/bcgov/cas-registration/pull/2011))

**Comment by hannavovk** [comment]
We created a placeholder ticket to be written out and refined  @patriciarussellCAS @dleard @marcellmueller @joshgamache (cc @patrickisaac )
