### ISSUE TITLE
Admin\Facilities - Add status column to grid

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-registration#2018]
For External and Internal Users, add a column to the facilities grid called "status"
The status options are
Active
Transferred
Closed
Temporarily Shutdown

[External User: Operator View Figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=7817-186&t=dIfbsyHGLhH5Wyq0-4)

[Internal User View Figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=7861-362&t=dIfbsyHGLhH5Wyq0-4)

Development checklist
- [x] add a status to the facility_designated_operation_timeline model (probably using class Statuses(models.TextChoices), see the operation statuses for an example)
- [ ] add constraint on database so that there can only be one instance of "Active" status per facility ID
- [x] edit the existing facility get endpoint to additionally fetch and filter on status
- [x] add a status column to the facility grid component
- [x] update existing api tests
- [x] update existing vitests

**Comment by BCerki** [comment]
@zoeyli-46 , I've removed `If an operation that was previously closed or temporarily shutdown, and has been reported as Restarted, the status reverts back to Active.` because I ~think this would be done in the ticket for the restart form. Unless you mean there's a status of "Restarted," but in the grid we're supposed to show it as active?

**Comment by zoeyli-46** [comment]
removed backlog tag! @BCerki

**Comment by BCerki** [comment]
@zoeyli-46 , do you know if we have a ticket for creating the facility grid for internal users? It looks like we're using the same grid for both internal/external in the app right now, but they are different in the designs

**Comment by zoeyli-46** [comment]
Hey @BCerki yes, this is the ticket https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=facilit&pane=issue&itemId=64983985 
here are all other associated facility internal user tickets
https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=facilit&pane=issue&itemId=78646387 
https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=facilit&pane=issue&itemId=77908571
https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=facilit&pane=issue&itemId=64985528
