### ISSUE TITLE
Create wireframes for Operation registration forms

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-registration#202]
#### Describe the task

Now that we have the Registration fields looked at by the business area, we can create the wireframes to reflect the new forms.

#### Acceptance Criteria

- [x] Finalize updated form design
- [x] Create new form fields using auto-layout + components in Figma referring to the Registration field
- [x] clarify questions with Jairo

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by suhafa** [comment]
@hannavovk - barebones of the ticket are here! c:

**Comment by suhafa** [comment]
@hannavovk the [wireframes have been implemented](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=1341%3A3093&mode=design&t=csTUY2KwWpDXSnRl-1), this ticket can be closed after your review (and it didn't even make it to Sprint Backlog) :P

**Comment by hannavovk** [comment]
Looking great! Thanks @suhafa!
