### ISSUE TITLE
Review forms with business area

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-registration#203]
#### Describe the task

Now that we have the wireframes of the form fields, we need to get input from Business Area as to how our users will be filling out this information. From what sources will they be gathering the documents, templates or information for the fields? We need to iron this out so that we can improve the user experience. 

#### Acceptance Criteria
- [x] Align the fields in the shared [spreadsheets](https://bcgov.sharepoint.com/:x:/r/teams/00608-CPRInternal/Shared%20Documents/Carbon%20Pricing%20Transition%20SMEs/Registration%20App/Registration%20Fields.xlsx?d=w30d0c9c9540644f4930683d9db06f8c3&csf=1&web=1&e=c8NgM1) with the latest design in Figma
- [x] Create a column explaining where the user will get this information and if it comes from any gov source, a third-party or some other place.
- [x] Ask the business area to fill out the column
- [ ] (Optional) Set up meeting with SME + Devs
- [ ] Collect information on where the user can be linked for more information on the fields

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by suhafa** [comment]
@nanyangpro @hannavovk will look into this conversation and see if there is any thing on the AC that needs updating

**Comment by nanyangpro** [comment]
AC is updated. Before I remove the "Backlog Refinement" label and get it started, could you please clarify the last AC you had from the list, @suhafa? Thanks!

**Comment by Dianadec** [comment]
@nanyangpro  can the refinement tag be removed now?

**Comment by nanyangpro** [comment]
Thanks for the reminder, @Dianadec! 

The tag is removed now with the last item discarded from the AC as discussed with Hanna:

> - [ ] Create a wireframe screen for what the 'requirements' of the form will be for the user OR add links to the fields so user can find out themselves

**Comment by nanyangpro** [comment]
As discussed with @hannavovk on Fri, Dec 1, this ticket is ready for review and can be closed with:
- the **"Template link for document upload" columns** added to the ["Registration Fields" shared spreadsheets](https://bcgov.sharepoint.com/:x:/r/teams/00608-CPRInternal/Shared%20Documents/Carbon%20Pricing%20Transition%20SMEs/Registration%20App/Registration%20Fields.xlsx?d=w30d0c9c9540644f4930683d9db06f8c3&csf=1&web=1&e=hy9lJY)
- the SME Jairo working on templates for the document upload fields
- the SME Jairo being requested to fill out the columns with the highlighted fields (i.e. the fields with the type "document upload")
