### ISSUE TITLE
Confirm the MVP copy/text with the business area

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-registration#204]
#### Describe the task

Before the MVP release, we need to allow the business area to review, revise, and approve the copy on each page/screen of the Registration module.

**Status Updates:**
According to [Hanna's Workplan](https://bcgov.sharepoint.com/:w:/r/teams/06817/_layouts/15/Doc.aspx?sourcedoc=%7BE38508C3-7B9E-418D-9D44-F05F7E7AE95F%7D&file=Workplan%20for%20App%20Release%20Prep.docx&action=default&mobileredirect=true&ovuser=6fdb5200-3d0d-4a8a-b036-d3685e359adc%2CNan.1.Yang%40gov.bc.ca&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyOC8yMzExMDIyNDcwNSIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D)
- Due: Jan 9
- Review/Revise: Tiegan/Jessica will carry it forward in Jairo's absence
_Tiegan will be back on Jan 2nd, a meeting for providing clarifications/contexts to her is scheduled on that day_
- IRC has completed the web-app language reviews and there are some changes
- Tiegan has confirmed 
    - all the mandatory change requests as "Confirmed Change Request"
    - any non mandatory change requests as "Suggested Changes"

#### Acceptance Criteria
- [x] Consult the SMEs on how they would like to review the copy on each page/screen of the Registration module (Figma? Miro? OneNote? etc.)
- [x] Provide a way for the business area to review the copy ([For SME | MVP Copy/Text Refinement](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=3422-159&mode=design) in Figma)
- [x] Support the business area in reviewing the copy and suggest changes where necessary
- [x] Reflect the decisions in Figma

#### Additional context
- Blocks #552

**Comment by suhafa** [comment]
@hannavovk - hi Hanna! Created this ticket for a catch-all for any UX copy reviewing that remains

**Comment by suhafa** [comment]
@hannavovk we can repurpose this for the plain language thinking and implementation

**Comment by nanyangpro** [comment]
**Status update:**
- After investigation, there seems no efficient way for exporting/migrating all the MVP screens to a Miro board with them visually organized the same way we have in Figma as requested by Jairo.
- Alternatively, I duplicated the MVP page in Figma, and suggested Jairo to comment directly on the page to inform us where needs copy/text updates once he finalizes them with the business area.

This ticket is a bit outdated. **To do:**
- Refine the ticket description further to reflect the current process/collabs/comms

**Comment by nanyangpro** [comment]
**Status update:**
- Jairo will be out of office after tomorrow (Wed, Dec 20)
- This work might be carried forward by Avril/Harnav/Tiegan based on their planning this afternoon, we need to confirm it during tomorrow's stand-up

**Comment by nanyangpro** [comment]
Hi @hannavovk (cc: @Dianadec ) - This ticket is ready for you to review and can be closed.
- All copy/language change requests for the MVP can be tracked from the [SME pge](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=3422-159&mode=design) in Figma.
- All frames on the [master MVP page](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=4-2&mode=design) were updated to reflect the change requests above.
- **Follow-up Tickets:**
    - The Statutory Declaration page is pending finalized bullets and a template link address. #645 
    - The Landing page is pending a few link address. #668 
    - The breadcrumbs are yet to be updated. #615
