### ISSUE TITLE
Dashboard\Tiles - External user condition if Operator record has 1 operation in status "Registered"

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-registration#2048]
#### Description:
 If an operator does not have 1 registered operation, registration tile's Register an Operation link has an "action required" notification and reporting and COAM tiles are hidden

#### Acceptance Criteria:
When I have logged in with access to an  "Operator" without any operations registered
The Administration, Registration tiles are both unhidden 
I see an "action pending" in my Registration tile next to Register an Operation
[Figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=21217-257&t=zEkU6O0dvzDho0r5-4)

Given that I registered one of my operations, then when I go back to my dashboard, the Reporting tile becomes unhidden 
[Figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=18028-9590&t=f401YGlFZz8nua2M-4)

#### Development Checklist:

- [x] Create API to return result if Operator record has 1 operation in status "Registered"
    - [x] If Operator record has 1 operation in status "Registered"
       - [x]  Display dashboard tile\link:  Registration\Register an Operation
       - [x]  Display dashboard tile: Reporting
    - [x] If Operator record does not have 1 operation in status "Registered"
       - [x]  Display dashboard tile\link:  Registration\Register an Operation - action pending
       - [x]  Do not display dashboard tile: Reporting
- [x] Add routing protections for Reporting dashboard based on if Operator record has 1 operation in status "Registered"

- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by zoeyli-46** [comment]
Hey @patriciarussellCAS this is the ticket for graying out the tiles in relation to selecting an operator/registration part 2 flow. feel free to check the prototype in the first link to see how it is intended to behave!

**Comment by zoeyli-46** [comment]
Zoey to update this ticket / split it into 2 tickets, one for the operators who are registering for the first time and one for returning operators. 
remove the "graying out" part, replace with "hide" since that is already a pattern that has been implemented.

**Comment by zoeyli-46** [comment]
@shon-button ticket has been split into this and ticket #2341 let me know if there are clarifications I can make to this ticket!

**Comment by shon-button** [comment]
Testing reference: https://github.com/bcgov/cas-registration/pull/2395
