### ISSUE TITLE
Add pytest tests to CI

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#205]
#### Describe the task

We want to run our pytest backend tests on every PR.

#### Acceptance Criteria

- [ ] Another job to `test.yaml` file to make sure pytest tests are passing
- [ ] Add this job to develop branch CI checks

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by Sepehr-Sobhani** [comment]
Addressed in https://app.zenhub.com/workspaces/team-moose-sprint-board-60d216175a2689000ec774d0/issues/gh/bcgov/cas-registration/193
