### ISSUE TITLE
DataGrid throws error if rows==undefined

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#2051]
Describe the Bug:

`bciers/libs/components/src/datagrid/DataGrid.tsx`  throws error if rows==undefined

e.g.:
http://localhost:3000/administration/operations/002d5a9e-32a6-4191-938c-2c02bfec592d/facilities?operations_title=Operation+2
![image](https://github.com/user-attachments/assets/19775dec-4b1f-4c2e-8339-65299f719a43)

**Possible Resolution:**
change const isRowsEmpty = !rows || rows.length === 0;
This way, isRowsEmpty will be true if rows is either undefined or has a length of 0.

Probability (how likely the bug is to happen, scored from 1-5):
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by marcellmueller** [comment]
@shon-button I can't seem to recreate this one (that link takes me to a working DataGrid) 🤔
