### ISSUE TITLE
Admin\Operations - External User sees button "View Facility" or "View Facilities"

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-registration#2065]
Context: SFOs should have a slightly different experience than LFOs 

As an external user, given that the operation is an SFO, then:
- [x] On the operations grid, the button should say "View Facility" instead of "View Facilities"
- [x] Given I have clicked View Facility, the facility page should skip the facilities grid page and directly go to the facility form page

**Comment by zoeyli-46** [comment]
cc @marcellmueller I'm not sure if you would be assigned to this ticket but let me know if these details are sufficient

**Comment by marcellmueller** [comment]
Looks good to me thank you!

**Comment by shon-button** [comment]
@patriciarussellCAS 

Reachable at:
https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/administration/operations?operations_title=Operation+2

**Comment by shon-button** [comment]
@patriciarussellCAS

Reachable at:
https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/administration/operations

**Comment by patriciarussellCAS** [comment]
Reviewed in Dev.
