### ISSUE TITLE
Admin & Reg\draft high-level user guide

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#2093]
#### Describe the task

Write a high-level "user guide" (from both external & internal user perspectives) for how to use the Administration and Registration modules.

The rationale for creating this doc is:
- collate the expected behaviour of the modules in one centralized place (rather than being spread across all our user story tickets)
- serve as a source-of-truth to capture workflows and data flows as agreed upon between DST and IRC
- provide more detailed explanation of expected behaviours and workflows to Moose developers than what can be captured in wireframes
- (potentially) be a starting point in the future when IRC needs to prepare their own training materials and guidance docs for external users

#### Acceptance Criteria

- [ ] in bullet-point format, describe expected behaviour of Administration module for all user workflows
- [ ] in bullet-point format, describe expected behaviour of Registration (Part 2) module for all user workflows
- [ ] in bullet-point format, explain the plans for migrating data & user flows from Reg 1 to Reg 2/Admin modules
- [x] text is stored in a Wiki page in our github repo 

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by shon-button** [comment]
@andrea-williams 

**FYI:** changing the title of a wiki page, or changing text in a header will affect any existing links to the document or the header.

e.g.
Changing `Administration ‐ External` to `Administration ‐ External ‐ User Stories` would break existing links using `https://github.com/bcgov/cas-registration/wiki/Administration-%E2%80%90-External`

So, `https://github.com/bcgov/cas-registration/wiki/Administration-%E2%80%90-External#feature-contacts---contact---add` would become `https://github.com/bcgov/cas-registration/wiki/Administration-%E2%80%90-External-%E2%80%90-User-Stories/#feature-contacts---contact---add`

**Note:** I have updated the links in https://github.com/orgs/bcgov/projects/122/views/22

**Comment by patrickisaac** [comment]
Closing ticket as discussed in standup. Wiki link for reference - https://github.com/bcgov/cas-registration/wiki
