### ISSUE TITLE
Reg\Register an operation - Registration workflow cleanup

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#2097]
#### Describe the task

Each step of the registration workflow was developed in isolation, and the `MultiStepBase` component was developed before we have any real forms, so now that we have the flow hammered out, there's some cleanup to do.

#### Acceptance Criteria

- [x] Add error handling to the `MultiStepBase` component (it handles errors that are passed in as props, but if there's an error in its submit handler, the error doesn't display): https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=80555060
- [x] remove baseUrlParams (the breadcrumbs don't show the operation title anymore) https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=80555060
- [ ] vitests (these are already covered in the form creation tickets)
- [ ] `ReportingActivity` data model was renamed to `Activity` but the endpoint remained `reporting_activities` (to minimize the impact of renaming). it would be good to rename the endpoint to reflect the data model properly.(this includes updating FE calls and BE tests) https://github.com/orgs/bcgov/projects/123/views/15?filterQuery=-status%3Adone++2222&pane=issue&itemId=80945062
- [ ] We need to be consistent with API naming. It is better to use kebab-case instead of using snake_case. :) https://github.com/orgs/bcgov/projects/123/views/15?filterQuery=-status%3Adone++2222&pane=issue&itemId=80945280
- [ ] Add caching for `get_registration_purposes` endpoint (We already have the cache invalidation in the data model) https://github.com/orgs/bcgov/projects/123/views/15?filterQuery=-status%3Adone++2222&pane=issue&itemId=80945405
- [ ] Make sure heading levels and styling are consistent and match wireframes (leaving this for now--Zoey's been making more specific tickets for this)

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by patrickisaac** [comment]
This ticket will be a placeholder/parent ticket. Child tickets will be created.

- This is not blocking anything related to registration workflow

**Comment by BCerki** [comment]
@patriciarussellCAS , closing this ticket. Links to the broken-down tickets above
