### ISSUE TITLE
Add playwright for e2e testing

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#21]
This card requires a little bit of exploration. We wanted to explore using playwright instead of cypress for e2e testing. Let's get playwright set up and write a smoke test to ensure that it is running properly in our CI process.
Playwright setup docs: https://playwright.dev/docs/intro

- [x] Add playwright dependency to the repo as a dev dependency
- [x] Add a smoke test that shows playwright is running correctly
- [x] Add an e2e CI step to run playwright tests

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-registration/21?planning-poker) with Zenhub @andrea-williams @BCerki @dleard @JoshLarouche @Sepehr-Sobhani

**Comment by hannavovk** [comment]
@dleard, does this belong under the Development Pipeline epic?

**Comment by dleard** [comment]
Maybe the Frontend Setup epic makes more sense? A workflow step to include this in the CI pipeline will also need to be added once we have this running locally.
