### ISSUE TITLE
Admin\Operations - Single Facility Operation should only be able to create 1 facility

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#2105]
#### Describe the task

The current implementation of facilities features comes with the risk that an SFO could create multiple Facilities. We should implement some safeguards that only allow an SFO to create 1 facility.

#### Acceptance Criteria

Just some thoughts - feel free to modify, add or remove some of these

- [x] Currently we are bypassing the `Facilities` DataGrid and linking an SFO to the Facility form. However the could still go to the facilities grid via URL, so we should hide the `Add Facility` button.
- [x] Add a check in the backend create facility POST route that won't allow creation of a second Facility for an SFO

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by patriciarussellCAS** [comment]
Does this need to be refined and estimated before getting pulled in? And added to the sprint?

**Comment by patrickisaac** [comment]
Sweet! Thanks @gdalcengio! I'm going to add your estimate, remove the backlog refinement label and pull it in our current sprint. A reminder that when you do move items from `backlog` or `next sprint backlog` to `In Progress`, be sure to select our current sprint too! Unfortunately, GH doesn't automatically pull things into our current sprint when we move items to `In Progress`
