### ISSUE TITLE
Admin\User Requests - New Operators no longer require approval

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#2122]
#### Describe the task

Unlike in Reg 1, IRC users no longer have the need to approve/decline requests received from external users to create new operators. Remove this functionality from Reg 2 ("Admin" module really) when/if copying over code from Reg 1.

[Figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=19862-390&t=eSq3JnHjljdh4HX0-4)

#### Acceptance Criteria

- [ ] Approve & Decline buttons no longer appear next to Operator info when internal users are reviewing prime admin access requests
- [ ] for now, keep `status`, `verified_at`, `verified_by`, `is_new` columns on `Operator` model - they can be removed once Reg2 goes live in production

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by patriciarussellCAS** [comment]
This seems like something we could get clarity on sooner than later. I'm pulling it into the next sprint backlog but think we need Business Area input in order to refine this properly.

**Comment by andrea-williams** [comment]
@patriciarussellCAS I think the business area is pretty decided that this is the path they want to take moving forward. I can't think of anything specific we need clarity on - I think we can move ahead with this ticket.

**Comment by patriciarussellCAS** [comment]
Thanks @andrea-williams Makes sense after our chat in Collab this week. Is there already a ticket for the approval for Operator who already exists but doesn't have an admin? Is this captured in #2160 ?

**Comment by andrea-williams** [comment]
deletion candidate - seems to be a duplicate of #2059

**Comment by patriciarussellCAS** [comment]
Agreed. I will close this.
