### ISSUE TITLE
App router page(s) should use Suspense to wrap data fetching child component

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#2130]
###Description of the Tech Debt###

With the App Router (using the app directory), Suspense can be used with React Server Components, allowing you to fetch data on the server while managing loading states effectively  for an improved UX.  i.e. a loading interface can be displayed while an async fetch is called in the imported component.

###Dev Check List
- [x] Verify app router pages that import async components use the Suspense wrapper

Ex: `bciers/apps/administration/app/bceidbusiness/industry_user/contacts/page.tsx` imports async component `administration/app/components/contacts/ContactsPage` without using Suspense.  
Example of using Suspense around an async component can be seen in `bciers/apps/administration/app/bceidbusiness/industry_user_admin/operations/[operationId]/facilities/[facilityId]/page.tsx` 

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |       |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |       |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |       |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |       |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |       |
| TOTAL SCORE:                                                                                                                  |       |       |

**Comment by BCerki** [comment]
I don't think this easily testable for POs, @shon-button ?

**Comment by shon-button** [comment]
> I don't think this easily testable for POs, @shon-button ?

@BCerki  Fully agree. 

I would think setting status to  `Accepted by PO or Dev` would be acceptable for these types of architectural implementations.
