### ISSUE TITLE
Reg\Register an operation - conditionally show form pages based on Registration purpose(s)

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#2133]
#### Describe the task

The Operation Registration form is meant to conditionally show form pages such as the `New Entrant Operation` and `Opted-in Operation` based on what the user selects for the `Registration Purpose` question. We have logic for this partially implemented in `OperationRegistrationPage.tsx`, however even though a user can only select one they can be assigned multiple options in the backend based on this criteria:

```
For Developers
Dropdown for “The purpose of this registration is to register as a:”
is options includes: 

Reporting Operation
OBPS Regulated Operation
Opted-in Operation
New Entrant Operation
Electricity Import Operation
Potential Reporting Operation

The user can only pick 1 option. 
all options EXCEPT “potential reporting operation” should automatically mark the user as a “reporting operation” in the back end.
if the user picks new entrant or opt in, mark the user as a Reporting AND regulated operation in the back end.
```

#### Acceptance Criteria

- [ ] Remove hardcoded `purpose`
- [ ] ~Investigate what is best to return for `Registration purpose` in the case that there are multiple purposes. An array with all of the purposes or the one that they selected/is relevant to displaying the extra form pages (New Entrant/Opted-in)? @Sepehr-Sobhani might have some thoughts on this :) (**Sep**: I think we can have a resolver to send what we are actually looking for by calling all registration purposes on the operation and returns `'Opted-in Operation'` if `OPTED_IN_OPERATION` is one of those purposes and `'New Entrant Operation'` if `NEW_ENTRANT_OPERATION` is one and ...~ There can only be 1 registration purpose selected in the UI. The case of having multiple reporting purposes only applies to the backend => **Sep:** This is correct if we don't want to fetch the purpose from the backend.
- [ ] Create resolver in `OperationOut` Django Ninja schema
- [ ] Add `OperationRegistrationPage.tsx` tests
- [ ] Also consider this: https://github.com/bcgov/cas-registration/issues/1952#issuecomment-2334928724

**Comment by patrickisaac** [comment]
`Blocking` label is added for PO checking other mentioned tickets, not development work

**Comment by patriciarussellCAS** [comment]
I believe this is blocking #2094 but please correct me if I'm wrong.

**Comment by BCerki** [comment]
> I believe this is blocking #2094 but please correct me if I'm wrong.

It doesn't block development, but it does block manual testing of 2094. Everything's a new entrant until 2094 is in

**Comment by BCerki** [comment]
Note that there's a bug (https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=facility&pane=issue&itemId=79778537) that prevents continuing past the facilities page for LFOs.

**Comment by patriciarussellCAS** [comment]
Thanks! This worked for SFO workflows, but like @BCerki mentions I couldn't complete the steps for an LFO. 
I'll close this, noting the bug ticket for that is already created.
