### ISSUE TITLE
Reg \ Add Operation Representative

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-registration#2135]
Update the operation representative screen per this Figma
[Figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=10222-77&t=Cj2ns72mqmkzHEoV-4)
Please refer to the prototype for the behaviour/interactions [Figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=18250-6164&t=Cj2ns72mqmkzHEoV-4)

- [ ] Remove the "is this contact a user in BCIERS". Reason for removal: given that someone is a user, they should automatically be added as a contact as well. therefore there isn't a need for having the "is this contact a user in bciers" field.

**Comment by Sepehr-Sobhani** [comment]
Hey @zoeyli-46 ! I think we can move the details of this ticket to ticket: #2136 and close this one.

**Comment by zoeyli-46** [comment]
Closing issue because the details of this ticket were moved to #2136
