### ISSUE TITLE
Reg\Register an Operation\Page "Operation Representative" - External user can create new Contacts by using existing user information

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-registration#2136]
#### Describe the task

This ticket covers the missing part of the ticket: https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=&pane=issue&itemId=69560403

#### Acceptance Criteria:

Given that I am on the preceding page (either new entrant, opt in, or facility information), When I click on the save and continue button,
Then I am brought to the Operation Representative page of the form
https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=18211-1609&t=4RQUxOy5Cqbs60a7-4

Given that I am on the Operation Representative page as an External user,
When the operation has existing operation representatives,
Then I see a list of operation representatives

Given that I am on the Operation Representative page as an External user,
When the operation has existing operation representatives,
Then I can see a button to add new operation representatives

Given that I am on the Operation Representative page as an External user,
When I click the button to add new operation representatives
Then I see a form to add the required info

**OPTION 1:**
Given that I am on the Operation Representative page as an External user,
When I fill out the form and click the `Save Operation Representative` button
Then I see the new operation representative being added to the operation(see: https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=18250-6024&t=OZlPtCxjAD0tYi1s-4)

**OPTION 2:**
Given that I am on the Operation Representative page as an external user, 
When I select an existing contact from the dropdown,
Then the form should be populated with the information of the selected contact(see:https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=18250-6794&t=OZlPtCxjAD0tYi1s-4(**NOTE**: First Name, Last Name and Email fields of existing contact are not editable)

Given that I am on the Operation Representative page as an external user, 
When I fill out the form for existing contact and click the `Save Operation Representative` button
Then I see the new operation representative being added to the operation(see: https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=18250-6024&t=OZlPtCxjAD0tYi1s-4)

**NOTE:**
Removing existing operation representatives will be handled in ticket: https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=81400225

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by Sepehr-Sobhani** [comment]
Will wait until we decide what to do with the Operation Representative. (User Vs. Contact)

**Comment by andrea-williams** [comment]
(radical) decision made: first name, last name, & email address should not be editable.
