### ISSUE TITLE
Create registration prototypes

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-registration#214]
#### Describe the task

Now that we have implemented comments, changes and updated form designs it is time to create prototypes for user testing.

#### Acceptance Criteria

- [x] understand test environment progress with devs
- [x] scope out which prototypes to create, and what to test in Test environment
- [x] Prepare prototypes
- [x] Create 2 flows for the different forms
- [x] Test out prototypes with Team
- [x] Create drop downs
#### Additional context

- Add any other context about the task here.
- Or here

**Comment by suhafa** [comment]
@hannavovk - created this ticket to capture work for creating prototypes

**Comment by suhafa** [comment]
This ticket can be closed. [Prototypes were created and iterated ](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?page-id=1560%3A824&type=design&node-id=1560-5463&viewport=819%2C699%2C0.06&t=iYc13AKjHCN1RdKG-1&scaling=min-zoom&starting-point-node-id=1560%3A5463&mode=design)

**Comment by hannavovk** [comment]
Thanks @suhafa!
