### ISSUE TITLE
Add BCeID authentication protection to relevant API endpoints

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#216]
#### Describe the task

We need to implement an authentication mechanism to all our API endpoints to ensure that only logged-in users can successfully send requests to our API.

Any not-authenticated user should receive a 401 Unauthorized response when they send a request to our API.

This means that each endpoint will require a token to be included in the request.

#### Acceptance Criteria

- [ ] create 2 new roles in our Common Single-Sign On integration: one for administrator-level Industrial Operators (IOs), named something like `operation_admin`; and one for standard-level IO users, named something like `operation_user` (exact wording of these can be changed as desired)
- [ ] a request with no token or an invalid token receives a 401 Unauthorized response status code when the request is sent to any of our API endpoints

Rules (by API endpoint):
- [x] GET /naics_codes: operation_admin and operation_user permitted
~~- [ ] GET /naics_categories: operation_admin and operation_user permitted~~
- [x] GET /operators: anyone authenticated with Business BCeID permitted (they don't need to have either operation_admin or operation_user role assigned to them)
- [x] GET /operations: operation_admin and operation_user NOT permitted
- [x] POST /operations: operation_admin and operation_user permitted (in order to create a brand new operation)
- [x] GET /operations/{operation_id}: operation_admin and operation_user permitted to access their own operation(s); all other operations must be BLOCKED
- [x] PUT /operations/{operation_id}: operation_admin and operation_user permitted to access their own operation(s); all other operations must be BLOCKED
- [x] POST /select-operator/request-access: operation_admin and operation_user permitted
- [x] PUT /operations/{operation_id}/update-status: operation_admin and operation_user NOT permitted
- [ ] PUT /select-operator/user-operator/{user_operator_id}: operation_admin and operation_user permitted

- [ ] update backend unit tests to include test cases checking that authentication works as expected

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by andrea-williams** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Moose-Sprint-Board-60d216175a2689000ec774d0/issues/bcgov/cas-registration/216?planning-poker) with Zenhub @andrea-williams @BCerki @Sepehr-Sobhani @JoshLarouche @shon-button @dleard

**Comment by BCerki** [comment]
We don't have this endpoint: PUT /select-operator/user-operator/{user_operator_id}: operation_admin and operation_user permitted
