### ISSUE TITLE
Disable Datagrid e2e screenshots

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#2182]
#### Describe the task

As discussed we decided to disable Registration1 Datagrid screenshots since they are causing severe Happo failure fatigue.

- [x] comment out Datagrid screenshots
- [x] create tech debt issue to resolve Datagrid screenshot issues

**Comment by marcellmueller** [comment]
Sorry that was me that put it in PO review. I wasn't sure if you wanted to review issues like these.

**Comment by patriciarussellCAS** [comment]
Thanks @marcellmueller I think I'm ok to close as is.
