### ISSUE TITLE
Don't run Happo in ShipIt

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#2190]
#### Describe the task

Outcome of Dev Team Agreements: to reduce Happo headaches, don't run Happo in ShipIt when cutting a release to any Openshift environment.

Happo will have run for each individual PR already, so removing it in the release is low-risk.

#### Acceptance Criteria

- [x] skip-check Happo in ShipIt

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by andrea-williams** [comment]
@dleard likely best candidate for refining this. I don't know what I'm doing.

**Comment by patriciarussellCAS** [comment]
Leaving in Accepted by PO/Dev until Dylan has confirmed it's working properly :)

**Comment by patriciarussellCAS** [comment]
@dleard Can we close this ticket or need to wait longer?

**Comment by patriciarussellCAS** [comment]
@dleard forgot to ask you about this one today. Do you know if this is working now?
