### ISSUE TITLE
Run all project E2E tests on merge to main

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#2210]
#### Describe the task

We are using `nx affected` to only run E2E tests in CI for projects that are affected by the current PR. This has a few benefits, namely reducing GitHub runner usage, mitigating issues from flakey tests and in some cases reducing CI running time. 

`nx affected` tries to be as safe as possible and will run all tests if anything in shared folders changes, though there is still the possibility of bugs getting through. For example a breaking change in the backend as that isn't monitored by nx affected. We should run the entire suite of E2E tests on merge to main to be safe.

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

**Comment by patriciarussellCAS** [comment]
Looks like this is in progress so I will add it to the current sprint.
