### ISSUE TITLE
Reusable function or decorator to check user can only access records associated with their operator

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#2230]
#### Describe the task

We have a variety of functions we use to check that industry users are only allowed to access their own operations, contacts, facilities, etc.
E.g.
```
if not operation.user_has_access(user_guid):
            raise Exception(UNAUTHORIZED_MESSAGE)

if user.is_industry_user() and not owner.user_has_access(user.user_guid):
            raise Exception(UNAUTHORIZED_MESSAGE)

contact = user_contacts.filter(id=contact_id).first()
        if user.is_industry_user() and not contact:
            raise Exception(UNAUTHORIZED_MESSAGE)
```

We also do this check in many but not all services, so sometimes we check access multiple times, but in other places it might not be checked at all. This ticket is about finding a more consistent way/refactor to check access.

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by pbastia** [comment]
cc @patriciarussellCAS, this is a goose item that is pretty high up on the list

**Comment by patriciarussellCAS** [comment]
Thanks Pierre. I'm moving it into Next Sprint backlog so we can refine it for next sprint

**Comment by patrickisaac** [comment]
Refinement Notes:
- To be discussed during the next API meeting

**Comment by patriciarussellCAS** [comment]
More discussion needed.

**Comment by rdromey** [comment]
Being closed as a result of ongoing exploration. New tickets will be written as a result of API meeting.
