### ISSUE TITLE
Add Postal Code Validation for `CAPostalCodeField`

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-registration#225]
###Description of the Tech Debt###

Our Django app uses the `CAPostalCodeField` data field in multiple database tables. However, there is currently no proper validation in place when saving values to the database. Although Django form validation exists, it is not currently being utilized. To ensure the accuracy of postal code data and potentially enhance the user experience, we need to address this technical debt by implementing server-side validation for `CAPostalCodeField`. In addition, we should consider implementing client-side validation for postal codes to validate data before sending it to the backend.

**Proposed Solution**:

Implement a server-side validation mechanism for `CAPostalCodeField` to ensure that only valid postal codes are saved to the database. [Django Validators](https://docs.djangoproject.com/en/4.2/ref/validators/)
Explore the option of adding client-side validation to the user interface to provide real-time feedback to users before submitting data to the backend.

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |     3  |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |       3|
| System Fault Risk - Risk of system errors or application downtime                                                             |       |    1   |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |    3   |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |       1|
| TOTAL SCORE:                                                                                                                  |       |   11    |

**Comment by andrea-williams** [comment]
@marcellmueller  we now have postal code input validation on the frontend too, don't we?

**Comment by marcellmueller** [comment]
Yes we have front end postal code validation
