### ISSUE TITLE
Registration workflow screens flash

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#2291]
Blocked by #2290 (may be solved by this)

Describe the Bug:

When navigating through the registration workflow, after clicking submit, there's a moment where we flash to the existing step before moving to the next step. To make it obvious, I turned on throttling and put in a temp loading component: https://www.loom.com/share/99f835e99463426fb3a855205c7b43d9

Probability (how likely the bug is to happen, scored from 1-5):
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by patriciarussellCAS** [comment]
I think this issue has been solved. @BCerki agree?

**Comment by BCerki** [comment]
Yes, the loading spinner fixed this
