### ISSUE TITLE
Run all BCIERS apps in CI to test inter app functionality

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#2294]
#### Describe the task

Currently we have set up e2e testing in CI to test each app which runs the Dashboard app and the app being tested (eg Reporting, Administration, Registration etc). Now that the difficult work of getting the apps to communicate properly in CI has been done we should create a `docker-compose` file and create a `Dashboard` job that runs all apps and supports testing inter-app functionality for example a user going from Registration to Administration.

The work in creating a docker-compose file/action that will run the entire app can be reused for https://github.com/bcgov/cas-registration/issues/2195

#### Acceptance Criteria

- [x] Create `docker-compose` file that runs all apps simultaneously (rather than just Dashboard and one app like the current file)
- [x] Create a `run-bciers-apps` action that can be reused that runs this compose file
- [x] Create a GitHub workflow that runs this e2e test - currently we don't have a `Dashboard` one so it makes sense to do these tests in `dashboard-e2e` project. Or maybe create `bciers-e2e`?
- [x] Write very basic tests that show Happo screenshots of all apps working correctly

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by patriciarussellCAS** [comment]
@dleard or @Sepehr-Sobhani could one of you review this for approval?

**Comment by Sepehr-Sobhani** [comment]
> @dleard or @Sepehr-Sobhani could one of you review this for approval?

@shon-button, the dragon slayer, reviewed this PR, and I'm good to approve it again. However, considering his DevOps expertise, @dleard might want to give it another look and share his thoughts.
