### ISSUE TITLE
Reg\Register an Operation\Page "Operation Representative" - External user can remove existing operation representatives from operation

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-registration#2299]
#### Description:

This ticket covers removing an existing Operation Representative from the operation

#### Acceptance Criteria:

Given that I am on the Operation Representative page as an External user,
When the operation has existing operation representatives,
Then I see a list of operation representatives and a trash icon next to it (see:https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=18250-6015&t=OZlPtCxjAD0tYi1s-4)

Given that I am on the Operation Representative page as an External user,
When I click the trash icon next to any of the existing operation representatives,
Then that operation representative gets removed from the operation.

#### Development Checklist:

- [x] Possibly a new front-end widget with read-only values and an icon next to each value that triggers an action when clicked
- [x] An API endpoint to remove an existing operation representative from an operation
- [x] Adding tests(FE and BE)
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by patriciarussellCAS** [comment]
Update ticket so it's only about removing person as an Operation Representative - not to delete the contact.

**Comment by zoeyli-46** [comment]
Every operation must have an operation representative, so we could just say "You cannot delete contacts. To change the operation representative to another contact, please go directly to the operation information form to edit the operation representative." and then there can be an "unassign" button on the contacts page instead of a "remove" option.

Check out this Figma :) does this align with what you mentioned, or do we mean something else?. https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=20692-5544&t=wKrHKv5fITGvCjvL-4

**Comment by zoeyli-46** [comment]
Instead of repurposing this one, I just created a new ticket #2327

**Comment by Sepehr-Sobhani** [comment]
> Instead of repurposing this one, I just created a new ticket #2327

We still need this functionality in order to remove existing Operation Representatives.
