### ISSUE TITLE
Create data for the test environment

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#2310]
The test environment currenlty wipes all data whenever we deploy. By default, there is no data after a fresh wipe. We should add some meaningful test data so that users can jump directly to testing later workflows (ie: reporting).

We now have two business bceid accounts for the test environment. We should choose one to have data pre-populated so that the registration workflows can be skipped & a tester can immediately go into testing reporting, or some of the later registration workflows. The other account can remain without any default data associated so that the early registration workflows can be tested.

In order to do this, we should create fixtures that create the following data after a deploy is complete:
- an approved admin from the bceid account for an operator
- an SFO operation with a boro id
- an LFO operation with a boro id
- facilities for the operations above

**Comment by pbastia** [comment]
@dleard I was recommended to use this to potentially anonymyze data https://www.pgflo.io/
Supposedly it's a new tool

**Comment by Sepehr-Sobhani** [comment]
Here are some alternative options we can consider if we ever feel like doing this in Django 😄:

[dj-anonymizer](https://pypi.org/project/dj-anonymizer/)
[django-anon](https://github.com/Tesorio/django-anon)
[django-gdpr-assist](https://github.com/wildfish/django-gdpr-assist)
[django-obfuscate](https://pypi.org/project/django-obfuscate/)
