### ISSUE TITLE
Reg\Contacts\ External user can replace an existing operation representative from Contacts Page

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-registration#2327]
#### Description:

This ticket covers replacing an existing Operation Representative from the operation

#### Acceptance Criteria:

Given that I am on the Edit Contacts page, [Figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=20869-6141&t=TiJxn6znYKYcccof-4)
I can see which operation that my representative is assigned to and a note that says "Note: To unassign this contact, please add a new contact first and then select the new contact in the corresponding operation information form." 

The operation that they are assigned to is hyperlinked. 

When I click the link to the operation, it redirects me to a single Operation Representative page for the associated operation [Figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=20906-6262&t=TiJxn6znYKYcccof-4)
On this page, I can remove the existing Operation Representative, and fill out the form to add a new representative.

#### Development Checklist:

- [ ] A new page (similar to `OperationRepresentativePage`) for both industry user and industry admin user (Possibly under `[operationId]` directory)
- [ ] Add a link in front of each operation representative that redirect user to the newly created page
- [ ] Add a test for this new link (make sure we only need this for external users)
- [ ] Modify the submit handler to redirect the user back to the contact edit form (maybe contactID as a query param???)
- [ ] Add a snackbar message once user submitted
- [ ] Make sure breadcrumb is like mockups
- [ ] Page and form already been tested, we just need to test these new conditions (vitest)
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by zoeyli-46** [comment]
@BCerki @Sepehr-Sobhani I've created this new ticket here!

**Comment by patrickisaac** [comment]
Refinement Notes:
- Will be further refined and discussed next time (Dec. 3)

**Comment by patrickisaac** [comment]
Based on discussion with team, this ticket will be captured in #2524 . Closing this one!
