### ISSUE TITLE
Make sure `waitFor` is always preceded by `await`

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#2329]
###Description of the Tech Debt###

We use `waitFor` in some of our vitests. `waitFor` is async, but in some tests the `await` that should precede it is missing. This produces tests that pass even when they shouldn't because assertions in the `waitFor` don't cause the tests to fail.

At the time of ticket writing, there are <10 instances of `waitFor` missing await.

If adding await causes the tests to fail, some solutions that worked in other tests are:
- use await findBy (async) instead of getBy (sync)
- use a locator in the waitFor instead of a variable
- e.g. in MultiStepBase

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |       |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |       |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |       |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |       |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |       |
| TOTAL SCORE:                                                                                                                  |       |       |

**Comment by Sepehr-Sobhani** [comment]
We should also await for `userEvent`s.
