### ISSUE TITLE
Make changes to wireframes based on Amos' feedback

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-registration#233]
#### Describe the task

After user testing with Amos, we got feedback that we need to implement before testing with users

#### Acceptance Criteria

- [x] Fill 'Events' tables with dates
- [x] change dashboard headings
- [x] rearrange 'My Operator' module to be last
- [x] allow user to confirm where to send the email to
- [x] 'Add user by IDIR' screen
- [x] Under actions, create 3 dots for approving or rejecting? (Added as action item in Figma)
- [x] Remove graphs? (Added comment in Figma tagging Service Designers)

Forms
- [x] Add back button
- [x] 'Have not received confirmation email?' text can be misleading. Remove
- [x] need to push 2 emails. application received + confirmation email
- [x] Facilities: Pre-populate this field? (Added to SME OneNote)
- [x] 'Proof of authority of designated operator from partner company' doesn't make sense to user (Added to SME OneNote)
- [x] Might have multiple process flow diagrams. should we get specific with our wording or allow user to upload multiple ones? (Added to SME OneNote)

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by hannavovk** [comment]
Looks good, thanks @suhafa.
