### ISSUE TITLE
Reg\Reg workflow\Operation info - No regulated products for Reporting operations

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#2337]
#### Describe the task

Currently the "Regulated Products" dropdown appears when the selected registration purpose is "Reporting Operation" - this dropdown should not appear, because reporting operations don't have regulated products.

#### Acceptance Criteria

- [x] the "regulated products" dropdown appears as a required field when the selected registration purpose is one of "OBPS Regulated", "New Entrant", or "Opt-in"
- [x] the "regulated products" dropdown DOES NOT appear in the form at all when the selected registration purpose is any of the options not listed in the first AC

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by patriciarussellCAS** [comment]
Is this already being addressed in #2224 ?

**Comment by patriciarussellCAS** [comment]
Tagging @BCerki as this is similar to the ticket you just created. Maybe we could merge them?

**Comment by BCerki** [comment]
> Tagging @BCerki as this is similar to the ticket you just created. Maybe we could merge them?

They're not particularly related in the code. This will be quick though if you want to additionally bring it in

**Comment by vesselak** [comment]
tested successfully in dev.
