### ISSUE TITLE
Dashboard\Tiles -External user condition if Operator record has required fields

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-registration#2341]
#### Dependencies

- #2047, #1960 External user can select operator/add new operator 
- Related to ticket: #2048 

#### Figma links
Please review this workflow [Figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=21217-361&t=zEkU6O0dvzDho0r5-4) to see where each screen leads to by following the arrows/text instructions

Click through this [Prototype](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=18028-10207&node-type=canvas&t=f401YGlFZz8nua2M-0&scaling=scale-down&content-scaling=fixed&page-id=7692%3A2&starting-point-node-id=18028%3A10207&show-proto-sidebar=1) to see the intended workflow for either a new user who is signing into BCIERS for an EXISTING operator, OR a returning user who already has access to an operator. 

Note: the grayed-out tiles in the prototype will be a future enhancement; for the MVP, we will implement them as hidden instead of grayed-out, because we already have the "hide tile" pattern implemented. 
 
#### Description:
During the first year of BCIERS 2025, the Operator must complete a sequence of steps. To enforce this sequence of steps, tiles will be hidden and shown to users one by one given that they completed the required step.

Given that a user (new or returning) is accessing an existing operator, these are the required steps 
1. User signs in (if they are new, they request access and wait for access to be granted) 
2. User is brought to the BCIERS dashboard
3. Only Admin tile is shown, Inside the Admin tile, the Operator link has a "action required" notification" ONLY if the associated operator is missing required fields information
4. User updates their Operator Information
5. Dashboard tile, Operator link has NO "action required" notification
6. Dashboard Registration tile displays
~~5. User is redirected to the BCIERS dashboard: only Admin and Registration and Report a Problem tiles are shown, (reporting and COAM are hidden)~~
~~6. Registration tile's Register an Operation link has an "action required" notification~~
~~7. Given that the user registers 1 operation, when they return to the BCIERS dashboard the reporting tile is unhidden and shown~~
~~8. Given that the user has submitted a report, the COAM tile is unhidden and shown (pending BA decision on when to show the COAM tile)~~

#### Acceptance Criteria:
~~Given I am logging in as a user for an **existing** operator who does not have an admin,~~
~~When I have logged in,~~
~~I have to wait for the Internal User to approve of me as an admin for the **existing** operator~~
~~Then I will be able to access the BCIERS dashboard~~
~~related to ticket: #2122 )~~

~~Given I am logging in as a user for an **existing** operator with an admin~~
~~When I have logged in,~~
~~I have to wait for the admin to approve of me,~~
~~Then I will be able to access the BCIERS dashboard~~

Given that I have access to the BCIERS dashboard, but without access to an operator
I only see the Admin\Select an Operator and Report a Problem tile

Given that I have access to the BCIERS dashboard, with access to an operator but without required fields
I only see the Admin\My Operator * action required and Report a Problem tile
[Figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=18028-9387&t=zEkU6O0dvzDho0r5-4) 

Given that I filled out the Operator Information form and clicked submit,
then I get a success snackbar that says "All changes have been successfully saved", ~~and am redirected back to~~ the BCIERS dashboard
displays  Administration\My Operator and Registration tiles

~~I see an "action pending" in my Registration tile next to Register an Operation~~
~~Given that I registered one of my operations, then when I go back to my dashboard, the Reporting tile becomes unhidden~~
~~Given that it is May 31st, or I have submitted a report (?) then the COAM tile becomes unhidden~~

#### Development Checklist:

- [ ] Create API to return result if Operator record has required fields
    - [ ] If Operator record has required fields:
       - [ ]  Display dashboard tile\link: Admin\My Operator
       - [ ]  Display dashboard tile: Registration
    - [ ] If Operator record does not have required fields:
       - [ ]  Display dashboard tile\link: Admin\My Operator * action required
       - [ ]  Do not display dashboard tile: Registration
- [ ] Add routing protections for Reg dashboard based on if Operator record has required field
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by zoeyli-46** [comment]
@shon-button I've just added this ticket after splitting it from #2048 please let me know if there are any clarifications I can make to this ticket :) 
cc @patriciarussellCAS

**Comment by shon-button** [comment]
> then I get a success snackbar that says "Operator information updated.

@zoeyli-46 

Hi Zoey, thanks for doing the updates...could you also make this additions:
-  clarify that the "Inside the Admin tile, the Operator link has a "action required" notification" ONLY if the associated operator is missing required fields information
- instead of submit message "Operator information updated. Next, register your operation.", can you display the current submit message "All changes have been successfully saved"

**Comment by zoeyli-46** [comment]
@shon-button yes, done added to the ticket
