### ISSUE TITLE
Reg\Register an Operation\Operation Information - Back button function to  operation information returns "Not found"

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#2349]
Describe the Bug:
After completing Reg\Register an Operation\Operation Information, click "Back" from Facility Information returns "Not Found"

**Reproduction steps:**
- Sign in as an industry user with access to an operator (example: 'bc-cas-dev' user)
- Navigate to "Register an Operation"
- In Operation Information, complete required fields
 - Click 'Save and Continue'
- In Facility Information, click 'Back'

**Results:**
![image](https://github.com/user-attachments/assets/a5584842-ff2f-456d-9036-056e61b0b5f2)

Probability (how likely the bug is to happen, scored from 1-5):
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by vesselak** [comment]
The back button clears the data. Please review if this requires another bug ticket @Sepehr-Sobhani

**Comment by vesselak** [comment]
Accepting the ticket as this bug fix passed testing. Reviewing why the back button clears the data on the form.

**Comment by Sepehr-Sobhani** [comment]
> The back button clears the data. Please review if this requires another bug ticket @Sepehr-Sobhani

@vesselak This is related to a broader discussion that has been on our radar for a while, and we haven't figured out how to fully resolve it. Here is the ticket: https://github.com/orgs/bcgov/projects/123/views/15?pane=issue&itemId=80445750&issue=bcgov%7Ccas-registration%7C2169
