### ISSUE TITLE
Evaluate /test-setup endpoint

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#235]
#### Describe the task

For our CI e2e tests, we use an endpoint. More details here: 

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by BCerki** [comment]
@Sepehr-Sobhani explored different approaches for e2e db setup/teardown and this endpoint seems to be the best option (custom function to convert from django json data to raw sql is complicated and hard to maintain, doing all the setup from global.ts and then cleaning up individual tests instead of wipe/reset was determined to be too labour-intensive/error-prone)

**Comment by andrea-williams** [comment]
Closing - doesn't seem to be any actual work captured in this ticket
