### ISSUE TITLE
Reg\Dashboard - External user tiles have correct text descriptions

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#2350]
#### Describe the task

Registration dashboard tiles have TDB description.

![Image](https://github.com/user-attachments/assets/55ac6ed0-d0ee-4ef1-b764-77862a908bc6)

#### Acceptance Criteria

- [ ] Registration dashboard tiles should have text descriptions as defined by the business
- [ ] see [Figma wireframe](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=22844-976&t=HUuLJ35QNOYlqbvu-4) for descriptions

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by patriciarussellCAS** [comment]
To confirm - are we removing event tiles? what language goes here instead?

**Comment by andrea-williams** [comment]
@patriciarussellCAS my plan is to update the "Report an Event" tile's description but then hide it since it won't be included in MVP.

**Comment by patriciarussellCAS** [comment]
Thanks @andrea-williams. If we hide the Report an Event tile, do we have anywhere else where we explain they have to email ghgregulator about events? @zoeyli-46

**Comment by zoeyli-46** [comment]
Sorry, @andrea-williams In the design, if they click "report event" it will go to the instructions page which will be a part of MVP https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=23217-5751&t=ZBw6geuOauX8OqCY-4 here it is

**Comment by patriciarussellCAS** [comment]
@andrea-williams @zoeyli-46 - it looks like we still need the report an event tile, or something on this page to get to the instruction page that zoey linked above. Is this in a separate ticket?

**Comment by zoeyli-46** [comment]
I just made a ticket for the transfers tile for industry users. https://github.com/orgs/bcgov/projects/123/views/16?filterQuery=repo%3Abcgov%2Fcas-registration+reg%5Ceve&pane=issue&itemId=88779475&issue=bcgov%7Ccas-registration%7C2528 

lets make a separate ticket for the edits to the other tiles in BCIERS.

**Comment by patriciarussellCAS** [comment]
Thanks! I'll mark this as approved then.
