### ISSUE TITLE
Reg\Register an Operation\Operation Representative - Back button function to operation representative returns "Not found"

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#2354]
Describe the Bug:
After completing Reg\Register an Operation\Operation Representative, click "Back" from Submission page returns "Not Found"

**Reproduction steps:**
- Sign in as an industry user with access to an operator (example: 'bc-cas-dev' user)
- Navigate to "Register an Operation"
- In Operation Information, complete required fields
 - Click 'Save and Continue'
- In Facility Information, complete required fields
 - Click 'Save and Continue'
- In Operation Representative, complete required fields
 - Click 'Save and Continue'
- In Submission, click 'Back'

**Results:**
![image](https://github.com/user-attachments/assets/a5584842-ff2f-456d-9036-056e61b0b5f2)
![image](https://github.com/user-attachments/assets/d8e58e81-5ccd-4658-af4b-df64b4afdf40)

Probability (how likely the bug is to happen, scored from 1-5):
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by dleard** [comment]
@Sepehr-Sobhani  @vesselak We're accepting this ticket as complete as the back button does go back to the correct page now.
However, new bug tickets may be needed for: 
- when redirected back to the operation representative page the person selected is now immutable & the only option is to add a new one.
- cancel button throws an error when clicked

**Comment by Sepehr-Sobhani** [comment]
> @Sepehr-Sobhani @vesselak We're accepting this ticket as complete as the back button does go back to the correct page now. However, new bug tickets may be needed for:
> 
> * when redirected back to the operation representative page the person selected is now immutable & the only option is to add a new one.
> * cancel button throws an error when clicked

Thanks for accepting this ticket. 
- This issue has already been captured as a separate ticket: https://github.com/orgs/bcgov/projects/123/views/15?pane=issue&itemId=81400225&issue=bcgov%7Ccas-registration%7C2299. 
- I have tested this and wasn't able to reproduce this issue. Could you please share the steps you took when facing this issue?

**Comment by dleard** [comment]
When the cancel button threw an error this is what I did:
pressed the 'back' button to the operation representative page
clicked 'add new operation representative'
clicked 'cancel'
Then the page erored out
