### ISSUE TITLE
Remove "Operation Representative" from user profile page title

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#2399]
#### Describe the task

Change text in title: ![Image](https://github.com/user-attachments/assets/cf0c324b-1740-4240-9283-66cb7ea0cff3)
To be more generally about user

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by BCerki** [comment]
@patriciarussellCAS , for IDIR users it just says "Please update or verify your information". Will that work for industry users too, or did you want it to say "Please update or verify your information as a user"

**Comment by patriciarussellCAS** [comment]
Thanks @BCerki I think just "please update or verify your information" works for both.
