### ISSUE TITLE
User story: IO user requests access to be prime admin for Operator (organization)

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#24]
#### Description:

~~As an org rep, I want to complete the organization profile so that  I can start registering facilities~~ ("org profile"=filling out the form to request to register)

~~As an IO, I want to complete the operator (organization) profile so that  I can start registering facilities~~

~~As an IO, I want to register my operator (organization) by filling out a form so that I can register for OBPS~~

As John Smith (aka Prime Gertrude), I want to submit a request to become the prime admin for my company, 123 Co.
Assumption: John has already logged in to his individual BCeID account, which is connected to 123 Co.'s Business BCeID (so that we can confirm John is associated with 123 Co.)

See https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/Registration-app?type=design&node-id=4-2&mode=design&t=lp8DwUm6T8XDYKso-0 for wireframes

#### Acceptance Criteria:

Given I am an external user logged in to my Business BCeID account
When my company already exists in the Registration database but no prime admin has been assigned to the company yet
Then a record should be created in the database that captures my request to be the prime admin in OBPS for my company

Given I am an external user logged in to my Business BCeID account
When my company already exists in the Registration database and a prime admin has already been assigned (approved) to my company
Then I cannot submit a request to be prime admin for my company (subsequent ticket will address what page the user should be presented with instead)

#### Development Checklist:

- [x] when the API receives a valid request to be prime admin, database should be updated to indicate that John Smith submitted the request
    - [x] display Success page from Prime Gertrude's perspective to know that their request has been submitted
- [x] when the API receives a new request for a prime admin for a company that already has an assigned prime admin, there is no need to record this in the database
    - [x] ~display temporary "NO!" page to John Smith so that he knows that he can't be prime admin because someone else already is prime admin for his company~ Display an error if the company already has a prime admin
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [x] Acceptance criteria are tested by the CI pipeline
- [x] UI meets accessibility requirements
- [x] Configuration changes are documented, documentation and designs are updated
- [x] Passes code peer-review
- [x] Passes QA of Acceptance Criteria with verification in Dev and Test
- [x] Ticket is ready to be merged to main branch
- [x] Can be demoed in Sprint Review
- [x] Bugs or future work cards are identified and created
- [x] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by andrea-williams** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-registration/24?planning-poker) with Zenhub @andrea-williams @BCerki @dleard @JoshLarouche @Sepehr-Sobhani

**Comment by BCerki** [comment]
Is the "organization profile" the form Prime Gertrude will have to fill out before clicking "request access to the registration app"?

**Comment by Sepehr-Sobhani** [comment]
We won't be able to test this until we receive development data from https://app.zenhub.com/workspaces/team-moose-sprint-board-60d216175a2689000ec774d0/issues/gh/bcgov/cas-registration/198.
