### ISSUE TITLE
Creation of `cas-director` user role

### ISSUE THREAD

**Issue by patrickisaac** [bcgov/cas-registration#2493]
#### Description:
As a `cas-director` user, I should have all functionalities listed in this [table](https://miro.com/app/board/uXjVKdOp2dg=/?share_link_id=560390359720).

#### Acceptance Criteria:
- [x] Manage first-time operator admin role approvals
- [x] Assign BORO ID/BCGHG ID

#### Development Checklist:

- [x] migration to add the cas_director role (e.g. of adding cas_analyst: cas-registration/bc_obps/registration/migrations/0002_prod_data.py)
- [x] in `cas-registration/bciers/apps/registration/app/idir`, create a cas_director folder. Copy/paste the structure of cas_admin into this folder (cas_director is allowed to access everything)
- [x] add cas_director to the "access_roles" in the `internal.json` files to give cas_director users access to all dashboard tiles
- [x] Previously all internal users had the same permissions, so many parts of the app use an `isInternalUser` or `isAuthorizedAdminUser` variable to determine whether to show/hide/allow editing. Change these conditionals to only allow cas_director to assign bcghg id and boro id
- [x] first-time operator admin role approvals access is controlled by a dashboard tile (if users have the tile, they can do it) so no changes needed
- [x] Check and update the endpoint and service permissions for this new role to ensure the user has the correct access.

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by vesselak** [comment]
Tested in dev and accepting with the following notes:

A couple of notes for testing:

We haven't built first-time operator admin role approvals yet, so right now a cas_director can access the tile, but they can't actually approve yet
The transfer form also isn't built yet. cas_director has view access to it, so again they can see the tile (minus the link to the editable form), and once the form is built, they'll be able to view via the grid
