### ISSUE TITLE
UAT Bug-The ‘Action Required’ prompt did not show up for me

### ISSUE THREAD

**Issue by TammieV-BCG** [bcgov/cas-registration#2506]
#### Describe the Bug:
The ‘Action Required’ prompt did not show up for me.  

#### Steps to reproduce the behaviour:
1. Log-In  
2. See that there is no ‘Action Required’ prompt beside my operator. 

#### Screenshots:
![Image](https://github.com/user-attachments/assets/31904b3d-d832-4122-a61a-6f4369d2f4c7)

#### Additional information:
Browser: chrome, edge

#### Additional Context
User Story: As an External User, given that I already applied for a BORO ID, when I sign into BCIERS for the first time since Reg 2 opened, I see a prompt "Action Required" next to My Operator. This message disappears after I fill in any blank My Operator fields
 
Link to UAT ticket: https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/mytasks?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fv1%2Fplan%2FbyyJUkJggkaPhsw6jAP-oWUAGWDg%2Ftask%2FEnk4pwJYRkyN2AyPgQz1JWUAGAj3%22%7D

Tester: Tiegan-

**Comment by patriciarussellCAS** [comment]
Hi @TammieV-BCG - can you share which user had this issue? It might be specific to their access and this will help us figure out the issue.

**Comment by zoeyli-46** [comment]
should we close this either this ticket or #2523 since these seem to be duplicated? @TammieV-BCG

**Comment by TammieV-BCG** [comment]
@zoeyli-46 yes we can. thanks for spotting that
