### ISSUE TITLE
UAT Bug- regulated operation fields that shouldn't show up

### ISSUE THREAD

**Issue by TammieV-BCG** [bcgov/cas-registration#2507]
#### Describe the Bug:
 field do not match wireframe reference 

#### Steps to reproduce the behaviour:

1. select Reporting Operation as purpose of registration
2. I can then select a Regulated Product, this does not match the wireframe for this process. Wireframe does not have Regulated Product Names option.

#### Screenshots:
![Image](https://github.com/user-attachments/assets/4db394b0-26ee-4657-9c9a-6d15d65b03a6)

#### Additional information:
Browser: MS Edge 

#### Additional Context
User story: As an External User, for a Reporting or Reporting-only operation, I will only fill out the necessary fields for this registration purpose type.

Link to UAT ticket: https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/mytasks?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fv1%2Fplan%2FbyyJUkJggkaPhsw6jAP-oWUAGWDg%2Ftask%2FVI7NGf7xEEO_59fFAV7CQWUAHtfF%22%7D -

**Comment by patriciarussellCAS** [comment]
Thanks @TammieV-BCG - this is a known bug and already has a ticket for it. #2337 
cc: @andrea-williams
