### ISSUE TITLE
UAT Bug?-Question in step 3 references different table from wireframe

### ISSUE THREAD

**Issue by TammieV-BCG** [bcgov/cas-registration#2508]
#### Describe the Bug:
in Opt In Application step 3: Does this operation produce a regulated product listed in Table 1 of Schedule A.1 of the GGERR?* 
Is it Table 1 or Table 2 to be stated? Application states Table 1 but Wireframe states Table 2.  

#### Steps to reproduce the behaviour:

1. Registration Step 1: Selected Opt-in application 
2. Registration Step 2: Completed Facility Information 
3. Registration Step 3: Identified that the question in the application “Does this operation produce a regulated product listed in Table 1 of Schedule A.1 of the GGERR?*” states Table 1, while in the Wireframe the question states Table 2.  

#### Screenshots:
![Image](https://github.com/user-attachments/assets/2a1831a1-a134-4667-8c69-7539aed1cb71)

#### Additional information:
Browser: MS Edge 

#### Additional Context
User Story: As an External User, given that I selected Opt-In as my registration purpose, then I am shown an opt-in application

Link to UAT ticket: https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/mytasks?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fv1%2Fplan%2FbyyJUkJggkaPhsw6jAP-oWUAGWDg%2Ftask%2FrTvokwYtpUSPFo_GN4Ibo2UAKykw%22%7D
-

**Comment by patriciarussellCAS** [comment]
@zoeyli-46 - might be a clarifying question for the BA

**Comment by zoeyli-46** [comment]
Hey @patriciarussellCAS it is table 2. Tiegan asked me to change it to table 2 on figma a while back, and its in this ticket already for wording updates :) https://github.com/orgs/bcgov/projects/123/views/16?filterQuery=wording&pane=issue&itemId=80445746&issue=bcgov%7Ccas-registration%7C2147

**Comment by patrickisaac** [comment]
Refinement Notes:
- Can be closed as it is being addressed in another ticket #2147
