### ISSUE TITLE
UAT Bug- (Ext. User) No edit button on Operation Information page

### ISSUE THREAD

**Issue by TammieV-BCG** [bcgov/cas-registration#2509]
#### Describe the Bug:
No edit button on Operation Information page 

#### Steps to reproduce the behaviour:

1. Navigate to operation information page 
2. Scroll down. On my screen I do not have an edit button next to the cancel button, only the cancel button.  

#### Screenshots:
![Image](https://github.com/user-attachments/assets/fa50d239-bf95-4acf-b439-e7655792c094)

#### Additional information:
Browser: chrome

#### Additional Context
user story: As an External User, given that I am on my Operation Information form, if my answer to “Does the operation have multiple operators?” value is yes, then I can see the fields to enter multiple operators

Link to UAT ticket: https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/mytasks?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fv1%2Fplan%2FbyyJUkJggkaPhsw6jAP-oWUAGWDg%2Ftask%2FL9OCCB85mUSqYpFuVPGl1WUAAPhf%22%7D

-

**Comment by zoeyli-46** [comment]
@patriciarussellCAS might be a user role access issue? It was Cam who had this issue.

**Comment by TammieV-BCG** [comment]
@patriciarussellCAS so you think this issue resolved? as I noticed you were there was an edit button today

**Comment by zoeyli-46** [comment]
Cam to retest this to see if it can be recreated, to close this ticket

**Comment by patrickisaac** [comment]
Refinement Notes:
- Could be role-based issue

**Comment by TammieV-BCG** [comment]
> Cam to retest this to see if it can be recreated, to close this ticket

@patriciarussellCAS Cam re-tested and he sees the edit button. should I close the ticket?

**Comment by patriciarussellCAS** [comment]
Excellent! Yes we can close this! Thanks @TammieV-BCG
