### ISSUE TITLE
UAT Bug-When selecting small aggregate as facility type, multiple fields remain

### ISSUE THREAD

**Issue by TammieV-BCG** [bcgov/cas-registration#2512]
#### Describe the Bug:
When selecting small aggregate as facility type, multiple fields remain 

#### Steps to reproduce the behaviour:

1. Navigate to add new facility 
2. Select small aggregate as facility type 
3. Multiple fields remain 

#### Screenshots:
![Image](https://github.com/user-attachments/assets/e3e7d549-0cf5-4b72-9e62-178dd9b3ef2a)

#### Additional information:
Browser: chrome

#### Additional Context
User Story: As an External User, given that I am adding a new facility, if the facility type is Small Aggregate, then there are only 2 fields that appear on the page: "Facility name" and "Facility Type"

UAT Ticket-https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/mytasks?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fv1%2Fplan%2FbyyJUkJggkaPhsw6jAP-oWUAGWDg%2Ftask%2Fvd3gL7Z2PEWYQmNFPlqsa2UAHXjk%22%7D

Tester: Cam -

**Comment by patriciarussellCAS** [comment]
This work is incomplete. Ticket for this is here: #2129
