### ISSUE TITLE
UAT Bug-Blank page when you login for the first time with IDIR

### ISSUE THREAD

**Issue by TammieV-BCG** [bcgov/cas-registration#2514]
#### Describe the Bug:
Blank page when you login for the first time with IDIR 

#### Steps to reproduce the behaviour:
1. Log in to test site with IDIR 
It leads to no where you have to go back to dashboard to see that your request has been sent 

#### Screenshots:
![Image](https://github.com/user-attachments/assets/12c81e3a-3b8e-47b2-a5d0-5b1ef91ab5d9)

#### Additional information:
Browser: Edge

#### Additional Context
not connected to a user stories or UAT ticket

-

**Comment by zoeyli-46** [comment]
already captured in #2167, close this ticket?

**Comment by Sepehr-Sobhani** [comment]
Duplicate: https://github.com/orgs/bcgov/projects/123/views/11?pane=issue&itemId=80445728&issue=bcgov%7Ccas-registration%7C2167
