### ISSUE TITLE
SSL Certificate Setup

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-registration#252]
Follow the steps in here:

https://apps.nrs.gov.bc.ca/int/confluence/display/DEVGUILD/Generating+a+CSR#GeneratingaCSR-oc-secret

**Comment by Dianadec** [comment]
@dleard as an update, I'm still waiting to hear about about a missing code we need to submit this. But I've escalated it so hopefully we'll get it by EOD so that they can submit this request. cc @hannavovk

**Comment by Dianadec** [comment]
@dleard @hannavovk  FYI I got the missing coding so they are moving it along now

**Comment by Dianadec** [comment]
@dleard they just sent over the SSL certificate to be installed (via email). cc @hannavovk @andrea-williams

**Comment by Dianadec** [comment]
On hold until January - middletier is trying to troubleshoot.

**Comment by hannavovk** [comment]
Middletier response on Dec 19 via email:
"The SSL certificate for “industryemissions.gov.bc.ca” has been cross verified again and there is no issue on the attachments forwarded. FYR, please find the below screenshot. ... [in email]
 The site https://industryemissions.gov.bc.ca/ has been configured with the wrong certificate. Please reach out to the below mentioned contacts regarding configuring certificates for OpenShift."
...
"the certificate is issued to logontest7.gov.bc.ca and but should be industryemissions.gov.bc.ca"

**Comment by Dianadec** [comment]
Update re: domain name. Changing it to industrialemissions.gov.bc.ca rather than industryemissions.gov.bc.ca. This change will be submitted as we also figure out the issue with the SSL cert the way it was setup by the middle tier team.

**Comment by Dianadec** [comment]
new domain name has been approved (industrialemissions.gov.bc.ca) and we can proceed with generating the .csr and submitting it to middletier services via jira. cc @dleard

**Comment by Dianadec** [comment]
We have received the ssl certs to be installed. @dleard @hannavovk

**Comment by Dianadec** [comment]
SSL Cert setup documentation has been recorded here: https://bcgov.sharepoint.com/:w:/r/teams/00608-ScrumTeam/Shared%20Documents/Scrum%20Team/OBPS/Domain%20Setup/SSL_Certificate_Documentation.docx?d=w3140fee140ef4eb2abf7615a53fb391e&csf=1&web=1&e=QQhH8C
