### ISSUE TITLE
Reg1 & Reg2\separate API endpoints into v1 and v2

### ISSUE THREAD

**Issue by patrickisaac** [bcgov/cas-registration#2522]
#### Dependencies
Blocking #2497 

#### Description:
Completely separate the v1 and v2 endpoints for Reg1 and Reg2. We need this because the user roles are different between the 2 apps, so the endpoint protections will need to be different.

#### Acceptance Criteria:
- [x] all API endpoints called in Reg1 are in a `v1` api folder
- [ ] all API endpoints called in Reg2 are in a `v2` api folder
- [x] where an API endpoint is called in both Reg1 and Reg2, the endpoint should be duplicated in both `v1` and `v2` folders
- [x] update RBAC protections for each endpoint and app appropriately

#### Development Checklist:

- [ ] [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by BCerki** [comment]
I don't think there's any PO testing for this one, do you @Sepehr-Sobhani ?
