### ISSUE TITLE
Reg\Transfers Tile for Transfers - External User

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-registration#2528]
#### Description:
External users have a transfer tile 

#### Acceptance Criteria:
Given that I am an industry user, 
When I am on my BCIERS dashboard, I have a transfers tile. [Figma wireframe](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=22844-976&t=FjKJaW7us84sFbTf-4)
Then when I click on the transfers tile or on the "report a ..." link, then it takes me to an [instruction page](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=23217-5751&t=FjKJaW7us84sFbTf-4) (instruction page handled in #2374 )

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

#### Definition of Ready (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

#### Definition of Done (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by patrickisaac** [comment]
Refinement Notes:
- Closing this one as this will be a part of #2374
