### ISSUE TITLE
Compile feedback from user testing sessions

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-registration#253]
#### Describe the task

We need to compile the feedback we received and implement them. This preparation is to also help Nan onboard back on Registration

#### Acceptance Criteria

- [x] Organize Figma file into respective frames
- [x] Create shareable Miro board of the feedback 
- [x] Organize feedback on the forms to share with business area (for #203)
- [x] Create action items for updates to make to the wireframes for Nan (+ List of fields that need to be part of a gloassary)

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by suhafa** [comment]
This ticket can be closed. @hannavovk and @nanyangpro, kindly see the Miro board titled 'User Engagement: Feedback Analysis' for the findings and recommendations following our user engagement sessions

**Comment by nanyangpro** [comment]
Astonishing work, @suhafa! Thanks for your time and efforts!

FYI @hannavovk - I created #485 in the Post-MVP Backlog as the next step.

**Comment by hannavovk** [comment]
Great work! thank you @suhafa
