### ISSUE TITLE
Reg\Register Operation - Only show New Entrant/Opt-in Application if selected

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-registration#2545]
Currently, the New entrant or opt-in application in step 3 shows up no matter what the registration purpose is. 

Task: only show New Entrant / Opt-in Application in Step 3 IF it was selected in "registration purpose" otherwise, step 3 is just "operation representative"

**Comment by zoeyli-46** [comment]
@patriciarussellCAS @patrickisaac for your visibility

**Comment by patrickisaac** [comment]
Thanks @zoeyli-46!

@patriciarussellCAS - I've moved this towards the top of the `Backlog` section so it does not get lost. Feel free to move it up or down whenever! 😄 !

**Comment by patriciarussellCAS** [comment]
I think we should prioritize this as it will be part of control testing for FRCR.

**Comment by patrickisaac** [comment]
@patriciarussellCAS - I'll move this to `Next Sprint Backlog` and above the DevOps stuff that we discussed during our Prod Checklist meeting.

**Comment by patrickisaac** [comment]
Refinement Notes:
- Closing ticket as per discussion
