### ISSUE TITLE
Confusing error on extraprovincial operator toggle

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#2565]
#### Describe the Bug:

![Image](https://github.com/user-attachments/assets/8d78b84c-ac16-4c25-b691-43925f4340e0)

or that error we need to replace enum:... with const:... in `
mo_is_extraprovincial_company

#### Probability:

(How likely the bug is to happen, scored from 1-5. For example, probability of 5 is something like "it happens to all users every time they log in." whereas probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

#### Impact:

(How bad the bug is when it does happen, scored from 1-5. For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected." whereas effect of 1 is "It makes some styling look a little bit weird.")

<img src="https://www.getzephyr.com/sites/default/files/riksk%20matrix.jpg" alt="Bug Matrix" width="250" height="250"/>

#### Steps to reproduce the behaviour:

1. Step #1
2. Step #2
3. Step #3

#### Additional information:

Browser: [e.g. chrome, safari]
Version: [e.g. 22]

#### Additional Context

-

**Comment by patriciarussellCAS** [comment]
Confirmed that this weird error message is now gone. Thanks!
