### ISSUE TITLE
Tooltips alternatives exploration

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-registration#258]
#### Describe the task

Users want to be able to further understand what is being asked of them when submitting forms and would like to be able to have something like tool tips for additional information.

We need to come to a consensus as a team about how we want to address this user need for getting more information, in a way that meets accessibility criteria, is minimal in terms of UI, doesn't clutter the page with extra elements and intuitive for the user.

We've explored creating a '[Glossary](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2071%3A4318&mode=design&t=xupjFDi0z51sBous-1)' page. What other ways can we address this need on our interface (besides the guidance document)?

Some proposed solutions [can be found here](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2119%3A4506&mode=design&t=xupjFDi0z51sBous-1)

#### Acceptance Criteria

- [ ] Explore more options for UI
- [ ] Review with Scrum Team about risks/pros and cons of each solution
- [ ] Test this solution(s) with internal/external users
- [ ] Decide which solution to go with 

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by suhafa** [comment]
@hannavovk ticket created!

**Comment by suhafa** [comment]
Might have to explore the outcomes of #259 and vice versa for this

**Comment by nanyangpro** [comment]
Closing. Please see #836 instead.
