### ISSUE TITLE
Support the guidance document creation

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-registration#259]
#### Describe the task

Jairo completed the first draft of the [guidance](https://bcgov.sharepoint.com/:w:/t/00605/EdYhJWp0-bpAquKOat84XW8BcNP2Dfs54J939BqTMFObnQ) document. This ticket is to figure out the best way to present Jairo's document to users and help him finalize it with user feedback.

**Status Updates:**
According to [Hanna's Workplan](https://bcgov.sharepoint.com/:w:/r/teams/06817/_layouts/15/Doc.aspx?sourcedoc=%7BE38508C3-7B9E-418D-9D44-F05F7E7AE95F%7D&file=Workplan%20for%20App%20Release%20Prep.docx&action=default&mobileredirect=true&ovuser=6fdb5200-3d0d-4a8a-b036-d3685e359adc%2CNan.1.Yang%40gov.bc.ca&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyOC8yMzExMDIyNDcwNSIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D)
- Due: Jan 9 for review
- Draft: Harnav/Nan will carry it forward in Jairo's absence
_Harnav will be back on Jan 2nd, a meeting to follow up with her is scheduled on that day_
- Review/Revise: Hanna/Jess
- Approve: Chris/Maral/Adria

#### Acceptance Criteria

- [x] Connect with Hanna on the current status of the ticket (repurpose/refine the ticket description accordingly)
- [x] Review relevant feedback from the previous user engagement sessions
- [x] Review Jairo's first draft of the [guidance](https://bcgov.sharepoint.com/:w:/t/00605/EdYhJWp0-bpAquKOat84XW8BcNP2Dfs54J939BqTMFObnQ) document
- [x] Connect with the Engagement team (Jessica/Avril/Alana/Scott)
- [x] Support Jairo/Harnav with edits/comments/suggestions

#### Additional context

Suggestions made based on user feedback so far:
>- preferably the content is on a website that is editable and linkable via link anchors. We can support on making this user-friendly and navigable. The catch is it will need to be maintained and updated as policy matures, so we will need to have a check-in with business area to make sure it is up to date on a certain frequency
>- we will need a glossary of terms, and we can make this reference-able for each field that needs more context
>- users should be able to access and download all required templates from this document
>- it would be good to have specific directions for users to fill out each of the forms
>- a lot of users are carrying over knowledge about CIIP/systems of other provinces. It would be good to let them know how some requirements/terminologies are different from CIIP and other provinces.
>- need to clarify roles and who is required to do what so that they can plan accordingly

**Comment by suhafa** [comment]
@hannavovk ticket created here!

**Comment by patriciarussellCAS** [comment]
Just wanted to add that this work is also being supported by the ICPG team, via Scott Cutler and Alana Clement. Alana comes from the engagement team previous and has a lot of experience with drafting language for the web that is more accessible. :)

**Comment by nanyangpro** [comment]
**Next steps:**
- Connect with Jessica/Avril on their program website
- Propose the best solution for presenting Jairo's document
- Help Jairo finalizing the content

**Comment by nanyangpro** [comment]
We met with the Engagement team and our SMEs on Mon, Dec 18
 
**Agreements:**
- Once finalized, the  ​docx icon web app guidance will be hosted as a PDF on the OBPS program website.
- The Engagement team will send out a letter to inform the industry.
- The web content updates will be post January.

**Next steps:**
- DST review and revise Jairo’s draft document
- DST confirm readiness of the draft document with Jairo/Harnav
- DST share the draft document in the  ​Folder icon Guidance and Comms folder in the Engagement channel, and inform the Engagement team for approval
- Engagement team review/revise/approve the draft document
- Engagement team or DST export the finalized document to PDF
- Engagement team host and publish the PDF
- Engagement team send out the letter to industry

@hannavovk  informs Nan if there’re changes of the plan post the work planning meeting this afternoon.

**Comment by Dianadec** [comment]
Suha suggests looking at the usability testing feedback to support guidance doc design/creation. cc @nanyangpro

**Comment by Dianadec** [comment]
@nanyangpro This is the latest guidance document link from Harnav: https://bcgov.sharepoint.com/:w:/r/teams/06817/_layouts/15/Doc.aspx?sourcedoc=%7B8CAD9D58-F261-4304-BC88-49735E96FE87%7D&file=Applying%20for%20a%20BC%20OBPS%20Regulated%20Operation%20ID%20-%20Guidance%20Document.docx&nav=eyJjIjoyMDU4OTU0ODg3fQ&action=default&mobileredirect=true&isSPOFile=1&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzExMzAyNjIwMiIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D

**Comment by Dianadec** [comment]
I'll cross-ref the guidance doc with the webinar slides. cc @nanyangpro @hannavovk

**Comment by nanyangpro** [comment]
Hi @hannavovk (cc: @Dianadec), since the supporting work from our end has been wrapped up given the [Guidance](https://bcgov.sharepoint.com/:w:/r/teams/06817/_layouts/15/Doc.aspx?sourcedoc=%7B8CAD9D58-F261-4304-BC88-49735E96FE87%7D&file=Applying%20for%20a%20BC%20OBPS%20Regulated%20Operation%20ID%20-%20Guidance%20Document.docx&nav=eyJjIjoxODcyOTI4NDgwfQ&action=default&mobileredirect=true) document is with the Engagement team for the final review and publish, we can close this ticket unless you advise otherwise. Thanks!

**Comment by hannavovk** [comment]
Thanks so much for all your collaborative work and patience on this! @nanyangpro
