### ISSUE TITLE
Operator (organization) admin adds/edits an operation (facility) for their operator

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#26]
#### Description:

As Gertrude, I want to be able to add or update a facility that belongs to my operator

Assumption: Gertrude is logged in with their BCeID account that's linked to their operator's Business BCeID
The prime admin's access request has already been approved by IRC
Includes user filling out forms and submitting request to register operation.

See https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/Registration-app?type=design&node-id=4-2&mode=design&t=lp8DwUm6T8XDYKso-0 for wireframes

#### Acceptance Criteria:

Given I am logged in to the Registration app with my Business BCeID account and I have been granted "admin" role for my operator
When I navigate to the Operation (facility) Details page
Then I can view the existing operations associated with my operator
And I can edit information about those operations
And I can add a new operation associated with my operator

#### Development Checklist:

- [x] API endpoint/(s) to POST/PUT facility data for an operator
- [x] Implement front-end according to wireframes
- [x] External user sees confirmation page when registration request is submitted (indicates that the request has been submitted successfully, not that it has been approved/denied yet)
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [x] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [x] Configuration changes are documented, documentation and designs are updated
- [x] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [x] Ticket is ready to be merged to main branch
- [x] Can be demoed in Sprint Review
- [x] Bugs or future work cards are identified and created
- [x] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by andrea-williams** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-registration/26?planning-poker) with Zenhub @andrea-williams @BCerki @dleard @JoshLarouche @Sepehr-Sobhani

**Comment by hannavovk** [comment]
Includes user filling out forms and submitting request to register operation.

**Comment by BCerki** [comment]
@hannavovk, here's a video of what this ticket includes: https://www.loom.com/share/7495eecd5329421c952384a0e4e0c528

It does not include:
- approval (you'll see status is pending for everything in the table)
- anything to do with auth (right now the table shows every facility in the app regardless of who the user is)

**Comment by hannavovk** [comment]
@BCerki I'm not sure what you mean by "does not include registering an operation" - clicking "submit" is equal to submitting a request to register the operation under OBPS. 
You may be thinking of the scenario of adding an operatOR? In that case we would need to first approver the creation of an operator and the prime admin person (this is one step), and then they would add an operation to that operator and submit it for registration.

**Comment by hannavovk** [comment]
As discussed with @BCerki, we will look at this together later in the week for approval.  The form has changed a lot since the video as a result of #15. We won't be able to submit the form (which is one of the AC) until the devops people add some mock data.

**Comment by hannavovk** [comment]
Amazing work @BCerki! Thank you!

**Comment by patriciarussellCAS** [comment]
@andrea-williams is this ticket still relevant or can we close? looks like its' from Reg 1.

**Comment by andrea-williams** [comment]
it's ancient - closing it
