### ISSUE TITLE
Have a landing page discussion with the business area

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-registration#260]
#### Describe the task

We need to finalize on the design for Landing page in collaboration with the business area.

**Status Updates:**
- The [landing page design](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2688-6375&mode=design&t=aeoJEopSsPfaTp3k-4) has been updated to IRC's version in Figma
- Waiting on final approval for implementation

#### Acceptance Criteria

- [x] Create proposed designs for landing page
- [x] Prepare Miro Board for discussion
- [x] Review with business area
- [x] Implement business area text and design suggestions
- [x] finalize design

#### Additional context

- Blocking #163

**Comment by suhafa** [comment]
@hannavovk created ticket here

**Comment by suhafa** [comment]
Latest update from Business Area (Jairo):

Hi Suha, Sharing something posted by Tiegan in the Landing Page Meeting chat "Hi everyone! I spoke with Avril yesterday about the timelines they are expecting to publish general OBPS pages, as well as the approval process they are going to use for them. She confirmed that they are aiming to have these posted for the new year (or hopefully sooner), but that they are having a meeting with Maral tomorrow to confirm direction. She will update me after that meeting " 

"They are going through the approval process for web page changes that Susan (web coordinator lead) has set out, but we both agreed that the registration application doesn't really fall into this web approval process. Unless your team has been directed to get GCPE approval on these pages, we figured it would probably be fine just having sign off by Adria. "

"Happy to have a call to discuss this more next week! As I mentioned yesterday, I am leaving the country very early tomorrow and returning late Monday night - but will be back on Tuesday and around for the remainder of next week to get all the content sorted and the approval process lined out"

**Comment by suhafa** [comment]
@nanyangpro and I will be collaborating on this after receiving business area feedback

**Comment by suhafa** [comment]
Business area has completed the text in Miro for the Landing Page (see 'OBPS MVP Landing page discussion' Miro board) Now we need to implement the suggestions and reach out to them in case of further tweaks/context we may need.

**Comment by nanyangpro** [comment]
Hi @hannavovk - This ticket is ready for you to review and can be closed with

- The [approved IRC landing page version](https://bcgov.sharepoint.com/:w:/r/teams/06817/Shared%20Documents/Engagement/External/Guidance%20and%20Comms/Registration%20App%20materials/Landing%20Page%20-%20BCIERS%20_Approved.docx?d=w5bba938378864076b611d86f6ecbf7bc&csf=1&web=1&e=ueUonK) updated in [Figma](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2688-6375&mode=design&t=kp8xB0bBe5Qlx2Xc-4)

Your ongoing support simplified this work a lot for me, much appreciated! :)

**Comment by hannavovk** [comment]
Looking great! Thanks @nanyangpro! And thanks for your patience with this :)
