### ISSUE TITLE
Cannot access Django Ninja API Endpoint documentation on backend in dev

### ISSUE THREAD

**Issue by joshgamache** [bcgov/cas-registration#2607]
## Describe the Bug:
Cannot access the Django Ninja API Endpoint documentation page on the backend (locally, dev servers). The following error is displayed:
![Image](https://github.com/user-attachments/assets/762506c9-2230-4729-9901-6564292b23fb)

### Steps to reproduce the behaviour:

1. Spin up a local copy of the backend. 
2. Navigate to `localhost:8000/api/docs`

Probability: **5**/5
Impact: **2**/5

## Additional context

Does *not* seem to effect the functionality of the backend or Django-Ninja, just the output and display of the API Endpoint documentation. This page is only accessible in local/dev environments, so will only impact developers.

**Comment by Sepehr-Sobhani** [comment]
Addressed in: https://github.com/bcgov/cas-registration/pull/2639
