### ISSUE TITLE
Have a dashboard page discussion with the business area and service designers

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-registration#261]
#### Describe the task

We need to finalize on the design for the dashboard e in collaboration with the business area and service designers

#### Acceptance Criteria

- [ ] Create proposed designs for landing page
- [ ] Conduct workshop for reviewing and brainstorming proposed solutions
- [ ] Compile information required from business area for implementation
- [ ] Finalize design

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by suhafa** [comment]
@hannavovk ticket created, this will be a task we carry out much later, after the Landing page work (#260)

**Comment by nanyangpro** [comment]
Closing.
We have both internal and external dashboard design reviewed and finalized by the business area **for the MVP**. Further refinements or enhancements are out of the scope and will be addressed post MVP. We'll revisit the dashboard design and create associated ticket(s) when needed during Reporting/Registration collaboration.
