### ISSUE TITLE
Transmit exemption data for an operation to FIN

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#263]
#### Describe the task

We need to create a data pipeline so that operations that have been approved for carbon tax exemption have their data automatically submitted to Ministry of Finance so that they can issue an exemption certificate.

*At this time, we don't know what data about an operation FIN needs in order to issue an exemption certificate, nor how they want us to send them the data. Business area/PO to reach out to FIN.*

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by hannavovk** [comment]
I'm not sure that we will need this actually. So far FIN doesn't seem to be indicating what, if anything, they would like us to provide. It could end up just a simple data extract or even spreadsheet. TBD.

**Comment by andrea-williams** [comment]
This will probably be replaced by the work captured in #273
