### ISSUE TITLE
Add role protection to app routes

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#265]

**Comment by shon-button** [comment]
#### Describe the task

We need to protect app routes by 

Protected routes are routes that require authentication before allowing access. In a Next.js application using NextAuth.js, you can implement protected routes by using middleware. The middleware can check whether a user is authenticated before allowing access to a particular route. If a user is not authenticated, they can be redirected to a login page or shown an access denied message.

#### Additional context

**Comment by dleard** [comment]
@shon-button I created a separate ticket for the db roles in #281

**Comment by dleard** [comment]
I think industry_user has one db role & then their fine-grained permissions specific to an operator is defined by the user_operator table

**Comment by shon-button** [comment]
@dleard can we assume if auth user is in `user_operator` table then the auth user has permissions to the route for "Users: For managing user access for your operators"

**Comment by dleard** [comment]
If the user has the admin role in the user_operator table then they will have permissions for that route. The reporter role woudl not
