### ISSUE TITLE
Set up MailHog (or similar) for dev and test envs

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#266]
#### Describe the task

Our dev and test environments should be integrated with CHES so that they can send emails, but we should use a tool like MailHog to ensure that the email notifications automatically generated in those environments aren't actually sent to the intended recipients.

#### Acceptance Criteria

- [ ] all auto-generated emails from DEV environment are captured (not sent to recipient)
- [ ] all auto-generated emails from TEST environment are captured (not sent to recipient)
- [ ] all auto-generated emails from PROD environment are sent to recipient

#### Additional context

- MailHog has been used in other CAS applications; can explore other tool options if desired
- Or here

**Comment by dleard** [comment]
This is the chart that we're using in CIIP to deploy & run mailhog in our dev/test environments
https://artifacthub.io/packages/helm/codecentric/mailhog
