### ISSUE TITLE
Clean up <Review> component in Operations view

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#268]
###Description of the Tech Debt###

A `<Review />` component has been added to `forms/Operation` for internal users to approve/reject an Operation's request for carbon tax exemption. It is functional but there is outstanding front-end work to polish up the styling and fix a small bug. 

To see the Review component, click "View Details" on an Operation whose status is 'Pending'. 

- [x] make whitespace in component more aesthetic & functional
- [x] I think according to the wireframes the buttons should be moved over to the right side of the page (?)
- [x] check with designers: should users be prompted to confirm they want to Approve/Reject before the change happens? (i.e., "Are you sure?"). At the moment there's no route to undo a status change once it's been made
- [x] the `Alert` component that should appear when an Operation is approved or rejected used to show up and stay there until the user dismissed it, but since the version upgrade of Next.js, it only flashes very briefly and then disappears. Would like to get that either staying until user manually dismisses it, or timeout after ~5 seconds

**Comment by marcellmueller** [comment]
Putting this back in the sprint backlog for now as I am blocked waiting for a design sync.
