### ISSUE TITLE
IO user requests access to an operator (organization)

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#27]
#### Description:

As Salamander (Industry report submitter) or Regular Gertrude (aspiring admin), I want to request access for myself to view my operator's data in the Registration app

Assumption: Salamander/Regular Gertrude has already logged in to their individual BCeID account, which is associated to their operator's Business BCeID

See https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/Registration-app?type=design&node-id=4-2&mode=design&t=lp8DwUm6T8XDYKso-0 for wireframes

#### Acceptance Criteria:

Given I have logged into the Registration app with my Business BCeID account
When my operator's registration request has already been approved, but I haven't been assigned a role within my operator
Then I can submit a request to access my operator

#### Development Checklist:

- [x] API endpoint to POST a request to be added to the operator
- [x] when the request is received, create a new record in the database to indicate that the new user has requested access to the operator, and that the Status is Pending
- [x] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by andrea-williams** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-registration/27?planning-poker) with Zenhub @andrea-williams @BCerki @dleard @JoshLarouche @Sepehr-Sobhani

**Comment by NicoleGovvy** [comment]
@andrea-williams Is it possible for this ticket to be more general - not just salamander but granting of Gertrude permissions as well?

**Comment by hannavovk** [comment]
Looking great! Thanks @dleard !
