### ISSUE TITLE
Bug: Option to Approve or Reject an Operation doesn't appear when the Operation has been created manually

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#274]
Describe the Bug:

The `<Review />` component (the buttons to Approve or Reject an operation) only appear when an operation's status is Pending. The dummy operation data contains an operation with a status of "Pending", and operations whose statuses can be updated from "Not Registered" to "Pending" by clicking the "Submit" button under "Start Registration". When the status of these operations is "Pending", the Approve/Reject buttons are rendered.

If an IO creates a new Operation manually (by filling out all the fields in the form), the Approve/Reject buttons aren't displayed. My theory is that there's something wrong with how the `status` field is being set in the POST endpoint for operations. (We should be used the fixed strings in `class.Statuses`, not just a `'pending'` string.)

Probability (how likely the bug is to happen, scored from 1-5): 4
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 4
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
1. Use the "Add Operation" button to create a new operation. Once you've hit the "Submit" button in the form, the Operation's status should be set to 'Pending' in the UI.
2. Click the "View Details" button next to your new operation. A new page is rendered with all the available info about the operation, but the Approve/Reject buttons aren't there.

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by marcellmueller** [comment]
Closing as this was fixed in #291
