### ISSUE TITLE
Operator (organization) admin approves/denies user access request

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#28]
#### Description:

As an external admin, I want to be able to review requests received to access my operator's information within OBPS, and either approve or deny the requests received from users

Assumption: The External admin is logged in to their BCeID account, and has admin rights for their operator (123 Co.)

See https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/Registration-app?type=design&node-id=4-2&mode=design&t=lp8DwUm6T8XDYKso-0 for wireframes

#### Acceptance Criteria:

Given I am an external admin and I have logged into my Business BCeID account and I already have the admin role assigned to my account
When I navigate to the User Access Management page
Then I can see a list of the users who have requested access, and I can approve or deny those requests

Given I am Salamander (Industry report submitter) and I have logged into the Registration app with my Business BCeID account
When my request to access my operator in the Registration app has been approved
Then I can view information specific to my operator in the Registration app

#### Development Checklist:

- [x] API endpoint to FETCH all received requests for the operator
- [x] API endpoint to update user status
   - [x] data sent to this endpoint should update the requesting user's record in the database, including Status (approved/denied), datetime updated, and updated by <Prime Gertrude's user ID>
- [x] create frontend UI based on wireframes
- [x] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by andrea-williams** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-registration/28?planning-poker) with Zenhub @andrea-williams @dleard @Sepehr-Sobhani @BCerki @JoshLarouche

**Comment by hannavovk** [comment]
Would it make sense to split this into two sperate tickets - one for a user to request access and another for prime admin to review and approve/deny their access (and assign permission level)?

**Comment by joshgamache** [comment]
PR: https://github.com/bcgov/cas-registration/pull/394

**Comment by hannavovk** [comment]
We're getting an error on the user management page when loading both on OpenShift and local (cc: @andrea-williams, @dleard, @joshgamache)
<img width="1354" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1NqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b57a70335e7aa3933bc3cc159e32ce499033eb2/image.png" alt="image.png" />
