### ISSUE TITLE
IO can provide operator data when operation is owned by multiple operators

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#280]
#### Description:

In the operation admin form, the user is asked if the operation has multiple operators. If they answer yes, they are presented with a form to enter data about that operator. This operator data should be treated differently from the data in the operator table. It is purely metadata, whereas the operator table is for registered operators that are the primary operator for their dependent operations. The data entered in this form should not mutate the data in the operator table, it should live in its own place.

wireframe of multiple operator form:
https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=1312-1134&mode=design&t=Vh3QQdLInvXMO7Gu-0

#### Acceptance Criteria:

Given my operation has multiple operators
When I am presented with the form
Then I can enter the data about the extra operator

Given I need to enter multiple operator data
When I enter that data
Then the data is not saved to the operator table
And the data is saved to the multiple_operator table as metadata

#### Development Checklist:

- [x] a new model `multiple_operator` is created
- [x] the `multiple_operator` table contains all fields in the wireframe (minus the radio button, which is just a formatting thing)
- [x] when data is entered in the multiple operator section of the operation admin form, it is saved / updated in the `multiple_operator` table
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Moose-Sprint-Board-60d216175a2689000ec774d0/issues/bcgov/cas-registration/280?planning-poker) with Zenhub @dleard @joshgamache @JoshLarouche @mikevespi @Sepehr-Sobhani @andrea-williams @marcellmueller

**Comment by andrea-williams** [comment]
If document upload feature hasn't been implemented at the time this story is worked on, ignore doc upload

**Comment by dleard** [comment]
We can develop this form minus the file upload functionality and tackle that when a decision is made on how to handle #138

**Comment by Dianadec** [comment]
@marcellmueller  wants to take this on

**Comment by andrea-williams** [comment]
@dleard  

1.  I notice the multi-operator form has a field to capture percentage of ownership of operation - I'm assuming that value should be stored in the `multiple_operator` table (?). 
2. seems like there's a risk of data duplication btwn the `operator` and `multiple_operator` tables, and within the `multiple_operator` table itself - are we ok with that? 
       - Example scenario: Operator A and Operator B co-own 2 operations, and each 100% owns some of their own operations. Then we'll have records for both Operators in the `operator` table, but we'll also have 4 records total in the `multiple_operator` table (repeating the same info about names, CRA & BC reg numbers, addresses, etc.) That sounds ugly (but maybe this isn't a very realistic scenario?) 
       - the other option I see is making the `multiple_operator` table only have fields for (operation_id_FK, operator_id_FK, percentage_ownership, proof_of_authority_doc_url).
