### ISSUE TITLE
Add a roles table to the database

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#281]
We will need to have a table that defines the different app roles that can be assigned to a user. The user table should also have a role column that is a foreign key to the role table.

The roles should be:
cas_admin
cas_analyst
cas_pending
industry_user

AC:
- [x] a new table is created in the database (app_role)
- [x] the new table has a column (role) with a row for each role defined above
- [x] the user table has a foreign key to the app_role table

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Moose-Sprint-Board-60d216175a2689000ec774d0/issues/bcgov/cas-registration/281?planning-poker) with Zenhub @andrea-williams @dleard @joshgamache @JoshLarouche @marcellmueller @mikevespi @Sepehr-Sobhani

**Comment by dleard** [comment]
@Sepehr-Sobhani role_name is an alternative

**Comment by Sepehr-Sobhani** [comment]
@dleard or permission!!
