### ISSUE TITLE
RJSF custom widget testing

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#282]
We will need to catch up on unit tests for all the custom RJSF widgets we have created.

- [ ] ComboBox
- [ ] EmailWidget
- [ ] FileWidget
- [ ] RadioWidget
- [ ] SelectWidget
- [ ] TextWidget
- [ ] URLWidget

**Comment by BCerki** [comment]
@marcellmueller , is this a duplicate of the one you're already working on?

**Comment by marcellmueller** [comment]
Yes it looks like it is, closing!
