### ISSUE TITLE
User should be created on login if they do not already exist in the database

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#283]
When a user logs in with their IDIR or BCeID, their guid should be matched with a user in our database User table. If no user exists in our database that matches that guid, then the user should be prompted with a form to add / confirm their info & on submit, that form should create a user in our database.

Wireframe link added in the comments.

AC:
- In client/app/api/auth/route.ts we should try to match the user guid returned by keycloak to a row in our user table
- If the user exists, set their role in the session from their user data
- If the user does not exist, they should be redirected to a user registration form
- The form should have the following fields: First Name, Last Name, position, email (immutable, prepopulated, returned by keycloak), phone number
- On submitting the form, a new user should be created in the database using that form data.
- 

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [x] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Moose-Sprint-Board-60d216175a2689000ec774d0/issues/bcgov/cas-registration/283?planning-poker) with Zenhub @andrea-williams @dleard @joshgamache @JoshLarouche @marcellmueller @mikevespi @Sepehr-Sobhani

**Comment by andrea-williams** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Moose-Sprint-Board-60d216175a2689000ec774d0/issues/bcgov/cas-registration/283?planning-poker) with Zenhub @shon-button

**Comment by andrea-williams** [comment]
I think this will be blocked until we decide on a solution for how the User table can be reworked (e.g., making some fields optional, such as mailing address, etc.)

**Comment by nanyangpro** [comment]
@dylan's example (from CIIP):
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUlEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b577f477d91d95a6ee34cb2fa83f9bb711a447b7/image.png)

**Comment by suhafa** [comment]
Wireframe: https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2895%3A390&mode=design&t=maBXISILutHXyUKb-1 @shon-button 

@dleard @hannavovk are we keeping the Occupation field? Anything else we want to remove?

**Comment by hannavovk** [comment]
We should keep it, but I would suggest we change it from "Occupation", which is really vague, to something like "Job Title", which is more reflective of what we are looking for. cc @suhafa @dleard @shon-button
