### ISSUE TITLE
Modify DB handling of addresses

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#289]
#### Describe the task

With our current DB structure there's some duplication of address fields, and addresses are stored on the `User` table when they're not necessary

#### Acceptance Criteria

- [x] remove all address-related fields from `User` model
- [x] create a new `Address` model with street address, municipality, province, postal code, ~~secondary address [optional]~~
- [x] remove all address-related fields from `Contact`, `Operator`, and `Operation` tables; replace them with 2 columns named `mailing_address_id` and `physical_address_id` with FK references to the Address table
- [x] JSON fixtures in `bc_obps/registration/fixtures` will need to be updated in a number of places with this new structure
- [x] refactor all endpoints and ninja schemas that deal with addresses

#### Dependencies
- Blocking #361

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by andrea-williams** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Moose-Sprint-Board-60d216175a2689000ec774d0/issues/bcgov/cas-registration/289?planning-poker) with Zenhub @andrea-williams @dleard @joshgamache @JoshLarouche @marcellmueller @Sepehr-Sobhani @shon-button

**Comment by BCerki** [comment]
This is going to have a lot of conflicts with #387 and #326
