### ISSUE TITLE
Task: Import Operator & Operation data from CIIP

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#29]
#### Describe the task

We want to pre-populate the Registration app's database with accurate Organization and Operation data, so that where possible, reporters won't have to re-enter data they've already entered in other related apps (such as CIIP). 

Because we won't have the data warehouse set up in time for Registration MVP, a workaround is to take a one-time data dump of existing operators & operations from CIIP and migrate it into our new database. 

What to import (pending BA approval):
- Pull SFO & LFO operator / operation data from SWRS (and CIIP if  any necessary data is not available in SWRS ie: business_registry_number)
- Do not pull IFa, IFb, Lc facilities
- Do not import the naics code, we will have them select that in the registration app
- Only pull operators and operations that submitted a swrs report for 2022

#### Acceptance Criteria

- [ ] SQL functions to retrieve the necessary information from SWRS/CIIP
- [ ] K8s job to perform the import

#### Additional context

- ~Should be able to re-use a decent amount of the script that was created during the hackathon (which pulled from SWRS database, so some modifications will be necessary). Scripts have been uploaded here: https://github.com/bcgov/cas-registration/tree/task/import-prod-data/29/bc_obps/data_import_scripts **NOTE: due to security flags from `bandit`, the `#nosec` op has been used regularly in these scripts. Use with extreme caution.**~
- Suggest instead writing this in SQL and using a foreign data wrapper
- 
OLD AC:
- [ ] script to import data from CIIP database into developers' local databases for local development purposes
- [ ] script to import data from CIIP database into database in registration-dev Openshift namespace

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-registration/29?planning-poker) with Zenhub @andrea-williams @BCerki @dleard @JoshLarouche @Sepehr-Sobhani

**Comment by hannavovk** [comment]
Note regarding scope of data to be imported: for Oil & Gas LFO's (linear facility operations), it's just the LFO-level 'facility' that should be imported, as that is the "Operation". The other 'facilities' are not, i.e. Operators will not be registering them individually (they will be dealt with in future work).

**Comment by Dianadec** [comment]
@andrea-williams to add link to script from hackathon

**Comment by dleard** [comment]
I think we are going to do this in SQL with foreign data wrappers rather than re-using the hackathon script as the query is more complicated than what was done in the hackathon.

**Comment by dleard** [comment]
@hannavovk I've updated this card after our conversation this morning & added the attn: Business Area tag

**Comment by hannavovk** [comment]
Confirmed that importing only 2022 reporters makes sense.

**Comment by dleard** [comment]
@hannavovk Noting here that on import, all operators should start in the 'draft' status
