### ISSUE TITLE
Re-design Prime Admin Request form

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#292]
#### Describe the task

During a dev discussion it was discovered that there's a logic flaw in the wireframe for an external user requesting prime admin access. Related to that, the way that we're currently saving user contact info associated with an Operator is flawed.

#### Acceptance Criteria

- [ ] move the checkbox asking whether the user requesting prime admin is the Senior Officer to be the first field in the form
- [ ] if the user requesting prime admin IS the Senior Officer, we should be able to pre-populate some of the Senior Officer contact fields with fields we have about the user (from the `user` table, such as name and email)
- [ ] else if the user requesting prime admin IS NOT the Senior Officer, the user should be prompted to input contact information only about the Senior Officer, not about themselves. (We may also display a list of existing contacts associated with the Operator, but that will be a subsequent ticket)
- [ ] store contact information about the operator's Senior Officer in the `contact` table, not the user table

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by suhafa** [comment]
@hannavovk Andrea, Dylan and I would like to touch base with you regarding some decision making before we commit to a workflow design!

**Comment by Sepehr-Sobhani** [comment]
Captured in ticket: #299
