### ISSUE TITLE
Create a 'Contacts' page design

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-registration#297]
#### Describe the task

We need a 'Contacts' page in the UI for the external user. This can help users to add contacts for Senior Officer, Operation Representative etc. in the forms for adding operations from a drop down instead of manually entering it in. Manual entry would cause duplication of the same contact. The user should be able to go to a central location to update contact information. This page could live under 'My Operator'.

Senior officer will probably be referenced in multiple operations for certain sectors, not much so for Operations Representative. 

Before starting this work, we need confirmation that this is a required piece or not, from either Andrea or Dylan.

> a Contact might not be a user. e.g., the CEO of a company would be a Contact (because they're the Senior Officer), but we wouldn't expect them to actually be signing in to the app and using it

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by Dianadec** [comment]
Post-MVP

**Comment by nanyangpro** [comment]
Closing. Please see #834 instead.
