### ISSUE TITLE
Amendments to feature: Request access to Operator as Prime Admin

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-registration#299]
#### Describe the task

Our code needs updating to reflect recent changes. Operators must now be approved before users can update their information.
**Workflow wireframes**: https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2401-60&mode=design&t=SmZ4kT0BDO8KtYse-4

#### Acceptance Criteria

- [x] Update Designs to reflect this new flow (need to update UserOperator, Confirm and Received Pages)
- [x] Update `UserOperator` form to only show User information section
- [x] Create separate API endpoints to update user information and create a new operator (for `AddOperator` flow)
- [x] Add/update endpoint tests if needed
- [x] Add multistep form to `AddOperator` flow (PR: https://github.com/bcgov/cas-registration/pull/302)

**Captured from ticket 292**:
- [x] move the checkbox asking whether the user requesting prime admin is the Senior Officer to be the first field in the form
- [x] if the user requesting prime admin IS the Senior Officer, we should be able to pre-populate some of the Senior Officer contact fields with fields we have about the user (from the `user` table, such as name and email)
- [x] else if the user requesting prime admin IS NOT the Senior Officer, the user should be prompted to input contact information only about the Senior Officer, not about themselves. (We may also display a list of existing contacts associated with the Operator, but that will be a subsequent ticket)
- [x] store contact information about the operator's Senior Officer in the `contact` table, not the user table

**Comment by Dianadec** [comment]
@shon-button I see that you pulled this in but it is not assigned to you - can I assign your name ?
