### ISSUE TITLE
Docs: RJSF form setup and best practices

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#312]
###Description of the Tech Debt###

We need some documentation on best practices when creating forms and how to use some of our form components (ie `MultiStepFormBase`), some of our custom widgets and how we are inserting types of headers into the forms. This will help ensure consistency between forms and help onboard developers to our RJSF system which can be very challenging to use.

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |     low  |  1    |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |    medium   |     2  |
| System Fault Risk - Risk of system errors or application downtime                                                             |  low     |     1  |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |      medium |   2    |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |  medium     |   2    |
| TOTAL SCORE:                                                                                                                  |       |    8   |

**Comment by BCerki** [comment]
@marcellmueller , is this a duplicate of https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=48610057?

**Comment by marcellmueller** [comment]
Yes looks like it. Thanks for going through these old issues 🙇
