### ISSUE TITLE
RJSF URL and Email field validation

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#316]
#### Describe the task

We need to validate URL and email fields and trigger an error in RJSF if they are not valid. Looks like we can just set `format: 'url` or `format: 'email'` in the schema next to the type to trigger an error. We may want to look into transforming custom error messages.

#### Acceptance Criteria

- [x] URL field validation
- [x] Email field validation
- [x] Update `InlineFieldTemplate` to display error message?
- [x] Update documentation

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by marcellmueller** [comment]
@BCerki Looks like this is blocked though I was testing formats and tried using the `format: 'url` built in to RJSF and I think it's too strict. For example it seems to require `http://` and a basic url like `www.google.com` triggers the validation.

We can easily get around this by finding a safe regex and making our own format in `FormBase` `customFormats`.

**Comment by hannavovk** [comment]
@marcellmueller Can we not requite the "http" for the URL to work? cc @dleard
