### ISSUE TITLE
Initial Testing

### ISSUE THREAD

**Issue by hannavovk** [bcgov/cas-registration#317]
We have made the following decisions around testing that we believe to be the best path forward to balance swift delivery and confidence in what we're delivering:
 
We will continue to write tests for the following as they are being developed:
- backend endpoints
- models
- route protection enforcement
We are going to forgo testing the following for now until after the app is fully functional to avoid duplication of effor:
- frontend components (jest)
- e2e tests
The yarn-test and e2e steps in CI will still run (and fail) but will no longer block merging a PR

This epic will contain tickets to complete the jest integration & playwright e2e tests.

**Comment by Dianadec** [comment]
Need to create tickets for each e2e test for each workflow.

Also need all components tested in jest with integration tests.

cc @dleard @Sepehr-Sobhani

**Comment by rdromey** [comment]
Moved to milestones as "Testing"
