### ISSUE TITLE
Set up Redux

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#32]
#### Describe the task

Install Redux and set up the framework for it on the frontend, so that (a) it can be used as an example for future development, and (b) it establishes coding conventions to be used throughout the repo.

#### Acceptance Criteria

- [x] install Redux (using yarn)
- [x] create initial slice, reducer, route, etc. (even if it doesn't actually perform any function, it will be useful to have as a point of reference when developing new features that involve Redux work)
- [x] add Redux Toolkit
- [x] add Server-Side Rendering

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by Sepehr-Sobhani** [comment]
We also need to add SSR at this stage.

**Comment by andrea-williams** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-registration/32?planning-poker) with Zenhub @andrea-williams @BCerki @dleard @JoshLarouche @Sepehr-Sobhani

**Comment by andrea-williams** [comment]
Pressing pause on this - Shon is working on #111, which will probably make this ticket obsolete.

**Comment by Sepehr-Sobhani** [comment]
Addressed in: https://github.com/bcgov/cas-registration/pull/115
