### ISSUE TITLE
Chore to remove legacy file structure to align with protected routes

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#322]

**Comment by shon-button** [comment]
Once #265 is merged, outstanding FE PRs using the legacy file structure remain will need to be integrated into protected routes as required and legacy folders deleted.

**Comment by Sepehr-Sobhani** [comment]
@shon-button I removed a couple of redundant files when I was resolving rebase conflicts as part of my [PR](https://github.com/bcgov/cas-registration/pull/250); Given this, do you think this ticket is still required?
