### ISSUE TITLE
Document data fields that will be needed in Registration app

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#33]
#### Describe the task

Create an Excel spreadsheet (similar to the one that was created for the Reporting app) that documents the data fields that will be needed in the Registration app.

This will partially be a re-work of the Word document that was provided to us by an SME earlier, with the hope of providing clarification.

#### Acceptance Criteria

- [x] document the type of each field (e.g., string, numeric, boolean, dropdown, etc.)
- [x] distinguish btwn required & optional fields
- [x] distinguish btwn fields for Facility (aka Operation) vs Organization (aka Operator)
- [x] identify which fields can be imported from CIIP database
- [x] identify which fields can be pulled from Business BCeID account
- [x] distinguish btwn fields that will be included in MVP, vs. those that can be added post-MVP
- [x] designer to clean up document to improve readability
- [x] designer to share document & questions with business area

#### Additional context

- Look at the admin schema in CIIP to see which data fields are included there
- Or here

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-registration/33?planning-poker) with Zenhub @andrea-williams @BCerki @dleard @JoshLarouche @Sepehr-Sobhani

**Comment by andrea-williams** [comment]
I will start working on this; may need to pass on to someone else to finish off

**Comment by andrea-williams** [comment]
In progress - saved here: https://bcgov.sharepoint.com/:x:/r/teams/00608-ScrumTeam/Shared%20Documents/Scrum%20Team/OBPS/BCERS%20and%20OBPS/Registration%20Fields.xlsx?d=w82d51550187b4e339abb0edb8d43e87a&csf=1&web=1&e=pGyaVw

**Comment by andrea-williams** [comment]
follow-up: create new ticket to gather feedback from B Area

**Comment by nanyangpro** [comment]
Wonderful work, @andrea-williams! - I formatted the sheets and updated the Intro tab to improve readability and will share it with our SMEs for validation/refinements on Monday.
**Question** - Do you expect our SME to update the sheets directly should they see things like missing fields or wrong terminologies, or would you prefer they indicate so in comments and let us make further revisions?

**Comment by andrea-williams** [comment]
Thanks for cleaning it up @nanyangpro ! I think asking our SMEs to add comments in the file with their feedback would probably be best.

**Comment by nanyangpro** [comment]
Hi @hannavovk - This ticket is ready for you to review and can be closed with the follow-up ticket #109 created for the upcoming sprint. (Please see additional information in the comment above. :)

**Comment by hannavovk** [comment]
Great work everyone pulling this together! Thanks @andrea-williams @BCerki @nanyangpro
