### ISSUE TITLE
Report a Problem

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#331]
#### Description:

From the Dashboard page, all users should have the ability to report technical errors.

#### Acceptance Criteria:

Given I have logged into the Registration app as any type of user (internal or external)
When I'm on the Dashboard page
Then a tile labelled "Report a Problem" is displayed

Given I click on the "Report a Problem" tile in my Dashboard
Then (?)

#### Development Checklist:

- [ ] Tile matches wireframe: https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2750%3A23091&mode=design&t=TwvtQeq0SkIDsYoq-1
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by Dianadec** [comment]
Related, 399 is the MVP solution, and this one (331) is either post-MVP or we're not doing it. cc @hannavovk  @BCerki

**Comment by andrea-williams** [comment]
Closing - already completed
