### ISSUE TITLE
e2e testing authentication routes

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-registration#335]

**Comment by Dianadec** [comment]
@dleard @BCerki  is this a duplicate of "Evaluate /test-setup endpoint #235"? https://app.zenhub.com/workspaces/team-moose-sprint-board-60d216175a2689000ec774d0/issues/gh/bcgov/cas-registration/235

**Comment by BCerki** [comment]
> @dleard @BCerki is this a duplicate of "Evaluate /test-setup endpoint #235"? https://app.zenhub.com/workspaces/team-moose-sprint-board-60d216175a2689000ec774d0/issues/gh/bcgov/cas-registration/235

I don't think so. #235 is about re-evaluating the way we've set up some of our e2e testing, and I ~think this one is about writing some specific tests.

**Comment by Dianadec** [comment]
This is already covered (#265) so we will close this one. cc @shon
