### ISSUE TITLE
Load Testing

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-registration#336]
Load testing was done with k6 on CCBC and may be helpful to use as a reference.

Basic setup documentation from CCBC:
https://github.com/bcgov/CONN-CCBC-portal/blob/main/app/tests/perf/README.md

CCBC load test folder
https://github.com/bcgov/CONN-CCBC-portal/tree/main/app/tests/perf

**Comment by mikevespi** [comment]
We need to talk to program area and find out what kind of numbers to be expecting based on their models, that will help us write this up and know what planning we need to do before-hand. Depending on the numbers, we may need to coordinate with Platform Services and schedule this.

**Comment by pbastia** [comment]
What do we aim at load testing? The API endpoints only? Is there a way we can test the performance of the nextjs server actions too, since that might be a bottleneck? cc @dleard @marcellmueller
