### ISSUE TITLE
Select widget should show values, not ids

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#340]
#### Describe the task

Currently, the select widget shows db ids. Instead, it should show the name/value the users can select from. For example, instead of choosing naics category 1,2,3, users should be able to choose "information technology", "healthcare" (or whatever the categories are).

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by marcellmueller** [comment]
Closing as this is handled in #318
