### ISSUE TITLE
Implement change history for industy_user controlled tables

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#359]
We have identified a need to record discrete change history for a subset of our data tables (the ones that have user-entered data like operator/operation). In order to enable this we will implement an erc_history schema in the database which will contain tables that mirror the data in our "live" erc schema, but will have many more rows as each row in our erc schema tables can have many related rows in the _history schema. This will preserve the unicity of the data in our "live" erc schema while allowing us to see the history of change for a specific operator/operation/other entity via the _history schema table.

On saving a form (or later, save as you type) data for the tables below will save their changes to the erc_history schema table. Any subsequent changes, until that data is submitted, are updated in place in that row. Once the data is submitted, the `applied_at` column of the history table is timestamped and the corresponding data row in the erc schema is overwritten with the data from the erc_history row. At this point the latest row in erc_history and erc are equal. Every time the data is set to be edited, a new row in the erc_history schema is created and the process repeats.

Tables that need change history:
- contact
- contact_documents
- multiple_operator <-- has not been created in erc schema yet #280
- operation
- operation_contacts
- operation_documents
- operation_regulated_products
- operation_reporting_activities
- operator
- operator_contacts
- operator_documents
- parent_child_operator? <-- this table in the erc schema likely needs to change (todo: create card & link here)

it's possible (but unlikely) that we won't need _history tables for the intersection tables, that can be determined during implementation.

AC:
- [ ] an erc_history schema exists
- [ ] the erc_history schema has tables with matching data for the above tables 
- [ ] each erc_history table has `source_id` and `applied_at` columns where `source_id` is the id of the erc table and applied at is a timestamptz column which is populated when transferring data from _history to erc
- [ ] endpoints that are currently saving to erc now save to erc_history where appropriate
- [ ] a mechanism exists that sets the `applied_at` column of the _history table and applies that data to the erc table (either in the endpoint or some database function/trigger combo, whichever ends up making the most sense) on final submit of data
- [ ] tests for the erc_history schema & above functionality

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Moose-Sprint-Board-60d216175a2689000ec774d0/issues/bcgov/cas-registration/359?planning-poker) with Zenhub @andrea-williams @mikevespi @dleard

**Comment by dleard** [comment]
I will probably split this up into separate PRs: 1) create schema/models 2) update endpoints / implement data transfer mechanism

**Comment by Dianadec** [comment]
Closing as per discussion with Dylan, Hanna, Andrea, Nan.

**Comment by dleard** [comment]
@Dianadec should we remove the points from this card so it doesn't reflect in our velocity?

**Comment by Dianadec** [comment]
Good flag @dleard . Removed the estimate :)
