### ISSUE TITLE
Archive multiple operators if they are removed from the Operations form

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#361]
In #280 multiple operators are saved in the multiple_operator table once the form is saved. We will need to archive them if they are removed and the form is saved again. This issue is blocked my #326 being implmented.

- [ ] Archive multiple operators if they are removed and the form is saved again
- [ ] Filter out multiple operators that are archived so they aren't displayed in the form

**Comment by BCerki** [comment]
@Sepehr-Sobhani, is this done as part of https://github.com/bcgov/cas-registration/issues/289?

**Comment by rdromey** [comment]
Edge case to still consider

**Comment by BCerki** [comment]
> Edge case to still consider

This is implemented now, see the `upsert_multiple_operators` service. We don't need this ticket anymore
