### ISSUE TITLE
Design Terms and Conditions page

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-registration#370]
#### Describe the task
We need a page for IO to agree to Terms and Conditions when they use the Web App. Envisioned to be very similar to the CIIP app.

Status:
- Business area and FIN working on the content of the T&C.
- DST waiting  to understand better what/when it's and where it should be

#### Acceptance Criteria
- [x] Hanna/Nan discuss status and next steps
- [x] Nan sets up placeholder frame in Figma
- [x] Hanna gets content/copy from the business area
- [ ] Hanna/Nan figure out what the page is for and where the page should be
- [ ] Nan refines design in Figma informed by the CIIP app

#### Dependencies
- Blocked by #604

**Comment by nanyangpro** [comment]
Hey @hannavovk - Could you please forward me Maral's email? Also, would you like to hop on a call sometime tomorrow to discuss the next steps?

**Comment by hannavovk** [comment]
Setting up the page is now covered by #604. This ticket should probably be revised to just finalize the text/copy design. @nanyangpro @Dianadec

**Comment by nanyangpro** [comment]
Hi @hannavovk - Shall we close this ticket? Marcel created #645 , I've included implementing the finalized languages on the page there. cc: @Dianadec
