### ISSUE TITLE
Breadcrumbs - support for multiple dynamic routes

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#371]
#### Describe the task

The breadcrumbs have issues with routes ending with multiple dynamic routes such as the operations form `dashboard/operations/1/1`. If you click the first `ID 1` in the breadcrumbs it will give a `The page you’re looking for is unavailable` as the route doesn't exist without specifying a form page. An easy solution to this issue might be to just remove the link from the dynamic routes so they are viewable but not clickable. 

#### Acceptance Criteria

- [ ] Create actions display in the breadcrumb
- [ ] Form section ID is removed from the breadcrumbs

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by shon-button** [comment]
Ensure the breadcrumb key is unique to avoid:

app-index.js:32 Warning: Encountered two children with the same key, `2`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

From e.g: http://localhost:3000/dashboard/operations/2/2

**Comment by nanyangpro** [comment]
Hi @marcellmueller - I see a UX Design tag on this ticket, is it something that can be resolved over a quick call? Anything else needed from me beforehand?

**Comment by nanyangpro** [comment]
Good suggestion, @marcellmueller! 

I've booked a meeting with you and @shon-button for the discussion tomorrow morning. Looking forward to some solutioning/decision-making out of it.

**Comment by shon-button** [comment]
@nanyangpro 

Hi Nan,

I didn't see a calendar invitation come my way yet but, can we meet to discuss the breadcrumbs after 12 pm PST?

Thanks :)

**Comment by nanyangpro** [comment]
Hi @shon-button - I rescheduled the chat to tomorrow morning since Marcel is away today and I'll be at our branch appreciation event this p.m.

(Feel free to let me know if you haven't got the invitation still. :)
