### ISSUE TITLE
e2e tests for all major user workflows

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-registration#372]
### Description

We need to make separate tickets for all the things related to this (may be more than what's listed below depending on how many features are complete before this ticket is pulled in):

### Dev Tasks
- Identify User Flows:
Use Figma to identify key user flows and interactions 
- Create Test Scenario Cards:
Based on the identified user flows, create cards for test scenarios that cover critical paths and user interactions.
Include positive and negative test cases to ensure the application behaves as expected.

#### Architectural Design

Using a balanced approach between between testing a page using each role or testing a role for each page.
- Initial tests of critical pages with each user role to ensure comprehensive coverage of essential functionalities. 
- Subsequent tests to target specific roles interacting with specific pages, especially for pages with role-specific features.

1. **Test a Page Using Each Role:**
   - **Pros:**
     - Comprehensive Coverage: This approach ensures that each page is tested with every user role, providing a comprehensive view of how different roles interact with each page.
     - Identifies Cross-Role Issues: Helps identify issues related to role-based permissions and ensures that a user with a specific role can access and interact with the expected content on each page.
   - **Cons:**
     - Repetition: The test scenarios for each role may overlap, leading to some repetition in test code. Maintenance may become more challenging as the number of roles and pages increases.

2. **Test a Role for Each Page:**
   - **Pros:**
     - Clear Test Focus: Each test focuses on a specific role, making it easier to understand and manage the purpose of each test.
     - Isolation of Issues: If a test fails, it is easier to isolate the issue to a specific role and page combination.
   - **Cons:**
     - Limited Cross-Role Coverage: This approach may not provide as comprehensive coverage across all user roles for each page, potentially missing cross-role issues.

### Page by Role Tests: `e2e\pages`

- [x] [home page/login-logout-login](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=49133752)

### Role by Page Tests: `e2e\workflows`

[Flow of Current Implementation](https://miro.com/app/board/uXjVN6uBj9Y=/)

#### Industry operator flows:

 **bceidbusiness\new user** interactions in the system:
[Ticket 800](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=51945351)

 **bceidbusiness\industry_user** interactions in the system:
[Ticket 505](https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=e2e&pane=issue&itemId=49836206)

**bceidbusiness\industry_user_admin** interactions in the system:
[Ticket 843](https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=e2e&pane=issue&itemId=52566898)

#### CAS flows

**idir\cas_pending** interactions in the system:
[Ticket 846](https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=e2e&pane=issue&itemId=52567549)

**idir\cas_analyst** interactions in the system:
[Ticket 845](https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=e2e&pane=issue&itemId=52567438)

**idir\cas_admin** interactions in the system:
[Ticket 844](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=52567202)

**Comment by Dianadec** [comment]
This card is more like a reminder - we need to split this card up into smaller pieces to identify what we actually need to action. CC @shon-button .

**Comment by nanyangpro** [comment]
Re: Refinement discussion - This is more like an epic.

**Comment by rdromey** [comment]
Tickets to be added to the Testing milestone if not already completed.
