### ISSUE TITLE
Flag when a new Operator has been added to the database

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#376]
#### Describe the task

When a user creates a brand new Operator (i.e., not one that already existed in our database), we want to add a boolean flag to the record in the database indicating that it's new. This "is_new" flag will indicate whether CAS internal staff need to explicitly approve the Operator at the same time that they're approving the request for prime admin access.

(Operators imported from CIIP will have `is_new` flag set to `false`, ~~and will automatically have their `status` set to `Approved`~~ when the data is imported).

#### Acceptance Criteria

- [x] when an internal user is reviewing a prime admin access request, if the Operator info that they're viewing at the same time (https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=413%3A48&mode=design&t=b0MX1lfLnGp4Rch3-1) has the `is_new = True` flag, the internal user will have to explicitly Approve the Operator before the prime admin request can be approved. If the Operator is not new (i.e., `is_new = False`, the internal user will not need to change the Operator's status.
- [x] once an Operator's status has been set to Approved, the `is_new` flag can be set to `False`
- [x] if the internal user Requests Changes for the new Operator, the `is_new` flag will remain as `True` until the Operator's status is changed to Approved
- [x] add a very descriptive comment to the `is_new` column on the Operator table to avoid developer confusion (most specifically, what the difference is between the `is_new` flag and the `status` column)

#### Additional context

- Blocked by #25

**Comment by andrea-williams** [comment]
@nanyangpro  do you plan to update the wireframes with some sort of marker so that internal users can tell when an Operator is brand new?

**Comment by nanyangpro** [comment]
Yes, @andrea-williams. I'll add the link once done. Before I proceed, I've got a [question](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8?node-id=413:48&mode=design#637079516) for you in Figma, could you please review and confirm there? Thanks!

**Comment by Dianadec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Moose-Sprint-Board-60d216175a2689000ec774d0/issues/bcgov/cas-registration/376?planning-poker) with Zenhub @andrea-williams @BCerki @dleard @JoshLarouche @marcellmueller @Sepehr-Sobhani @shon-button

**Comment by dleard** [comment]
@andrea-williams I think we said if we auto-approve operators that are imported, we don't have all the data we require from them at that time & there will be updates after approval. I think `is_new` may still be useful information to the business area even if we decide to auto-approve. Should we compare what we get from importing for an operator vs what we ask for to help inform our decision on auto-approval?

**Comment by Sepehr-Sobhani** [comment]
> @andrea-williams I think we said if we auto-approve operators that are imported, we don't have all the data we require from them at that time & there will be updates after approval. I think `is_new` may still be useful information to the business area even if we decide to auto-approve. Should we compare what we get from importing for an operator vs what we ask for to help inform our decision on auto-approval?

@andrea-williams / @dleard I was mostly suggesting that because we are currently not using `status` field of the Operator data model anywhere in the code, I was wondering if maybe we could benefit from that field or remove it if not needed.

**Comment by andrea-williams** [comment]
the status field on the Operator will now be used; i.e., new Operators will require explicit approval from CAS internal staff

**Comment by BCerki** [comment]
After talking with @nanyangpro , the design and styling of this feature are going to use the multistep component rather than the collapsible sections. The important pieces to retain from the wireframe are:
- text to indicate that new operations are new
- approve/reject buttons only affect the piece of the form they show up on (e.g., approving the operator only approves the operator, and the user needs to be approved separately on the next page)
