### ISSUE TITLE
Delete Contact if Prime Admin Request is Rejected

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#379]
#### Describe the task

Since we don't want external users to be able to modify Operator data before they've been granted access to a given Operator, we need to add some extra logic for handling cases where a prime admin access request is rejected.

#### Acceptance Criteria

- [x] if the request for prime admin access is rejected, the Senior Officer data (in the `contact` table) that was entered by the user requesting prime admin should be deleted from the database (this will also affect the `operator_contacts` through table)
- [x] if the request for prime admin access is approved, the Senior Officer/Contact data does not need to be changed in any way

#### Additional context

- once we have audit columns in place on all tables that need them, we can use the `created_by` FK reference to the user requesting prime admin to find the contact record/s (I think there will only ever be 1) for the given Operator that were created by the rejected prime admin user
- e.g., if the rejected prime admin user has ID = 2 and their Operator has ID = 1, we'd want to get IDs for all Contact records that were `created_by` user.id = 2, and then query those contact IDs against the OperatorContact through-table to find the contacts for operator.id = 1, and delete all of those records. If we've configured our data models correctly, deletion from the Contact table should cause a cascading delete on the OperatorContact table, but we'll want to double-check that when working on this ticket.

#### Dependencies
- Blocked by #326 
- Blocked by [#498](https://app.zenhub.com/workspaces/team-moose-sprint-board-60d216175a2689000ec774d0/issues/gh/bcgov/cas-registration/498)

**Comment by andrea-williams** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Moose-Sprint-Board-60d216175a2689000ec774d0/issues/bcgov/cas-registration/379?planning-poker) with Zenhub @andrea-williams @BCerki @dleard @JoshLarouche @Sepehr-Sobhani @shon-button @marcellmueller

**Comment by marcellmueller** [comment]
@andrea-williams I thought we were archiving on delete instead of a hard delete?

**Comment by andrea-williams** [comment]
> @andrea-williams I thought we were archiving on delete instead of a hard delete?

as a general rule throughout the app, yes, we'll want to archive rather than a hard-delete. In the specific scenario captured in this ticket, the record deletion is a bit of a band-aid fix because there's a flaw in our logic that we didn't notice soon enough. I'd argue for hard-deletion in this scenario because we'll be removing data that is likely garbage data because it was entered by an external user without admin permissions. In most/all other scenarios we'll want to archive records because that data was at point valid, but has become outdated. In the case of this Senior Officer contact data, it should be considered to have never been valid data, so we're scrubbing it from our DB for the sake of data integrity.

But I'm open to hearing your opinion if you disagree! I'll also loop @dleard  into this convo.

**Comment by marcellmueller** [comment]
Nope I'm happy with that, was just looking for clarification thanks :)

**Comment by shon-button** [comment]
Blocked by bug in `client/app/components/routes/select-operator/form/UserOperator.tsx` when 
```
export async function getUserOperatorFormData(id: number | undefined) {
  if (!id) return {};
  return actionHandler(
    `registration/select-operator/user-operator/${id}`,
    "GET",
    `/user-operator/${id}`
  );
}
```
 returns Server error

**Comment by Sepehr-Sobhani** [comment]
@andrea-williams Should we also archive the `user_operator` instance when rejecting?

**Comment by andrea-williams** [comment]
> @andrea-williams Should we also archive the `user_operator` instance when rejecting?

To be honest I/the team haven't given that much thought yet. I'd recommend for now that we don't archive on reject right now, although that might change in the future. I think we'll need insight from the business area/internal users on whether they want to be able to view the list of rejected admin requests directly within the app (vs. just going to Metabase).

**Comment by Sepehr-Sobhani** [comment]
> > @andrea-williams Should we also archive the `user_operator` instance when rejecting?
> 
> To be honest I/the team haven't given that much thought yet. I'd recommend for now that we don't archive on reject right now, although that might change in the future. I think we'll need insight from the business area/internal users on whether they want to be able to view the list of rejected admin requests directly within the app (vs. just going to Metabase).

Ok, Thanks Andrea!
