### ISSUE TITLE
Add user tracking to history tables

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#387]
Once #326 is in, we can add user tracking to the history tables in the `erc_history` schema so that all changes are associated to a user. We can use [this method](https://django-simple-history.readthedocs.io/en/latest/user_tracking.html#using-history-user-to-record-which-user-changed-a-model) from the simple history docs.

AC:
- Add user tracking to the history tables using the documentation linked above

Blocked by: 
#326 
#381
#451

**Comment by Sepehr-Sobhani** [comment]
@dleard To implement this, we require a data field named `changed_by` (or something similar) to be present on all tables. However, we currently only support such a field in data models with audit columns, which means we would have to update it manually. I suggest making this ticket dependent on the ticket: https://app.zenhub.com/workspaces/team-moose-sprint-board-60d216175a2689000ec774d0/issues/gh/bcgov/cas-registration/451, so we can utilize a better solution and avoid the need for manual updates to history data models.
