### ISSUE TITLE
CAS admin should not be able to edit the Operation form

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#392]
#### Describe the task

Currently a user logged in as `cas_admin` can edit the Operation form. This form should be read only for `cas_admin`.

#### Acceptance Criteria

- [x] Operation form is read only when logged in as `cas_admin`

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by Dianadec** [comment]
@dleard : "Fix this but also check the other forms."

**Comment by Dianadec** [comment]
This also might just be front-end ( @BCerki )
