### ISSUE TITLE
"Client-side" data refresh

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#406]

**Comment by shon-button** [comment]
Currently, we manage data changes from the backend to the frontend by using server action and revalidatePath, or refresh page.

This paradigm works well in use cases that flow from one screen to another but, may prove inefficient and/or a poor user experience if the screen does not navigate away after a data change.

Perhaps, we might implement a "client-side" data management using useEffect...

**Comment by joshgamache** [comment]
Is this somewhere that [on-demand revalidation](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#on-demand-revalidation) might work? I'm still not super familiar with Next 13/14/App dir, but it seems like it might apply in this case. 
Skimming over `client/app/utils/actions.ts:actionHandler()`, it seems like it might work there.

**Comment by shon-button** [comment]
@joshgamache in fact on-demand re-validation is handled in client/app/utils/actions.ts:actionHandler() where if a re-validate path is provided then the path is re-validated (on demand) but using revalidatePath which uses "refresh page"  strategy (I believe) . As mentioned above we may want to avoid this refresh page on some screens using useState as detailed above.
