### ISSUE TITLE
Form design bugs [5]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#409]
Describe the Bug:

Some bugs have popped up and the forms no longer match the designs: 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVZUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4eecfb1d9cf07f617a7e00198fbd073a34b6879/Screenshot%20from%202023-12-12%2011-34-12.png" alt="Screenshot from 2023-12-12 11-34-12.png" />

**Comment by BCerki** [comment]
Flagged as deletion candidate because I think @marcellmueller fixed this as part of another PR recently

**Comment by marcellmueller** [comment]
This is fixed so we could close it or leave it up to add other form design bugs.

**Comment by BCerki** [comment]
I vote close
