### ISSUE TITLE
Parent-child operator data should be saved as metadata in a separate table

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#415]
The current implementation of parent-child operator data is saved and referenced in the operator table. However, a parent operator may or may not be part of our system (may never report). In this case, we're adding data to a table that we use for reporting and for assigning permissions that will never be used for that purpose. In the other case, if an operator defines a parent that does report to us, then we're allowing both the child operator and the parent operator to change that operator's data (which can't happen).

Parent-child operator relationships should be handled in the same way as we implemented for an operation that has multiple operators. Multiple operator data was saved in a separate mutliple_operator table as metadata pertaining specifically to the operation that defined it. This isolates the data and makes it only referenced and updated by the entity that created it (in multiple_operators, the operation. In the case of this card, it will be the child operator).

The implementation here should be very similar to what was done in #280.
The PR where #280 was implemented can be found here: https://github.com/bcgov/cas-registration/pull/350

I was initially thinking that this data could live in the multiple_operator table, but after some thought and a chat with other devs, let's create a separate table. The parent operator vs multiple operator data will be the same, but they are semantically different enough that it probably makes sense to live in a different table. Also taking into account how this data will be used later (in metabase by CAS staff) this separation in the schema will probably make more sense to our end users.

Wireframe:
https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2401%3A331&mode=design&t=UiPqOsrnUBd3ceLQ-1

AC:
- [x] add a new table 'parent_operator' to the erc schema
- [x] the new table has history tracking in the erc_history schema
- [x] the new table has the same structure as the 'multiple_operator' table
- [x] the form allows for multiple parent operators (see implementation of multiple_operators, should be similar)
- [x] update endpoints so that when saving parent operator data, it is no longer saved to the operator table, it is saved to the new parent_operator table as metadata
- [x] model & endpoint tests

**Comment by dleard** [comment]
@nanyangpro The wireframe I linked in this card needs a small update to allow for multiple parent operators to be defined in the form (pretty much the same as we define multiple operators in the operation wireframe)

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Moose-Sprint-Board-60d216175a2689000ec774d0/issues/bcgov/cas-registration/415?planning-poker) with Zenhub @dleard @Sepehr-Sobhani @BCerki @JoshLarouche @marcellmueller @andrea-williams

**Comment by nanyangpro** [comment]
Thanks @dleard! The [wireframe](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2401%3A331&mode=design&t=Gxbi2HbxWsKykvfS-1) has been updated as discussed.
