### ISSUE TITLE
Search by operator name requires an exact match [7]

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#418]
Edit: This PR was changed to be a user story implementing a search dropdown using MUI autocomplete.

- [x] Searching does not require an exact match
- [x] Search results display as the user types

Describe the Bug:

When searching for an operator by legal name in the search dropdown, it requires an exact match to find the operator. This is counterintuitive to how these search dropdowns usually work.

Expected behaviour would be to at least return any results that contain the search parameter (case insenstive)

Probability (how likely the bug is to happen, scored from 1-5): 5

Effect (how bad the bug is when it does happen, scored from 1-5): 2

Steps to reproduce the behaviour:

As an industry user without any permisisons go to the operators page to search for an operator.
Our operators in the database are { Operator 1 Legal Name, Operator 2 Legal Name }
Type 'operator' in the box and search, no results will come up.

Screenshots:<img width="671" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzVjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ca819731be7a1380e1c6bee9233350d2c1c8155/Screenshot%20from%202023-12-13%2014-38-39.png" alt="Screenshot from 2023-12-13 14-38-39.png" />

**Comment by Sepehr-Sobhani** [comment]
@dleard According to the wireframes, we display only one operator and do not provide a dropdown for searching. When the user looks for a specific operator, we must return only one, which is why the name must be exact.

**Comment by dleard** [comment]
It looks like the wireframe is only showing the behaviour when entering a CRA business number, in which case that is true, only one operator should match a CRA number. But requiring an exact, case sensitive match in the search box is going to be frustrating to users. Is returning only one operator a requirement from somewhere?

**Comment by dleard** [comment]
I'll mark this for refinement and we can discuss today.

**Comment by Sepehr-Sobhani** [comment]
During the backlog refinement, it was decided to update the button label to "Select Operator". For legal name search, we could utilize a Combobox widget to execute the search on the front-end. As for the CRA business number, the user must provide the exact number.
