### ISSUE TITLE
Logging in for the first time re-signin flow

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#420]
#### Description:

Currently, when a user is logging in for the first time (they are not in our database & have to fill out the initial registration form) they are redirected to /home for re-login so to apply the user role to the security token (JWT)

Alternatively, we can use NextAuth update() method add the role to the session role.

#### Acceptance Criteria:

Given I am a new User
When I click the authenticate using my Keycloak login
Then I am taken to the `Dashboard\Profile` page that shows me a profile form

Given I am an authenticated new user
When I submit the profile form
Then I am assigned an app role and can navigate to my `Dashboard` page

#### Development Checklist:

- [x] modify `client/app/components/routes/profile/form/UserForm.tsx` to call nextauth update() after form submit event
- [x] modify `client/app/api/auth/[...nextauth]/route.ts` to evaluate token,app_role on any JWT call back (not just create trigger)
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

[update](https://next-auth.js.org/getting-started/client#updating-the-session)
The useSession() hook exposes a update(data?: any): Promise<Session | null> method that can be used to update the session, without reloading the page.
You can optionally pass an arbitrary object as the first argument, which will be accessible on the server to merge with the session object.
If you are not passing any argument, the session will be reloaded from the server. This is useful if you want to update the session after a server-side mutation, like updating in the database.

**Comment by shon-button** [comment]
Tech Debt from https://github.com/bcgov/cas-registration/pull/368 
See: "ToDos: Perhaps a better flow is required for new user POST profile like a signout to signin re-direct but I had issues implementing this"

**Comment by shon-button** [comment]
DL: is something that I think we need to fix before the Jan 22 launch.
