### ISSUE TITLE
As a user, I want to see the appropriate operations table for my app role type

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#421]
#### Description:

We often reuse components across the app, but in some cases, the components need to be slightly customized depending on who (IO or CAS user) is viewing the component. This card is about creating the correct views for the Operations form

#### Acceptance Criteria:

Given I am an IRC user
When I click the Operations tile
Then I am taken to page that shows me a table
And shows me a Note (see [wireframe](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=9%3A10&mode=design&t=Gxbi2HbxWsKykvfS-1))
And I see all operations for all operators except those with a not registered or draft status

Given I am an IO user
When I click the Operations tile
Then I am taken to page that shows me a table (see [wireframe](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=19%3A2197&mode=design&t=Gxbi2HbxWsKykvfS-1))
And an `Add Operation` button
And I see all operations my operator owns regardless of status 

#### Development Checklist:

- [x] create a note component (other pages will have notes, so we can reuse it with customized text)
- [x] in the operations endpoint, filter out operations with draft and not registered statuses if the user is IRC (there's already conditional logic for IRC vs. IO users, just add to that)
- [x] the IO user AC should already be complete; just make sure the changes don't introduce any bugs
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by nanyangpro** [comment]
Thanks for creating this ticket, @BCerki! 
- I added links to the wireframes in the ticket description
- Yes, internal gov users should only see "Pending"/"Rejected"/"Approved" operations. Operations with status "Draft"/"Not Registered" are only viewable by the external users
    - However, that being said, did we decide to reword or discard "Rejected" at some point so that it's less strong, @dleard, @andrea-williams?

**Comment by Dianadec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Moose-Sprint-Board-60d216175a2689000ec774d0/issues/bcgov/cas-registration/421?planning-poker) with Zenhub @andrea-williams @BCerki @dleard @JoshLarouche @marcellmueller @Sepehr-Sobhani @shon-button

**Comment by Dianadec** [comment]
During refinement we discussed replacing "rejected" with "declined"
