### ISSUE TITLE
Tax Exemption ID ---> BC OBPS Regulated Operation ID and more...

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-registration#427]
#### Describe the task

We need to change the wording of `Tax Exemption ID` to `BC OBPS Regulated Operation ID` wherever it has been used. Based on Dylan's comment we also need a **separate table** to hold some extra data for different scenarios.
Dylan's comment: an exemption should probably have some extra data associated with it such as issued_at, expires_at, maybe a status & some comment metadata in the case that an exemption is revoked.

#### Acceptance Criteria

- [x] Change the wording of `Tax Exemption ID` to `BC OBPS Regulated Operation ID`
- [x] Create a new data model for `BC OBPS Regulated Operation ID` with the below fields:
   - issued_at
   - ~expires_at~
   - comment
   - ...?

- [x] Operation table should have FK to the newly created table -> Changed to OneToOneField for uniqueness across operation instances.

**NOTE from Dylan**: perhaps a status column for valid/revoked? Other than that this looks good, we could also ask our SMEs if there's any other metadata about the exemption ID that CAS thinks would be helpful

**Comment by andrea-williams** [comment]
From what I've understood from the business area, there won't be a set expiry_date for an ID, but they will need some mechanism to "expire" or revoke IDs. The example I heard was that if the legal name of an operator or operation changes, the ID will need to be revoked and a new one issued.

**Comment by Dianadec** [comment]
Test comment
