### ISSUE TITLE
Add Roles enum to User Model

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#428]
Currently, `bc_obps/registration/api/user.py` uses enum vaues from `
from registration.enums.enums import Roles` but,...

**B.C.**
"...I think we actually could use the role choices in the User model (I'm not sure why it isn't already like that, maybe we thought we'd have a ton of roles?).
It could look like this..."

class User(UserAndContactCommonInfo):
    """User model"""
    class Roles(models.TextChoices):
        CAS_ADMIN = "cas_admin"
        ...
...
    app_role = models.ForeignKey(
        AppRole,
        choices=Users.choices,
        on_delete=models.DO_NOTHING,
        related_name="users",
        db_comment="The role assigned to this user which defines the permissions the use has.",
    )

**Comment by Sepehr-Sobhani** [comment]
We just need to remove `AppRoles` from `enums.py` file

**Comment by nanyangpro** [comment]
Closing as discussed during refinement. @sepehr will take care of the twist he suggested above.
