### ISSUE TITLE
Consider renaming the `select-operator` front-end endpoint

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#444]
###Description of the Tech Debt###

Initially, the `select-operator/Page.tsx` was only used for selecting operators. Now, it's being used for all IO workflows associated with operator information. This ticket is about choosing a new name for that route that's more representative of what it actually does.

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |       |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |       |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |       |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |       |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |       |
| TOTAL SCORE:                                                                                                                  |       |       |

**Comment by dleard** [comment]
I think we should consider breaking up both the frontend route & the backend api path to separate concerns. Both the frontend route and the backend api route are doing too many things.
