### ISSUE TITLE
Refactor API endpoint protections logic to be more Pythonic [8]

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#445]
###Description of the Tech Debt###

Suggestion from @Sepehr-Sobhani to take a more Pythonic approach to how our API auth-based endpoint protections are implemented:

```
def authorize(authorized_roles: List[str]):
    def decorator(router_func):
        def wrapper(request, *args, **kwargs):
            try:
                # authorization code here...
            except HttpError as e:
                return e.to_response()
            return router_func(request, *args, **kwargs)
        return wrapper
    return decorator
```

and then decorate all API endpoint definitions with tags like this:

```
@router.post("/user-operator/contact", response={200: str})
@authorize(authorized_roles=[# Specify authorized roles here]) 
def create_user_operator_contact(request, payload: UserOperatorContactIn):
```

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |    1   |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |    2   |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |    1   |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |   2    |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |   2    |
| TOTAL SCORE:                                                                                                                  |       |   8    |

**Comment by shon-button** [comment]
Adding the `[# Specify authorized roles here])` of `@authorize(authorized_roles=[# Specify authorized roles here])`  c/should use enum Roles instead of "hard-coded" as in:
` raise_401_if_role_not_authorized(request, ["industry_user", "industry_user_admin", "cas_admin", "cas_analyst"])`

**Comment by Sepehr-Sobhani** [comment]
@shon-button That's a good point, Thanks 👍 I just think we should check them against existing `AppRole` data model instances instead of enums.

**Comment by shon-button** [comment]
💯 👍

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
