### ISSUE TITLE
Django API errors

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#453]
Describe the Bug: 

**1.**
Calling Django API endpoints before the NextAuth token has been created results in error `"" is not a valid UUID` since
`client/app/utils/actions.ts\actionHandler` is setting `Authorization: header to ""`

Probability (how likely the bug is to happen, scored from 1-5): 5
Effect (how bad the bug is when it does happen, scored from 1-5): 1

Steps to reproduce the behaviour: 
Log into the app using IDIR or BCeid
Verify call to `registration/user-app-role/${token.user_guid}` caused Django API message: "" is not a valid UUID

**Possible Solution:**
- Obtain value for Authorization: header from UUID segment from endpoint

**2.**
New user flow errors since previously functioning as expected in PR [368](https://github.com/bcgov/cas-registration/pull/368)
<img width="1713" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzkvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a1e9f7f540817809ec5227307a18ce13716de786/image.png" alt="image.png" />

[21/Dec/2023 17:18:32] "GET /api/registration/user-app-role/58f255ed8d4644eeb2fe9f8d3d92c684 HTTP/1.1" 401 27
No User matches the given query.
[21/Dec/2023 17:18:32] "GET /api/registration/user-profile HTTP/1.1" 401 27

**3.**
e2e Authentication routes tests fail since previously functioning as expected in [446](https://github.com/bcgov/cas-registration/pull/446)
Running 24 tests using 6 workers
  1) [chromium] › auth/authentication.spec.ts:60:9 › Test Dashboard › Test Auth Session - cas_admin › Test Role Based UX 

    Test timeout of 30000ms exceeded.

**Comment by Sepehr-Sobhani** [comment]
This comes from line 18 of `CurrentUserMiddleware`. We can safely bypass it by replacing the `print` statement with `pass`.
