### ISSUE TITLE
Select Operator By CRA Number

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#455]
Currently `Dashboard > Select Operator\Search by Canada Revenue Agency (CRA) Business Number` has the following issues:

- Error after clicking "Select Operator" causes radio button to default to `Search by Business Legal Name`
- Return to `Dashboard > Select Operator` from `Dashboard > Select Operator > ID ` causes radio button to default to `Search by Business Legal Name`
- IMO, I think the cra search should work as text search (experience with past users searching on ids)

**Comment by Sepehr-Sobhani** [comment]
Side note: We might consider refactoring the `operator.py` file as it currently has two endpoints named `get_operator_by_legal_name_or_cra` that are very similar. It would be better if we could merge them into one endpoint and return the value conditionally. Additionally, we need to ensure that each endpoint checks for the user's authorization before proceeding.

**Comment by BCerki** [comment]
I think this is the same as https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=53174092

**Comment by nanyangpro** [comment]
Fixed. Closing as discussed during refinement.
