### ISSUE TITLE
Brand new user is blocked from doing anything [10]

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#456]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 5
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 5
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
1. When running the app locally, log out of the app and then delete your user from your local db
2. Log back into the app using your idir or business bceid
3. You'll be redirected to the Profile page with a 401 message (unauthorized)

Additional information:
- backend server log shows the following errors:
```
[20/Dec/2023 19:42:20] "GET /api/registration/user-profile HTTP/1.1" 401 27
No User matches the given query.
Unauthorized: /api/registration/user-app-role/{user_guid}
[20/Dec/2023 19:42:21] "GET /api/registration/user-app-role/{user_guid} HTTP/1.1" 401 27
No User matches the given query.
Unauthorized: /api/registration/user-profile
```

**Comment by shon-button** [comment]
Handled [here](https://app.zenhub.com/workspaces/team-moose-sprint-board-60d216175a2689000ec774d0/issues/gh/bcgov/cas-registration/453)
