### ISSUE TITLE
Make dashboard tiles look like wireframes

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#458]
#### Describe the task

The dashboard tiles should be updated to look like the wireframes

Current look:
<img width="1467" alt="Screenshot 2023-12-20 at 11 43 55 AM" src="https://github.com/bcgov/cas-registration/assets/14259474/08438674-ccc7-4c12-a5d1-b0e57efdeb42">

Wireframes:
<img width="1099" alt="Screenshot 2023-12-20 at 11 46 35 AM" src="https://github.com/bcgov/cas-registration/assets/14259474/426baa18-203b-4212-8e89-f16be13bb29b">

[Link to wireframes](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2414%3A1571&mode=design&t=BemM2GNhrV2VFbUH-1)
#### Acceptance Criteria

- [ ] Update the tiles

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by andrea-williams** [comment]
Don't think this is needed anymore - the work has been done in another ticket.

**Comment by marcellmueller** [comment]
Closing as this has been completed.
