### ISSUE TITLE
Multistep form should not save/submit when clicking 'Next' if form is disabled [6]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#460]
Describe the Bug:

The multistep form still saves/updates the form when clicking the `Next` button when viewing the form in a readonly/disabled state.

Probability (how likely the bug is to happen, scored from 1-5): 3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

- Use a multistep form in a disabled/readonly state (either logged in as cas admin/analyst or if form state is pending).
- Click next to view the next page
- View backend dev console and see a `PUT` operation

**Comment by marcellmueller** [comment]
Nice catch! This _should_ be fixed with some updates in pr #25 so we will verify once that goes in.

**Comment by marcellmueller** [comment]
Actually another thing I just noticed is that clicking `Next` will also update the form so I think that should be handled in this ticket.

**Comment by BCerki** [comment]
This should be fixed by https://github.com/bcgov/cas-registration/pull/492
