### ISSUE TITLE
Operator legal_name and bc_corporate_registry_number fields should have unique constraint

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#462]
#### Describe the task

The `legal_name` of an operator should have unique constraint. This will ensure users don't enter the same Operator twice or choose the wrong one when they search their Operator.

#### Acceptance Criteria

- [x] Operator legal_name field is unique
- [x] Operator bc_corporate_registry_number is unique
- [x] Test this in the `Add operator` form and make sure the error response is readable for a non technical user
- [ ] If further validation is required we might want to make another ticket

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by dleard** [comment]
developer to review (Not a PO concern)
