### ISSUE TITLE
Operator form phone number doesn't come out of db correctly [5]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#466]
Describe the Bug:

When viewing the readonly version of a submitted form, the phone number is missing:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnQvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f84e6fe849e1e43225d710679905bd6006ed6852/image.png" alt="image.png" />
Places to start:
- this might just be invalid mock data--try changing the phone number in the fixtures and see if that helps
- ninja schema

Probability (how likely the bug is to happen, scored from 1-5): 3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by Sepehr-Sobhani** [comment]
This is invalid mock data in `contact.json` file. instead of `123-456-7890` we should use `+1234567890`.
