### ISSUE TITLE
User profile requires a refresh before showing updated info [4]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#467]
Describe the Bug:
https://www.loom.com/share/4f59041332fc45a3aad6858cf4654bf1
Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by Sepehr-Sobhani** [comment]
Addressed in: https://github.com/bcgov/cas-registration/pull/477

**Comment by shon-button** [comment]
Handled [here](https://app.zenhub.com/workspaces/team-moose-sprint-board-60d216175a2689000ec774d0/issues/gh/bcgov/cas-registration/453)
