### ISSUE TITLE
Make operation table match wireframe

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#468]
###Description of the Tech Debt###

This ticket is about making the currently implemented operations table match the wireframe: https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=9-10&mode=design&t=RTQrkxl7Upj6pRkn-0

Edit: Data is currently not being shown in the table's cells. As part of this card, ensure that the data is properly displayed in the table.
- Todo:
- Add a submission_date timestamp column to the operation table
- The submission_date timestamp should be populated when the IO user submits their operation registration request
- The BORO ID should be displayed
- The bcghgid should be displayed

AC:
- [x] the operation table has a submission_date timestamp column
- [x] the submission_date column is populated when IO user submits their operation registration request
- [x] once approved, the BORO ID is displayed properly in the table for both IO & internal users
- [ ] the bcghgid is displayed properly in the table for both IO & internal users
- [x] headers and columns are the same as the wireframe
- [x] if there's no bghg id, show a placeholder
- [x] remove operations list header
- [x] if quick and easy, match the styling to what's currently implemented in the users table. If not quick and easy, make a new tech ticket for design updates

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |       |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |       |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |       |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |       |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |       |
| TOTAL SCORE:                                                                                                                  |       |       |

**Comment by dleard** [comment]
Updated this card to include making sure that the necessary content of the table is properly displayed (current implementation is missing data) cc @hannavovk

**Comment by marcellmueller** [comment]
After discussion we decided not to change the `Operation ID` column to the `BCGHG ID` column as not all applications have  one so we wouldn't be able to use it in the dynamic routes for an id to fetch the data. We have decided to move this to a post MVP improvement.

**Comment by hannavovk** [comment]
The operator column is not showing up. Can someone please look into this? @marcellmueller @andrea-williams 


![Image](https://github.com/bcgov/cas-registration/assets/87211104/f8fe4a85-7a81-4632-aa2e-a4cf2e40c481)

**Comment by marcellmueller** [comment]
Operator column is supposed to display for Internal users but not industry user as per discussion with @nanyangpro.

**Comment by andrea-williams** [comment]
Confirming that the Operator column appears in the Operations table when logged in as a CAS internal user.
