### ISSUE TITLE
Make operator table match wireframe

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#469]
###Description of the Tech Debt###

This ticket is about making the currently implemented operator table match the wireframe: https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=9-9&mode=design&t=71MafyBZE5QLO8M3-0

AC:
- [ ] headers and columns are the same as the wireframe (in the demo @andrea-williams mentioned that we were going to remove the Request ID but as of writing it's still in the wireframe, so confirm)
- [ ] if quick and easy, match the styling to what's currently implemented in the users table (pills). If not quick and easy, make a new tech ticket for design updates

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |       |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |       |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |       |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |       |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |       |
| TOTAL SCORE:                                                                                                                  |       |       |

**Comment by BCerki** [comment]
asked @nanyangpro for more details about the missing columns in figma comments

**Comment by BCerki** [comment]
After chatting with @nanyangpro in figma, the operator table doesn't require any changes (using the database id for request id is fine, and we don't need to add the BCeID column). @hannavovk , are you ok to close this issue?

**Comment by marcellmueller** [comment]
As per discussion with Hannah and Nan we are keeping the Request ID column for now and may revisit it post MVP. They wanted a column that has a unique identifier that will be visible in the breadcrumbs if they click on a form to view.
