### ISSUE TITLE
As an admin IO user, I want to assign a role when approving my users

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#470]
#### Description:

Admin IO users should be able to choose what role to assign their company's users.

Wireframe: https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2719-15135&mode=design&t=RTQrkxl7Upj6pRkn-0

#### Acceptance Criteria:

Given I am an admin IO user
When I go the the users tile and see the list of my company's users
Then I can approve users as either admins (same permissions as me) or reporters (can't see the user tile)

#### Development Checklist:

- [x] Add a dropdown to the users table so admins can select the `reporter` or `admin` role
- [x] When the IO user clicks approve:
- - [ ]  <strike>the approved user should get the appropriate app_role in the user table (admin=`'industry_user_admin`, reporter=`industry_user`)</strike> -
- - [x] the user_operator record for that user should have status=Statuses.APPROVED
- [ ] ~~IF we aren't using user_operator.role anywhere, we can delete this column (to avoid role and permission confusion). When determining which user role to show in the table, industry_user=reporter and industry_user_admin=admin~~
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by Dianadec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Moose-Sprint-Board-60d216175a2689000ec774d0/issues/bcgov/cas-registration/470?planning-poker) with Zenhub @andrea-williams @BCerki @dleard @marcellmueller @Sepehr-Sobhani @shon-button

**Comment by andrea-williams** [comment]
Updates:

- we're pressing pause on this user story - external users won't need to assign different roles within an Operator until post-MVP. For MVP, all external users will have "admin" rights on their Operator (although it won't be called "admin", but that's a separate ticket)
- not captured in the wireframes at this time, but desired: when an external user makes a change to the selected role in the dropdown, there should be a modal asking them to confirm their choice to change the assigned role for a user.

**Comment by andrea-williams** [comment]
Code has partially been implemented in branch [feat/assign-ext-user-roles/470](https://github.com/bcgov/cas-registration/tree/feat/assign-ext-user-roles/470). Still needs confirmation modal; there's an error parsing JSON in the dropdown's change handler to submit the changes.

**Comment by hannavovk** [comment]
Looking good! Thanks @marcellmueller
