### ISSUE TITLE
CRA business number should only allow numeric input [3]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#472]
Describe the Bug:
Users shouldn't be able to type letters into the business number field on the multiple operations form.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEdBQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3386cf5c142e56ba321fed05502be183fc56fc28/image.png" alt="image.png" />
And the error message is wrong: <img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEtBQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8699c79f5309bb97498e64c1d85ad1bb82413ebd/image.png" alt="image.png" />

Probably we're just missing a type or format in the form json schema.

Probability (how likely the bug is to happen, scored from 1-5): 1
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by marcellmueller** [comment]
I can't seem to be able to reproduce this. The field has `type=number` and will only let me type numbers in the field in the Multiple Operators section. Would love if someone else would confirm or deny this for me thanks.

**Comment by Sepehr-Sobhani** [comment]
I can type characters but it doesn't let me submit the form:


![Image](https://github.com/bcgov/cas-registration/assets/52381975/47761702-7833-4b18-897a-d077cbcd0ce4)

**Comment by BCerki** [comment]
Should be fixed by https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=cra&pane=issue&itemId=54181386

**Comment by nanyangpro** [comment]
Fixed. Closing as discussed during refinement.
