### ISSUE TITLE
Update Operations Form Language and Blurb

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-registration#473]
#### Describe the task

Need to:

Add a blurb above the "additional operators" section to explain more about what that means. [Need wording and design]

Also, change the language which currently says Operator 1, Operator 2, to something like "Additional Operator Information". (see wireframe)

#### Acceptance Criteria

- [x] Update [wireframe](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2669-4745&mode=design&t=ghOnDGBTVOwjISCR-4)
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by Dianadec** [comment]
@nanyangpro  and @hannavovk  this was the one during the backlog refinement walkthrough that will need some wording changes. cc @patriciarussellCAS

**Comment by nanyangpro** [comment]
Thanks @Dianadec! The wireframe has been updated as discussed with @hannavovk. This ticket can be turned into a dev task once refined.

**Comment by BCerki** [comment]
Covered by other tickets, closing
