### ISSUE TITLE
Update User Operator endpoints to use Django ninja/pydantic for data processing

### ISSUE THREAD

**Issue by JoshLarouche** [bcgov/cas-registration#479]
###Description of the Tech Debt###

The user-operator endpoints update-status endpoints need to be updated to process data in a similar way to the other endpoints in a more django ninja/pydantic style.

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring: 1

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |    low   |  1     | 
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |    low   |  1     |
| System Fault Risk - Risk of system errors or application downtime                                                             |   low    |   1    | 
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |   low    |  1     | 
| Time Sink Risk - How much will this tech debt slow the development process down                                               |   low    |   1    | 
| TOTAL SCORE:                                                                                                                  |   low    |   5    | 5

**Comment by Sepehr-Sobhani** [comment]
Addressed in: https://github.com/bcgov/cas-registration/pull/613
