### ISSUE TITLE
Add Business BCeID to Operators Access Requests table

### ISSUE THREAD

**Issue by JoshLarouche** [bcgov/cas-registration#480]
###Description of the Tech Debt###

A Business BCeID column needs to be added to the Operators Access Requests table.
Note: This field may be redundant, confirm it is still wanted before implementation

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring: 1

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |   medium    |   2    |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |  low     | 1      |
| System Fault Risk - Risk of system errors or application downtime                                                             |    low   |    1   |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |  low     |    1   |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |  low     |  1     |
| TOTAL SCORE:                                                                                                                  |    low   |  6     |

**Comment by nanyangpro** [comment]
Re: Refinement discussion - High-impact, low-effort, but doesn't block the prod release.

**Comment by andrea-williams** [comment]
This would be the `bceid_business_name` field on the `User` table - i.e., a string representation of the business's name. It should be getting pulled from Keycloak

**Comment by nanyangpro** [comment]
@dleard - In the page, but not in the table. Easy to do.

**Comment by BCerki** [comment]
@nanyangpro , do these column names look OK? For some extra clarity, I went loose cannon and changed them slightly from Figma

![Image](https://github.com/bcgov/cas-registration/assets/77306764/0a224e6a-7549-4b57-80a2-8df93973defa)

**Comment by nanyangpro** [comment]
Looks great to me, thanks @BCerki!

Just to confirm, the "Request ID" column is out of scope of the discussion here and will be taken care of in another ticket, correct?

**Comment by BCerki** [comment]
> Looks great to me, thanks @BCerki!
> 
> Just to confirm, the "Request ID" column is out of scope of the discussion here and will be taken care of in another ticket, correct?

Yes, different ticket
