### ISSUE TITLE
Simplify user-operator API type conversion

### ISSUE THREAD

**Issue by JoshLarouche** [bcgov/cas-registration#482]
###Description of the Tech Debt###

Explore simplfying the type conversion below from the user-operator.py file. Carryover from getting ticket number 25 in.

`# need to convert request.body (a bytes object) to a string, and convert the string to a JSON object
    payload = json.loads(request.body.decode())
    status = getattr(UserOperator.Statuses, payload.get("status").upper())`

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     | 1

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |    low   |    1   |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |   low    | 1      |
| System Fault Risk - Risk of system errors or application downtime                                                             |  low     |   1    |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |   low    |  1     |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |  low     |     1  |
| TOTAL SCORE:                                                                                                                  |  low     |    5   |

**Comment by Sepehr-Sobhani** [comment]
Addressed as part of: https://github.com/bcgov/cas-registration/pull/613
