### ISSUE TITLE
Prime Admin Access Requests workflow UI changes

### ISSUE THREAD

**Issue by JoshLarouche** [bcgov/cas-registration#483]
###Description of the Tech Debt###

Recording the changes desired by @nanyangpro that came out of the workflow walkthrough of ticket [#25](https://app.zenhub.com/workspaces/team-moose-sprint-board-60d216175a2689000ec774d0/issues/gh/bcgov/cas-registration/25) as a result of trying to get in merged in before Christmas.

- [x] Confirm with Design team if request ID is still needed on the operators page and remove it if it is not
- [x] Explore keeping the user-operator details page still read-only but not greyed out for better readability
- [x] Remove cancel and submit buttons from user-operator details page rather than keeping them there but nonfunctional
- [ ] make approve and reject success messages permanent on the user-operator details page after the request has been approved or rejected

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     | 1

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |    medium   |   2    |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |   low    | 1      |
| System Fault Risk - Risk of system errors or application downtime                                                             |    low   |   1    |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |    low   |   1    |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |   low    |   1    |
| TOTAL SCORE:                                                                                                                  |  low     |    6   |

**Comment by BCerki** [comment]
@nanyangpro , I think all but possibly the last AC in this card is already done?

**Comment by nanyangpro** [comment]
Fixed. Closing as discussed during refinement.
