### ISSUE TITLE
Can't navigate to second page of operations form

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#486]
Describe the Bug:

When a user is viewing a pending operation, they can't get to the next page because the form fails validation on the website field:

https://www.loom.com/share/6c1606faae20483d9e24e7b6296f0783

Website should not be required, and the form is readonly and shouldn't be editable, so probably shouldn't be validated again after submission

Probability (how likely the bug is to happen, scored from 1-5):
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by BCerki** [comment]
This shoud be fixed by https://github.com/bcgov/cas-registration/issues/490

**Comment by marcellmueller** [comment]
Closing as this was fixed by #490
