### ISSUE TITLE
Request Access as Prime Admin when operator already exists is broken[8]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-registration#498]
Describe the Bug:
When an IO requests access as prime admin for an operator that already exists, we should only show the `User Information` part of the `UserOperator` multistep form with the email and phone number of the current user prepopulated. but currently, we are showing all user information which is not what we want. Here is the wireframe: https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2401-146&mode=design&t=v9FvQ3xSYYraC3xX-4

Probability (how likely the bug is to happen, scored from 1-5):5
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

**Comment by shon-button** [comment]
Adding in my observations:
Currently, when an IO attempts to "Request Access as Prim Admin" when operator exists client/app/components/routes/select-operator/form/UserOperator.tsx` calls function:

```
export async function getUserOperatorFormData(id: number | undefined) {
  if (!id) return {};
  return actionHandler(
    `registration/select-operator/user-operator/${id}`,
    "GET",
    `/user-operator/${id}`,
  );
}
```
which returns error:
<img width="683" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1NpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd88f7ae77b156ad0fcf255318abafefa6a48b12/image.png" alt="image.png" />
