### ISSUE TITLE
e2e test\workflow\bceidbusiness\industry_user

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#505]
#### Description:

Tests of `\bceidbusiness\industry_user` [workflow](https://miro.com/app/board/uXjVN6uBj9Y=/)

**Page by Roles Tests**
- [x] Cannot navigated to restricted app routes (**NOTE:** tested in `client/e2e/pages/authenticated/routes/page.spec.ts`)
- [x] Login redirected to Dashboard page (**NOTE:** tested in `client/e2e/pages/onboarding/home/page.spec.ts`)
- [x] Profile page submit required data (**NOTE:** tested in `client/e2e/pages/authenticated/dashboard/profile/page.spec.ts`)
- [x] Dashboard design:  "Select Operator" and "Report a Problem" (**NOTE:** tested in `client/e2e/pages/authenticated/dashboard/page.spec.ts`)

**WIP**
**Tests using storageState for `industry_user`:**
- [ ] assert "My Operator\create new Operator"
- [ ] is able to search for their operator by operator legal name (fuzzy search) or CRA business number (exact matches only), or has the option of adding a new operator
- [ ] is able to select an operator from the search results and sees operator preview, with options to go back to the search screen, or confirm "Yes this is my operator"
- [ ] once they've selected their operator from the search and confirmed "Yes this is my operator", there's 2 scenarios:
            - [ ] no other user has requested admin access for the operator, in which case industry_user should be prompted whether they want to request to be admin
            - [ ] some other user has already requested admin access for the same operator, in which case the industry_user can request access to the Operator, but they won't automatically be the admin for the operator
- [ ] is able to create a new operator from the Select Operator page, and populate all form fields, with different scenarios:
            - [ ] operator has no parent company
            - [ ] operator has 1 parent company
            - [ ] operator has multiple parent companies 

Once industry_user has status = 'Approved' in user_operator table, see checklist in `industry_user_admin` ticket

**Comment by BCerki** [comment]
NOTE: re this AC, chatted with the reviewer and only did one test that has multiple parent companies (repetitive and slows CI to do all three versions), but if accepted reviewer requests three separate ones, I will change
is able to create a new operator from the Select Operator page, and populate all form fields, with different scenarios:
- [ ] operator has no parent company
- [ ] operator has 1 parent company
- [ ] operator has multiple parent companies
