### ISSUE TITLE
GET error if user has more than one operator [6]

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#511]
Describe the Bug:

There is an issue with our `GET` request for the operator page if there is more than one operator associated with that user. This should b less of an issue when #441 gets merged as users won't be shown the `select operator` page once they have submitted the form though I believe it will be an issue if their form is `Rejected` and they create a new one.

<img width="728" alt="Screenshot 2024-01-08 at 8 41 35 AM" src="https://github.com/bcgov/cas-registration/assets/14259474/93abe197-f108-487d-9b02-e7c71c8970e7">

From a discussion on teams it would be good to check if the user is associated with any operators when submitting the user operator form for the first time. We also might need to filter out ones with `Rejected` status as in the future they will be able to submit another application.

Probability (how likely the bug is to happen, scored from 1-5): 3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by BCerki** [comment]
I talked to Dylan about this one (and the one that's related) and it's okay to add a db constraint to ensure users can't be associated with more than one operator

**Comment by BCerki** [comment]
#554  is related

**Comment by BCerki** [comment]
This should be fixed by: https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=53044195
