### ISSUE TITLE
Subsequent user access request confirmation page shows a server error [6]

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#543]
Describe the Bug:

When a subsequent user requests access to an operator that already has an admin, after requesting access the confirmation page shows a server error. The request does however go through and the access request is created properly in the database.

<img width="1127" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFczQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca1e548a05d8ed977083e9ec25d944dcb410ff62/Screenshot%20from%202024-01-10%2015-32-06.png" alt="Screenshot from 2024-01-10 15-32-06.png" />

Probability (how likely the bug is to happen, scored from 1-5): 3

Effect (how bad the bug is when it does happen, scored from 1-5): 3

Steps to reproduce the behaviour:
- As an IO user request access to an operator that already has an approved admin
- See the server error at the end of the workflow

**Comment by dleard** [comment]
@Sepehr-Sobhani I feel like this is maybe related to something you've brought up recently about an endpoint being called unnecessarily?

**Comment by Sepehr-Sobhani** [comment]
Yes that was addressed in: https://github.com/bcgov/cas-registration/pull/516
By any chance, do you have server logs?

**Comment by dleard** [comment]
I manually deployed the head of develop today, so it should have been in there.
Here are the logs when I made the request:
<img width="880" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHUzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--546380de764e8b5a60874a5751ea841034f0bdbb/Screenshot%20from%202024-01-10%2015-43-46.png" alt="Screenshot from 2024-01-10 15-43-46.png" />

**Comment by Sepehr-Sobhani** [comment]
Do I have a cache or something on my shipit?

<img width="1245" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODIzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--03cce1c53557d7f6ef41d0158eca7bf214cd20cf/Screenshot%202024-01-10%20at%203.49.22%E2%80%AFPM.png" alt="Screenshot 2024-01-10 at 3.49.22 PM.png" />

**Comment by Sepehr-Sobhani** [comment]
Sorry, you mentioned manually.
I don't see any errors on logs though :/

**Comment by Sepehr-Sobhani** [comment]
I tried this locally and couldn't replicate the error, I'm confused.

**Comment by dleard** [comment]
I will try it again in dev

**Comment by dleard** [comment]
Huh, I didn't get the error this time. May have just been a 'blip'. I'll close this card for now, but it's a workflow to keep an eye on as we're QA'ing things
