### ISSUE TITLE
Hide document upload fields

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#555]
#### Describe the task

Since we aren't going to prod with document uploads we need to comment out those fields in the `User Operator` and `Operations` forms.

#### Acceptance Criteria

- [ ] Comment out document upload fields in `User Operator` form
- [ ] Comment out document upload fields in `Operations` form
- [ ] Ensure both form create/update functionality works without errors due to missing fields

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by BCerki** [comment]
This is probably going to be covered by #598 and #612

**Comment by andrea-williams** [comment]
Closing - already completed in other tickets.
