### ISSUE TITLE
As an IO, I want to be able to edit an operation (facility) registration form I already submitted so that I can add the information needed

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-registration#57]

**Comment by Dianadec** [comment]
@NicoleGovvy  I didn't see this epic in the user story map but maybe I am blind

**Comment by NicoleGovvy** [comment]
@Dianadec took a look and I seem to have created a duplicate - #84. I think the Epic wasn't numbered in the second story map so I created the second one.
