### ISSUE TITLE
Approve Operator when granting BORO ID

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#584]
#### Describe the task

When an internal user approves an Operation's request for a BORO ID
If the associated Operator has a status other than "Approved"
Then the Operator's status should be set to Approved when the BORO ID request is Approved

#### Acceptance Criteria

- [x] the Operator should implicitly be "Approved" (if not already Approved) when an Operation tied to the Operator is approved for a BORO ID. The Operator status should be changed to "Approved", and the relevant audit columns (such as verified_at and verified_by) should also be set
- [x] if the Operator's status is already "Approved" when the Operation's gets approved, no changes to the Operator should be performed (i.e., don't update anything in the Operator DB record)

#### Additional context

- external users will be able to request a BORO ID for their new or existing Operation without an "Approved" Operator if their Operator data was imported from CIIP/SWRS
- if the Operator was newly created (i.e., not imported), the Operator's status will already be set to "Approved" at the time that an external user is requesting a BORO ID for an Operation. In this case, no changes need to be made to the Operator's status when creating a BORO ID
- blocked until the fix for #656 is merged in

**Comment by andrea-williams** [comment]
IMO there's no additional info required in the card, but I may be biased since I wrote it :) I don't think we got around to discussing this ticket in any refinement/planning sessions, so other devs may have questions about it.

**Comment by Sepehr-Sobhani** [comment]
@andrea-williams Should we also set the `is_new` flag to False on the operator?

**Comment by andrea-williams** [comment]
> @andrea-williams Should we also set the `is_new` flag to False on the operator?

unless there's some edge case I'm not thinking of, the only workflow where an Operator might not be Approved when an Operation is pending approval would be when the Operator data has been imported, so the `is_new` flag on the Operator would always be False in that scenario.

**Comment by Sepehr-Sobhani** [comment]
> > @andrea-williams Should we also set the `is_new` flag to False on the operator?
> 
> unless there's some edge case I'm not thinking of, the only workflow where an Operator might not be Approved when an Operation is pending approval would be when the Operator data has been imported, so the `is_new` flag on the Operator would always be False in that scenario.

Thanks Andrea! I'm going to mark it as False again, just in case!
