### ISSUE TITLE
Revise Operator Form

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-registration#598]
#### Describe the task

AC:

1. Move parent company question in Operator Information table
- In the My Operator (Operator Information) table, the Question with radio buttons asking parent company information "Does the operator have a parent company" needs to be moved to the bottom of the Operator Information section.
- See wireframe: https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2401%3A331&mode=design&t=brhPkfT4W4RpuEjA-1

2. Remove 'Percentage of ownership of operator' field from the Operator Information Form. 
- Here's the wireframe to show this field. https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=3422%3A3161&mode=design&t=59ovTuKFm0Whkcg5-1
See below for the wireframe of what the design should look like without the field.
- Under 'Parent Company Information', we no longer need this field.
It should look like this: https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2401%3A331&mode=design&t=18BwAF7yEAoBZUZy-1

3. Remove fields in flow within 'If Operator Data does NOT exist', Operator Information form:
- remove field 'percentage of owner as operator' under Parent Company Information
- https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2615%3A3283&mode=design&t=vNEAKgcCX2f1IfPT-1

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by Dianadec** [comment]
@nanyangpro  did I capture the info here correctly? cc @hannavovk

**Comment by Dianadec** [comment]
@nanyangpro  I've combined the 'Operator Form' tasks into this one ticket. Please review :). (I closed #601 and #611)

**Comment by BCerki** [comment]
Blocked on broken Add Operator/Select Operator workflow

**Comment by nanyangpro** [comment]
Great call, @BCerki!
I double-checked in DEV. You are right, all the AC in this ticket are already checked off. Feel free to close this ticket or send it for PO approval.
