### ISSUE TITLE
User Story: CAS admin able to sort Organization access requests

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-registration#60]
#### Description:

As a CAS admin, I want to see a list of organization prime admin access requests so that I can approve or deny them

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by hannavovk** [comment]
This is about Operation registration approval. No overlap with #25, but could potentially be overlap with #97. 
Sorting would be by Operator, Operation, date submitted, approval status, etc - i.e. sorting within the columns.

**Comment by hannavovk** [comment]
Yes, likely overlap with #25. This is sorting by things like first name, last name, operator, etc. - i.e. the column headers.

**Comment by BCerki** [comment]
We're building a component in #26 that does sorting, so if we use that when building the organization page, this ticket may not be necessary

**Comment by Dianadec** [comment]
Reiterated during refinement today: May be covered by material UI components since it covers sorting.
