### ISSUE TITLE
Revise User Information External forms and screens

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-registration#600]
#### Describe the task

When user is requesting access they don't need any additional screens; Senior Officer info is gone and document uploads are gone.

AC: 
1. Delete "View Submitted information" screen and button
- Delete the "View submitted information" screen since we aren't showing any info to the user here
- Delete the "View submitted information" button from the previous screen since it contains the status message and the "Cancel request" link already
https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=3422%3A3978&mode=design&t=2vDxSPwFZJnCU2rl-1

2. Edit User Information screen and remove fields so that it shows the same fields as the first 'verify user information' page. 
Fields to include: First name, last name, email address, phone number, position title. See wireframe: https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=5311%3A316&mode=design&t=zhKSCwFBop5Kd07j-1

#### Additional context

- Add any other context about the task here.
- Or here
- 
Will have merge conflicts with https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=50188659 so blocking

**Comment by Dianadec** [comment]
@nanyangpro  for your review. cc @hannavovk

**Comment by nanyangpro** [comment]
Thanks @Dianadec!

Re: Your comment in Teams 
> [2:48 PM] De Cotiis, Diana WLRS:EX
Quick summary is that we need to keep the User Information screens but only show the info that was collected from the verify/update info page. Too much work to remove those pages completely.

I presume the ticket description would be revised accordingly, correct?

**Comment by Dianadec** [comment]
Correct @nanyangpro - this tickets need editing.

**Comment by Dianadec** [comment]
@nanyangpro this ticket has now been updated for your review (and @hannavovk )

**Comment by hannavovk** [comment]
Looks great! thanks @BCerki
