### ISSUE TITLE
Revise Operation Form

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-registration#612]
#### Describe the task

AC:

1. Remove Reporting Activities, Process Flow Diagram, and Boundary Map fields from Operation Form

- Removing fields as shown here: https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=3422%3A2265&mode=design&t=9gY7L4rgyithbn3W-1

- so the updated screen should look like this:
https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2669%3A4745&mode=design&t=9gY7L4rgyithbn3W-1

2. Under 'Please provide information about the GHG emissions...", 
- Remove 2022 Attributable Emissions Field
- Remove SWRS Facility ID
- BCGHG ID should be prepopulated.
- if they select 'no' to "Did you submit a GHG emissions report for reporting year 2022?", they should NOT be able to fill out/edit their BCGHG ID.
Wireframe: https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2669%3A4745&mode=design&t=vNEAKgcCX2f1IfPT-1

3. Opt-in Information
- delete document upload for Opt-in Signed Statutory Declaration

5. HIDE Multiple Operators information section
-  (may be needed in the future), including the "Does the operation have multiple operators?" radio buttons.
- Wireframe: https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2669%3A4745&mode=design&t=vNEAKgcCX2f1IfPT-1

4. Point of Contact
- Remove fields: Mailing address, municipality, province and postal code.
https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2669%3A5433&mode=design&t=vNEAKgcCX2f1IfPT-1

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by BCerki** [comment]
Note: related ticket https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=operation&pane=issue&itemId=50447776
