### ISSUE TITLE
Text changes in breadcrumbs

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#615]
#### Describe the task

Some text changes in the SME figma comments affect breadcrumbs. 

Nan: If we change wording in the tiles, we should change them in the breadcrumbs.

#### Acceptance Criteria

- [ ] Label dynamic routes in User Operator form. Once a user submits the form they get sent to a different route using `operator_id` so it changes and could be confusing.
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by BCerki** [comment]
https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=1000&pane=issue&itemId=54970425 will probably replace this

**Comment by nanyangpro** [comment]
Breadcrumbs will be updated according to the latest designs for Reg Pt. II later. Closing.
