### ISSUE TITLE
Add missing text (headers and instructions) to Operator form

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#622]
#### Describe the task

The Operator Form has multiple sections (e.g. "Operator Information") and notes (e.g. "Please provide information about the physical address of the operator") explaining how to fill them out. This tech debt ticket is to look at using the GroupedObjectFieldTemplate for creating the sections  instead of making fake fields in the rjsf schema (but beware possible performance issues) 

Wireframe with latest text: https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2615-3283&mode=design&t=hOiAVHiwgwSC7eBe-0

#### Acceptance Criteria

- [ ] refactor form if there are no performance issues

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by BCerki** [comment]
This was likely already done as part of other Operator form tickets

**Comment by marcellmueller** [comment]
Closing as this was fixed in another issue.
