### ISSUE TITLE
Demo for Webinar for Industry

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-registration#633]
#### Describe the task

On ~February 14~ (UPDATE: MARCH 5), there will be an industry webinar about BCIERS and OBPS. The DST Team will need to provide a demo of the app for the industry user audience.

#### Acceptance Criteria

- [x] Create slides to add to the Webinar slide deck (Diana to-do)
- [ ] Create internal demo plan for DST to prep for the demo (short version)
- [ ] Setup Demo prep meeting with devs involved. Andrea providing demo
- [ ] Create demo recording using Loom
- [ ] Update dummy data to avoid using "FakeFacility" wording
- [ ] what else

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by Dianadec** [comment]
Slide deck: https://bcgov.sharepoint.com/:p:/r/teams/06817/_layouts/15/Doc.aspx?sourcedoc=%7B43702315-2FB6-4451-8FBB-E42ED8BB5522%7D&file=DECK_OBPS%20Webinar%202024%20Feb.pptx&action=edit&mobileredirect=true

**Comment by nanyangpro** [comment]
Maral: The webinar might be postponed further, i.e., post Jan 20th. (Hopefully Mar 5th, we'll be updated next week. :)

**Comment by nanyangpro** [comment]
Re: stand-up, for @andrea-williams - Fyi, @dleard worked on the recordings while you are away. :)
