### ISSUE TITLE
User Operator Contact page error

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#640]
Describe the Bug:

If the User Operator Contact page is filled out without checking the Senior Officer box then the form can't be submitted. There is a backend validation error about missing email field:

<img width="723" alt="Screenshot 2024-01-19 at 9 13 54 AM" src="https://github.com/bcgov/cas-registration/assets/14259474/2418acb2-a73d-4b30-934d-9d94192c5889">

Probability (how likely the bug is to happen, scored from 1-5): 3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 4
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by Sepehr-Sobhani** [comment]
Addressed in: https://github.com/bcgov/cas-registration/pull/613
