### ISSUE TITLE
Rename "User Access" to "Access Type" in user table

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#641]
#### Describe the task

Per guidance from IRC, we want to rename the column title from "User Access" to "Access Type"

https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2719%3A15135&mode=design&t=1lXTaoAGvoNAKc2T-1

#### Acceptance Criteria

- [x] In the User table, rename the column title from "User Access" to "Access Type"

#### Additional context

- For MVP, the "reporter" UserOperator.Role is not needed.
- Refer to https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8?node-id=2719:15135&mode=design#674914864 for context
- note that this is separate to the app_roles DB model

**Comment by Dianadec** [comment]
Split out AC into multiple:
- front-end: represented as Operation Representative
- database: operation_representative
- add explanatory comment on database table to explain what Operation Representative is
cc @andrea-williams

**Comment by Dianadec** [comment]
As per a meeting with IRC today, we no longer need to Rename "admin" role as "Operation Representative". Instead, the solution is to rename the column title to "Access Type". cc @hannavovk
