### ISSUE TITLE
Add link to template download in Statutory Declaration field and update text

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#645]
#### Describe the task

We need to add a URL to the template download in the title for the `statutory_declaration` field. We are waiting on a link to this so  it couldn't be completed in #604. 

The field is using a custom title which was completed but mostly commented out in #604. 

We also need to update the text.

#### Acceptance Criteria

- [x] Uncomment custom title `StatutoryDeclarationUploadFieldTitle` in `operationsTitles.tsx`
- [x] Add template download URL
- [x] Update the languages on this page to align with the finalized [design](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=4903-986&mode=design&t=dR8i3chC0bQOTIKO-4)

**Comment by Dianadec** [comment]
Once we have the info, we can bring into the "Isolated Simple Tasks"

**Comment by nanyangpro** [comment]
The copy is updated in the design as advised by IRC.

We are still waiting for the template URL, this blocker has been brought to @Maralsotoudehnia's attention. Once we get the URL, I'll include it in the design and inform the developers for implementation.

**Comment by nanyangpro** [comment]
We got the links, this ticket is unblocked now! :)
