### ISSUE TITLE
Point of contact (previously called external application lead) checkbox is backwards

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#649]
This is part bug, part task, because there is a bug but the workflow has also changed, so while fixing the bug we may as well fix the workflow.

On the operations form, when we ask if the user wants to add a point of contact (previously called exemption lead), if they click yes, the form pre-fills with their user information (bug)

It should actually work like this (task):

- "No" is the default selection.
- When "No" is selected, instead of displaying the form, we show this message "You will be the point of contact of the B.C. OBPS Regulated Operation ID application."
- If the user selects "yes," then they see a blank form

**Comment by andrea-williams** [comment]
This can probably be closed - I "accidentally" fixed it in another ticket because this bug was a blocker for my work.
