### ISSUE TITLE
Create Current Registration App Workflow Diagram

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-registration#657]
#### Describe the task

Based on the retrospective discussion, the team identified that it would be helpful to have a diagram reflecting the workflows of the registration app.

See Andrea's miro board as an example: https://miro.com/app/board/uXjVN6uBj9Y=/

The diagram would be used
- for internal dev/design communications
- for collaboration with Giraffe
- as a reference for scoping out what should be in Registration Part II
- to aid in identifying missing workflows and user stories

#### Acceptance Criteria

- [x] Review Andrea's example, and check on the developers' expectations
- [x] Review the previous work in progress by Hanna and Suha
- [x] Review Zoey's SWRS Admin module workflow diagram, and ask for the service designers' suggestions
- [x] Create the diagram to reflect the current user workflows in the Registration app
- [x] Share with Zoey for peer review to unblock her work on #854
- [x] Share with the team and address the feedback

#### Additional context

- Related to #802

**Comment by Dianadec** [comment]
@nanyangpro / @hannavovk could you fill in the AC for this one?

**Comment by nanyangpro** [comment]
No problem, @Dianadec! I've added in AC and additional context. Feel free to refine it further as you see fit, @hannavovk!

**Comment by nanyangpro** [comment]
Hi @Maralsotoudehnia (cc: @hannavovk) - This ticket is ready for you to review and can be closed with:
- The [Current Registration Part I Workflow Diagram (MVP)](https://miro.com/app/board/uXjVNtgEVCs=/?moveToWidget=3458764578941329551&cot=14) created and shared for feedback
- The questions answered in the above board
- The feedback/suggestions/corrections addressed in the above board

Next step: Start 868 to draft Envisioned Registration Part II Workflow Diagram based on the identified requirements from 854

**Comment by hannavovk** [comment]
Awesome work! Thanks @nanyangpro
