### ISSUE TITLE
Dashboard > Select Operator > Undefined

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#683]
Describe the Bug:
Given I am logged in to the Registration app with Business BCeID account Cas Secondary
When I navigate to the `Select Operator`
Then I see the Operator Information form with ID `undefined`

![image](https://github.com/bcgov/cas-registration/assets/120038448/548c83c8-3c98-43e3-a3a3-24d6daf157ba)

Probability (how likely the bug is to happen, scored from 1-5):
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by marcellmueller** [comment]
Thanks Shon 🙇 Really appreciate this and am almost finished fixing it. Just to clarify that `Cas secondary` has a `User Operator` with `Pending` status so being redirected is correct even if that is currently broken for this user.

`bc-cas-dev-three` is the one to use to select an operator once I have fixed this bug I've introduced.
