### ISSUE TITLE
Refine wireframes for the Registration app with business area input

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-registration#69]
#### Describe the task
We demoed the wireframes for the Registration app to the business area. However, since they were created based on certain assumptions and there are still places where we need more clarity. We need to have further discussions with the business area and refine the wireframes based on their input.

#### Acceptance Criteria

- [x] Offer access to the interactive prototypes for async feedback from the business area
- [x] Identify places where we need more clarity and design decisions pending further input from the business area
- [x] Identify relevant attendees from business area (in addition to the SMEs) and schedule discussion(s).
- [x] Refine wireframes based on the input gathered

**Comment by nanyangpro** [comment]
Hi Hanna - This ticket is ready for you to review and can be closed with the designs updated based on the input gathered so far:
- [Key Screens Overview: Internal app & External app](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/Registration-app?page-id=4%3A2&type=design&node-id=5-6&viewport=365%2C284%2C0.29&t=h5wlKnr8rRvS46J2-1&scaling=scale-down&starting-point-node-id=5%3A6&show-proto-sidebar=1&mode=design)
- [Workflow 1: Request Admin Access to Org from CG](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/Registration-app?page-id=4%3A2&type=design&node-id=50-3570&viewport=365%2C284%2C0.29&t=h5wlKnr8rRvS46J2-1&scaling=scale-down&starting-point-node-id=50%3A3570&show-proto-sidebar=1&mode=design)
- [Workflow 2: Request Access to Org](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/Registration-app?page-id=4%3A2&type=design&node-id=50-3694&viewport=365%2C284%2C0.29&t=h5wlKnr8rRvS46J2-1&scaling=scale-down&starting-point-node-id=50%3A3694&show-proto-sidebar=1&mode=design)

Please note that the data fields in the design (e.g. Operation Registration form, Operator Admin Access Request form, etc.) don't reflect business area consensus yet. Our proposal were shared with SMEs as spreadsheets for further validation/refinement with the business area (Re: #33). As for now, we are still waiting on the finalized version.

**Comment by hannavovk** [comment]
Amazing work! Thanks @nanyangpro
