### ISSUE TITLE
Incorporate features/workflows regarding the carbon tax exemption into the design

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-registration#70]
#### Describe the task

Jessica N. brought up the need for having the features/workflows regarding the carbon tax exemption into the Registration app design. We want to visualize our vision towards it first and iterate with feedback/decisions from the business area.

The business area is leading the communications with FIN. Hanna suggested we confirm with the business area if we should show the design with FIN (indicate that we can support in the comms).

#### Acceptance Criteria

- [x] Create wireframes for the features/workflows regarding carbon tax exemption in Figma
- [x] Get input from the business area
- [x] Refine design based on the input gathered

**Comment by nanyangpro** [comment]
Hi Hanna - This ticket is ready for you to review and can be closed.
- As a first draft, the "Download Carbon Tax Exemption" button is added to both ["Operations" page](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/Registration-app?type=design&node-id=19-2197&mode=design&t=B2V1pfiMHUFESS3X-4) and each ["Operation Details" page](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/Registration-app?type=design&node-id=89-5110&mode=design&t=B2V1pfiMHUFESS3X-4):
    - The button is supposed to link to a PDF file generated and hosted by FIN
    - On the **"Operations" page**: the PDF is generated on the Operator level, listing all its Operations' status towards carbon tax exemption
    - On each **"Operation Details" page**: the PDF is generated on the Operation level indicating exemption from carbon tax
- As a next step, we want to confirm the feasibility of our proposal, ideally show the design with FIN. This requires support from the business area.

**Comment by hannavovk** [comment]
Thanks @nanyangpro
