### ISSUE TITLE
Create a Metabase Alert

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-registration#704]
#### Describe the task

A clear and concise description of what the task is.

#### Acceptance Criteria

- [ ] Find out who should be on th elist to get the alert (
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by dleard** [comment]
I've created two alerts in the Alerts channel in metabase prod. Leaving this in dev review in case someone wants to go check my SQL
