### ISSUE TITLE
When Operation status is Approved, edits to Operation data should not reset the Operation's status

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#706]
#### Describe the task

Current behaviour: when an external user updates any data fields for an already-Approved Operation, on Submit to our API, the status of that Operation is reset to "Pending". However, since the Operation was previously approved, it will still have an active BORO ID associated with it. This is pretty confusing for everyone.

Desired behaviour: when an external user updates any data fields for an already-Approved Operation, on Submit to our API, the status of that Operation should remain as it is (i.e., "Approved").

#### Acceptance Criteria

- [x] modify logic in our API on the PUT "/operations/{operation_id}" endpoint so that if the operation's status is already "Approved", the status remains unchanged 
- [x] PUT requests sent to "/operations/{operation_id}" should still trigger changes on the `updated_at` and `updated_by_id` columns in the Operation table
- [x] add a backend unit test confirming this desired behaviour

#### Additional context

- in another ticket, we'll be setting up Metabase to trigger notifications to internal staff whenever data about an approved Operation is updated. See #704

**Comment by Dianadec** [comment]
Needed for MVP.
