### ISSUE TITLE
DST Git strategy documentation

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#743]
We should have some discoverable and well defined documentation on our git strategy for the DST team. We've been unclear on how we use conventional commits, rebasing, branching strategy / nomenclature and preference for a linear git history which has been hard on new developers onboarding to the team.

**Comment by pbastia** [comment]
Tagging @joshgamache for Graphite

**Comment by hannavovk** [comment]
Thanks @dleard! Closing this out
