### ISSUE TITLE
Determine if the statutory declaration should be hard deleted

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#746]
#### Describe the task

Currently, we hard delete old statutory declarations from the db and GCS. Is this what we want?

#### Acceptance Criteria

- [x] Get decision of yes or no
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by BCerki** [comment]
@dleard (cc @Dianadec in case you were making a ticket too)

**Comment by Dianadec** [comment]
@hannavovk

**Comment by Dianadec** [comment]
Yes, hard deleted is the way.
