### ISSUE TITLE
Copy/Language Updates Impacted by #641

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-registration#748]
Impacted by #641 (update "User Role" to "Access Type" in the external "Users" table), additional copy updates are required on the following screens:

- [Screen 1](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2403-632&mode=design&t=M6fDYE2TCClt3dDZ-4)
- [Screen 2](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2407-1186&mode=design&t=M6fDYE2TCClt3dDZ-4)
- [Screen 3](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2615-3544&mode=design&t=M6fDYE2TCClt3dDZ-4)
- [Screen 4](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2615-3828&mode=design&t=M6fDYE2TCClt3dDZ-4)
- [Screen 5](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=2621-3889&mode=design&t=M6fDYE2TCClt3dDZ-4)

Please update copy in these screens according to the latest design linked above.

**Comment by BCerki** [comment]
@nanyangpro , will you want to look at this before it goes to PO review?

**Comment by nanyangpro** [comment]
Thanks for confirming, @BCerki!
The change requests in this ticket are straightforward and hard to be missed. Feel free to skip me and send it to PO review and approval. :)
