### ISSUE TITLE
CAS admin requests changes to IO's submission 

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-registration#75]
#### Description:

As a CAS admin, I want to be able to REQUEST CHANGES for an application from the IO if needed so that I can get the information I need to approve/reject it

#### Acceptance Criteria:

Given I have logged in with my IDIR and have appropriate internal permissions
When I click the "Request Changes" button for an application
Then I'm asked to confirm that I want to Request Changes
  - If I confirm, then the application's status changes to "Changes Requested"
     And the application's form fields are editable by the IO
  - Else if I cancel the Change Request, nothing happens

Given I have logged in with my IDIR and have appropriate internal permissions
And changes have been requested for an application
When I click the button to revert the Change Request
Then I'm asked to confirm that I want to revert the Change Request
   - If I confirm, then the application's status changes to "Pending"
     And the application's form fields are not editable by the IO
   - Else if I cancel the revert, no changes are made

Given I have logged in with my Business BCeID
If my operation has a status of "Changes Requested"
Then I can see that status in my list of operations
And I'm able (if I have the right permissions) to edit my application's form fields

#### Development Checklist:

- [ ] Matches wireframes: https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=1341%3A3929&mode=design&t=ld0UMfrRW3ROyfOv-1
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by hannavovk** [comment]
#62 and #75 seem like the same feature

**Comment by andrea-williams** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Moose-Sprint-Board-60d216175a2689000ec774d0/issues/bcgov/cas-registration/75?planning-poker) with Zenhub @andrea-williams @dleard @joshgamache @JoshLarouche @Sepehr-Sobhani @marcellmueller @shon-button

**Comment by andrea-williams** [comment]
Closing - work was completed in a duplicate ticket.
