### ISSUE TITLE
Operation form can get into an undefined state [5]

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#752]
Probability: 2
Effect: 3

There is a path when registering an operation where the form can get into an undefined state and become uneditable preventing the user from getting any further. If there is an error with the creation of the declaration attachment object, we get into a state where the document was not created, but the operation is in pending and therefore the user cannot make any further changes (ie: attempt the upload again).

I've attached a screenshot of where the issue can occur.
When we call operation.save(), it changes the status to 'Pending' (and we block edits on pending operations)
Because the Document.object.create() call comes after the operation.save() call, if there is an issue with that document creation, this is where we can get into our undefined state where: an operator exists and is in the "Pending" state, but no declaration document was created and the user cannot attempt another document upload/creation and cannot get past the document upload page.

![Image](https://github.com/bcgov/cas-registration/assets/26367840/4a64a689-edc7-4680-9a07-f9c52b466940)

Addition: this card should also add atomic to all the endpoints, not just the operations one, because this bug could happen anywhere

**Comment by dleard** [comment]
@Sepehr-Sobhani  tagging you here because you had a good idea on how to solve this issue when we discovered it

**Comment by Sepehr-Sobhani** [comment]
When we have API endpoints that handle multiple tasks and save different objects all at once, like in our scenario where various objects are saved within a single function, it's crucial to ensure the atomicity of these operations. In Django, the default behaviour is to run in `autocommit` mode, where each query is immediately committed to the database unless a transaction is active. However, we often need to go beyond `autocommit` in situations like updating or creating an `Operation` or `Operator`.

To achieve the desired level of control, we can use Django's atomic decorator or context manager. In our specific case, take the example of the `save_operator` function in the `user_operator.py` file. By applying the atomic decorator or context manager to this function, we treat the entire function as a single transaction. So, if at any point during the execution, something goes wrong, like an error occurs while saving addresses, the entire transaction is rolled back. This means that any changes made so far, including the creation of addresses, will be undone, maintaining the consistency of our database.

For a deeper dive into this concept and understanding the default `autocommit` behaviour, we can check out Django's documentation on `autocommit` and atomic transactions [here](https://docs.djangoproject.com/en/5.0/topics/db/transactions/#django-s-default-transaction-behavior) and [here](https://docs.djangoproject.com/en/5.0/topics/db/transactions/#django.db.transaction.atomic)

**Comment by andrea-williams** [comment]
Excellent idea @Sepehr-Sobhani
