### ISSUE TITLE
Session component show "loading" on home page [6]

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#797]
**Describe the Bug:**
Currently, the Session component `client/app/components/navigation/Session.tsx`  flashes "loading" on the home page.

**Background:**
With the  removal of the `Login` component from the Session component, there should not be any loading state indicator on the home page because there is nothing loading (anymore).

**Possible Resolution**

- Add useSession hook to `client/app/components/layout/Header.tsx`
- In Header, display `client/app/components/navigation/Profile.tsx` conditionally based on session?
- Delete `client/app/components/navigation/Session.tsx`  (YAGNI principle)
- Delete `client/app/components/navigation/Login.tsx`   (YAGNI principle)
- Possibly redesign the layout components as follows:
  - Add Header; Footer; Main to `client/app/layout.tsx`
  - Delete `client/app/(onboarding)/layout.tsx`
  - Modify `client/app/(authenticated)/layout.tsx` to nest Breadcrumbs within `client/app/layout.tsx`

Probability (how likely the bug is to happen, scored from 1-5): 5
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 1
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by dleard** [comment]
developer to review (not a PO concern)
