### ISSUE TITLE
Attachment upload works in dev/test/prod

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#799]
#### Describe the task

Attachment upload works in the app (you can upload an attachment and then download it later when viewing the operation), but the file doesn't show up in the google bucket. It must be going somewhere if we're able to redownload it, but where? This ticket is about investigating the google storage part of the feature.

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by hannavovk** [comment]
In reviewing #325 it was working properly in dev. Do we still need this card? @BCerki

**Comment by BCerki** [comment]
> In reviewing #325 this was working properly in dev - the attachment was uploading. Do we still need this card? @BCerki

I see the file upload in the app but I don't see the file show up in our google bucket, so part of the process isn't working yet. I'll update the card to be clearer about that.

**Comment by dleard** [comment]
Tested today & this works. Closing issue
