### ISSUE TITLE
`revalidateTag` error on next server actions [5]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-registration#804]
Describe the Bug:

There seems to be a bug where, upon searching for an existing operator and selecting one, and then confirming that the selected operator is the intended one, we encounter a `revalidateTag` error on the next server. This issue has been observed only in cases where an existing operator is selected and confirmed, but it might happen on other pages as well.

Probability (how likely the bug is to happen, scored from 1-5):3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Log in as `bc-cas-dev-three` -> go to select operator page -> select operator 1 -> confirm selected operator -> look at the next server terminal logs

Screenshots:

![Image](https://github.com/bcgov/cas-registration/assets/52381975/f8e9cf84-0e36-4771-aa87-817da9647ea7)

**Comment by patriciarussellCAS** [comment]
@Sepehr-Sobhani I wasn't able to recreate this bug in Dev. I think it might be fixed now?

**Comment by Sepehr-Sobhani** [comment]
Yes, the issue has been fixed!
