### ISSUE TITLE
Change 'myself' pill to 'Approved'

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-registration#811]
#### Describe the task

In the user table, the pill with the label 'Myself' should be replaced to say 'Approved'

#### Acceptance Criteria

- [x] Status pill with label `Myself` should be replaced to say `Approved`
- [x] Do a project wide text search for `Myself`. There is some conditionals that use the `Myself` and we can remove some of the enums related to styling

#### Additional context

- we want to keep the status.MYSELF because a user should not be able to change their own permissions
- Or here

**Comment by nanyangpro** [comment]
@andrea-williams suggested that this is just a front-end change. cc: @marcellmueller
