### ISSUE TITLE
From "Select Operator" page, can't search operators by CRA business number [5]

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#812]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

In an app environment with mock data (either local or in DEV env), we have some mock operators with set CRA business numbers (e.g., 123456789, or 987654321). 

1. Sign in with a Business BCeID account that isn't currently assigned to an operator
2. Go to the Select Operator tile
3. Click the radio button to search for operators by CRA business number
4. Start typing 2-3 digits into the search bar.
5. Click the "Search Operator" button
6. You'll get an error message saying that there's no matching operator found, even when I've typed in a CRA business number exactly (and it should be fuzzy search anyway)
7. (Try searching operators by legal name to see the desired behaviour)

Screenshots:

![Image](https://github.com/bcgov/cas-registration/assets/54914403/7d04a634-7f3c-41e3-8ce9-0545d3a983ac)

Additional information:

- for reference, I found this when running locally, but it will do the same thing in any app environment.

**Comment by Sepehr-Sobhani** [comment]
Searching operators by CRA business number should be an exact match based on a previous conversation.

**Comment by andrea-williams** [comment]
Thanks @Sepehr-Sobhani - I either didn't know about that, or forgot it entirely. I'll close this ticket as not-needed.
