### ISSUE TITLE
Create RJFS read-only theme in disabled state forms

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-registration#817]
#### Describe the task

When verifying information we’re showing the `disabled` state forms, it would be nice to use a black font rather than light grey for when people are reviewing information.
(Captured by Mike during QA - Note: this feedback was also brought up by other Giraffe team members during a previous demo of the app).

![Image](https://github.com/bcgov/cas-registration/assets/35785153/a22ced72-ff68-4735-8f59-7c5a6091784d)

#### Acceptance Criteria

- [ ] change font colour to hex code #313132
- [ ] re-style text boxes to plaintext

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by andrea-williams** [comment]
Would like to first confirm with @nanyangpro that this UI change is desired?

**Comment by Dianadec** [comment]
Adding notes from Suha as well, from the demo we did on January 11.
cc @andrea-williams @nancymz  @hannavovk @suhafa 


> This may just be a temporary solution, but the 'read-only' version of the form is not legible as the text is greyed out
We could use this format instead (this design is already in Figma)



![Image](https://github.com/bcgov/cas-registration/assets/35785153/064db9b3-5898-4750-bebc-51fc4cfaf5b6)

**Comment by nanyangpro** [comment]
As discussed, we'll get rid of the accordion design and go with the newer form design. AC is required still .@marcellmueller
