### ISSUE TITLE
Two `user_operator` rows for the same user, but different operators [9]

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-registration#818]
Describe the Bug:
Once approved for an operator, when I click `My Operator` on the dashboard it brings me to the Select an Operator page. From here I am able to request to be the lead of another operator (who didn’t have not yet). As a CAS admin I was able to accept the new request as well, seemingly leaving me with two `user_operator` rows for the same user, but different operators.
(Found by Mike during QA)

UPDATE: The frontend side of this will be handled by #600 . We should still add a unique constraint so that each user can only have one user_operator. I think these two tickets are duplicates of this problem:
https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=49864803
https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=49866873

This is a critical bug that needs to be fixed before MVP release = no user should have access to more than one operator, nor should an external user be allowed to request access to a second operator when their request for access to the first operator is still Pending. 

Probability (how likely the bug is to happen, scored from 1-5): [4]
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): [5]
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

![Image](https://github.com/bcgov/cas-registration/assets/35785153/f6d33d47-8aba-4098-af68-d4b5436332e2)

![Image](https://github.com/bcgov/cas-registration/assets/35785153/64db584f-9a70-4bbd-8034-0171ee3621fc)

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by Dianadec** [comment]
@BCerki will update the card once she has more info

**Comment by dleard** [comment]
Closing this as a duplicate. A unique constraint was added to the user_operator table in the PR #899 when working on card #890.
