### ISSUE TITLE
Unable to submit a request for a BORO ID

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-registration#819]
Describe the Bug:
Mike: I have been unable to submit a request for a BORO ID so far. I’m assuming it has something to do with the fact that I did 3 ^ (registered with 2 operators) but I will reset my DB this weekend and find out.

Probability (how likely the bug is to happen, scored from 1-5):
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

![Image](https://github.com/bcgov/cas-registration/assets/35785153/f957fd6b-d858-4aa1-8716-e41bc8d79483)

![Image](https://github.com/bcgov/cas-registration/assets/35785153/5670c469-4d4b-497a-b84c-e78605bfc2d5)

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by andrea-williams** [comment]
Based on the screenshots, it looks like Bug Hunter MV was trying to "submit" an Operation while signed in with his IDIR (as an internal user). Only external users should be allowed to request a BORO ID for an Operation. 

I don't think anything can be done with this at the moment. There might not be any work to do at all.

**Comment by nanyangpro** [comment]
Re: Refinement discussion - Closing as suggested by @dleard and @andrea-williams
