### ISSUE TITLE
Products list not quite in perfect alphabetical order [6]

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-registration#820]
Describe the Bug:
The Products list seems to be alphabetized, but not quite. Definitely not a big deal.

Probability (how likely the bug is to happen, scored from 1-5): 5
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 1
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

![Image](https://github.com/bcgov/cas-registration/assets/35785153/7f602910-ae54-47e1-a948-b29b3b37a99e)

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by nanyangpro** [comment]
Re: Refinement discussion - The listed will be updated per Jairo's request. Closing.
