### ISSUE TITLE
Investigate and optimize ineffeciencies in backend /operation API routes

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#825]
The results of our load testing showed that we have some very ineffecient API routes in the /operations paths. We need to investigate the operation endpoints and optimize where necessary. Some really good exploration & optimization work has been done in #814, which will include documentation on the [Django Silk](https://github.com/jazzband/django-silk) endpoint profiler and some examples of how the GET /operations route was optimized.

AC:
- All operation endpoints have been investigated with the Silk profiler
- Optimizations to any ineffecient routes have been implemented
- Local load testing has been run on the routes as a check that performance has improved (We will load test in the dev environment again once this card and #826 are complete)

**Comment by dleard** [comment]
@Sepehr-Sobhani I've merged this work. I'm not sure if there was more to be done in the /operation endpoints, but I will leave it up to you how you want to handle anything you feel is outstanding (if there is anything)

**Comment by Sepehr-Sobhani** [comment]
Thank you, @dleard! I would like to keep this task open, but remove the high-priority tag and move it to the tech debt column. I believe we can use this ticket to keep track of the unoptimized endpoints so that we can optimize them at a later time.
