### ISSUE TITLE
How will our system handle Sales/Transfers/Closures?

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-registration#831]
We will need to get clarity and map out the process flow for what happens when an Operator needs to change information about operations or facilities. This issue is particularly prominent with the Oil & Gas sector who tend to buy and sell facilities frequently. 
Some elements that make this complicated: 
Sales/transfers involve two parties; the seller and the buyer.
How do we capture historical Emissions/compliance reports from facilities that are sold? 

*Definition of Ready*
- [ ] Determine with B.A. whether or not this should be part of the MVP - how would this process work if it's NOT in the MVP? [Current process is that it happens via email] 

**Goals:** 
- [ ] Understand where and how in our system (Registration/Reporting) the Operator will go to update their information when there is a sale, transfer or closure of their facility. 
- [ ] Identify what information is required when transferring, selling or closing a facility. 
- [ ] Understand other requirements related to this process (for example, Operators will have 30 days from the date of sale to inform the province)

**Stretch goals (likely a separate ticket):**
- [ ] Map out the process for Operators to make these types of updates

**Comment by nanyangpro** [comment]
Will be covered by #1370 ~ #1378.
