### ISSUE TITLE
UX/UI Enhancement - Dynamic "Pending" Link for Each Dashboard Tiles

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-registration#837]
From the [compiled external user feedback](https://miro.com/app/board/uXjVNQ_HFbQ=/?moveToWidget=3458764574127352504&cot=14):

> The 'Pending' status under each tile needs some investigation as to how we can make it an intuitive experience for users

> **Suha's recommentation:** Could require further UI validation and exploring. Designers can collaborate on the best path forward.

As discussed with @hannavovk, this could be a future ux enhancement in Registration Part II post MVP.

Currently, the dynamic links display like below. This ticket is for revisiting the messagings, and refine the design to make it more intuitive to both internal and external users.

**Internal**
![Image](https://github.com/bcgov/cas-registration/assets/58751681/6d960ba8-49c4-4a28-88c7-ba221989731c)

**External**
![Image](https://github.com/bcgov/cas-registration/assets/58751681/42c0be00-cecf-4abc-86c6-15fe4d6113b3)

#### AC:
- [ ] To be added

**Comment by BCerki** [comment]
This is at least partially done already
