### ISSUE TITLE
e2e test\workflow\bceidbusiness\industry_user_admin

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#843]
#### Description:

Tests of `\bceidbusiness\industry_user_admin` [workflow](https://miro.com/app/board/uXjVN6uBj9Y=/)

**Page by Roles Tests**
- [x] Cannot navigated to restricted app routes (**NOTE:** tested in `client/e2e/pages/authenticated/routes/page.spec.ts`)
- [x] Login redirected to Dashboard page (**NOTE:** tested in `client/e2e/pages/onboarding/home/page.spec.ts`)
- [x] Profile page submit required data (**NOTE:** tested in `client/e2e/pages/authenticated/dashboard/profile/page.spec.ts`)
- [x] Dashboard design: "My Operator", "Operations", and "Report a Problem"  (**NOTE:** tested in `client/e2e/pages/authenticated/dashboard/page.spec.ts`)

**WIP**

**Tests using storageState for `industry_user_admin`:**

- [x] clicking on "Operations" tile should redirect them to table of all existing operations associated with their Operator only, including operations with a status of "Draft" or "Not Started"
- [x]  is able to click "View Details" button for any operation in the table
- [x]  is able to click "Add New Operation" from the Operations page and create a new Operation
- [x]  is able to click on "My Operator" tile, can see readonly data about the Operator
- [x]  from "My Operator" tile, is able to click the "Edit information" button and edit data fields (at the moment, can edit any field) about the Operator and submit the updated data successfully

**Comment by andrea-williams** [comment]
Closing this - we don't have an `industry_user_admin` role anymore
