### ISSUE TITLE
e2e test\workflow\idir\cas_analyst

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#845]
#### Description:

Tests of `\idir\cas_analyst` [workflow](https://miro.com/app/board/uXjVN6uBj9Y=/)

**Page by Roles Tests**
- [x] Cannot navigated to restricted app routes (**NOTE:** tested in `client/e2e/pages/authenticated/routes/page.spec.ts`)
- [x] Login redirected to Dashboard page (**NOTE:** tested in `client/e2e/pages/onboarding/home/page.spec.ts`)
- [x] Profile page submit required data (**NOTE:** tested in `client/e2e/pages/authenticated/dashboard/profile/page.spec.ts`)
- [x] Dashboard design:  " "Operators", "Operations", "Report a Problem" tiles (**NOTE:** tested in `client/e2e/pages/authenticated/dashboard/page.spec.ts`)

**Tests using storageState for `cas_analyst`:**
- [x] Operator tile workflow
    - [ ]  Dashboard tile click
    - [ ] Operator grid ux
        - [ ]  grid view
        - [ ]  grid table
        - [ ]  grid table columns
        - [ ]  grid column values
    - [ ] View Details click
    - [ ] Details form ux
    - [ ] Workflow New Operator, Pending status, Deny Action
    - [ ] Workflow New Operator, Pending status, Approve Action
    - [ ] Workflow Existing Operator, Pending status, Deny Action
    - [ ] Workflow Existing Operator, Pending status, Approve Action
- [x] Operation tile workflow
    - [ ]  Dashboard tile click
    - [ ] Operation grid ux
        - [ ]  grid view
        - [ ]  grid table
        - [ ]  grid table columns
        - [ ]  grid column values
    - [ ] View Details click
    - [ ] Details form ux
    - [ ] Workflow Pending status,Request Changes\Unrequest Changes
    - [ ] Workflow Pending status,Approve Action
    - [ ] Workflow Pending status, Decline Action
    - [ ] Workflow  Approved Preview the Statutory Declaration PDF

**Comment by andrea-williams** [comment]
De-prioritizing this - for MVP, all internal users will have `cas_admin` roles.

**Comment by shon-button** [comment]
## 🚧 
**Issue**
The following Playwright tests work locally but, fail in our CI environment.

1. `client/e2e/poms/operations.ts\await expect(this.messageOperationApproved).toBeVisible();`

**Local:**
![image](https://github.com/bcgov/cas-registration/assets/120038448/83358813-2365-4049-b9b7-6c38fe729c61)

**CI**
![image](https://github.com/bcgov/cas-registration/assets/120038448/74705886-31bd-413b-a9c2-09ffd69f92a3)



Error encountered compiling schema: Error: schema is invalid: data/properties/business_structure/anyOf must NOT have fewer than 1 items

![Image](https://github.com/bcgov/cas-registration/assets/120038448/c389a24a-70f9-42b0-82c7-f2595dd94d6e)

2.`client/e2e/poms/operations.ts\await downloadPDF`

**Local**
![image](https://github.com/bcgov/cas-registration/assets/120038448/8c252612-b5e8-4d10-a9ec-c30e04ee504c)

**CI**
![image](https://github.com/bcgov/cas-registration/assets/120038448/36044fe9-dafc-49e3-91ac-f867ba37e10c)
