### ISSUE TITLE
e2e test\workflow\idir\cas_pending

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#846]
Tests of `\idir\cas_pending` [workflow](https://miro.com/app/board/uXjVN6uBj9Y=/)

**Page by Roles Tests**
- [x] Cannot navigated to restricted app routes (**NOTE:** tested in `client/e2e/pages/authenticated/routes/page.spec.ts`)
- [x] Login redirected to Profile page (**NOTE:** tested in `client/e2e/pages/onboarding/home/page.spec.ts`)
- [x] Profile page submit required data (**NOTE:** tested in `client/e2e/pages/authenticated/dashboard/profile/page.spec.ts`)
- [x] Dashboard design: no tiles are available, message that access request is pending (**NOTE:** tested in `client/e2e/pages/authenticated/dashboard/page.spec.ts`)

**WIP**
**Tests using storageState for `cas_pending`:**
- [ ] navigation to "home" is redirected to Dashboard page

**Comment by Sepehr-Sobhani** [comment]
@shon-button , I recall you mentioning that you're developing route protection tied to user roles in issue `1006`. Should I skip that part here?

**Comment by shon-button** [comment]
@Sepehr-Sobhani  Updated ACs "done" list with `Cannot navigated to restricted app routes`
