### ISSUE TITLE
Draft Envisioned Registration Part II Information Architecture Diagram

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-registration#865]
This ticket is for creating an information architecture diagram for Registration Part II, based on the assumptions of required workflows. The information architecture will guide the UX structure for registration part II, how the navigation will work, and where users can find information

**Purpose**
- Inform design decision making for UX, so that UX can test the navigation and ease of finding information with users 

**AC**
- [x] It shows UX how the navigation and order of information should live, so that UX can create wireframes 
- [x] Peer review and feedback gathering
- [x] It is validated with the business areas and or external users 
- [x] It has been refined 

**Additional**
- Can be done in parallel, at the same time as creating the workflows, this ticket is not dependent on the completion of #868

**Comment by hannavovk** [comment]
Great work! Thanks @nanyangpro
