### ISSUE TITLE
Operation form cannot continue when operation submitted an emissions report for 2022

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#879]
When requesting a BORO ID as an industry user, if they select 'Yes' when asked if they submitted an emission report for 2022 they cannot continue through the form. If they select 'no' then the opt-in radio button shows up & when that has a value the form can be completed. I figure there is an error in the jsonschema logic somewhere where the opt-in value is still required even when it does not show up in the form.

To Reproduce:
- [ ] start registration for a BORO ID
- [ ] select 'Yes' when asked if submitted an emission report for 2022
- [ ] Click 'Next' at bottom of the page. Nothing happens, no errors on the backend. (This is why I figure it's a hidden RJSF validation thing)

**Comment by dleard** [comment]
Decisions that were made while investigating this bug:
- Remove the "Did you submit a GHG Report for 2022"  section entirely. It served no purpose and was the source of the bug
- Add a readonly bcghgid field to display the bcghgid (if they have it, otherwise shows a message that it will be assigned by CAS)
- Add additional context around opt-ins and a link to the BCOBPS website which contains more information and application forms for opt-ins

**Comment by nanyangpro** [comment]
Added "Deletion Candidate" as suggested by @dleard.
