### ISSUE TITLE
Business Mailing Address is or isn't required? [6]

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#889]
Describe the Bug:

As an external user, when filling out data in the Operator form, if I click on the "No" radio button for "Is the business mailing address the same as the physical address?" the mailing address field labels have *s next to them indicating that they're required, but on form submission, there's no validation performed to ensure those data fields are populated.

Probability (how likely the bug is to happen, scored from 1-5): 3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
1. Login as external user with no associated operator
2. Create a new operator (this might also happen with existing operators, not sure...)
3. Click "No" for "Is the business mailing address the same as the physical address?"
4. Leave business address fields blank and submit the form

Screenshots:

![Image](https://github.com/bcgov/cas-registration/assets/54914403/ef7a1182-4bf2-4c4c-ba63-2f3d8c571e14)

Desired Behaviour:
We should be collecting address data on Operators, so if an Operator's mailing address is different from their physical address, we want to make the business address fields required. If the mailing address == physical address, the mailing address fields should be hidden in the form anyway.

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by Sepehr-Sobhani** [comment]
I was not able to replicate the issue:


![Image](https://github.com/bcgov/cas-registration/assets/52381975/4351a31e-fb04-4ef2-aa55-967e72f43eb1)

**Comment by nanyangpro** [comment]
Can someone else try to replicate it since @Sepehr-Sobhani wasn't able to? Feel free to close it if needed. @marcellmueller

**Comment by marcellmueller** [comment]
Verified that this isn't needed anymore.
