### ISSUE TITLE
Internal users shouldn't be able to edit parent company data for Operators [5]

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#891]
Describe the Bug: Internal users shouldn't be able to edit parent company data for Operators

Probability (how likely the bug is to happen, scored from 1-5): 3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

As an internal user viewing an Operation with a "Pending" status (or probably any status), I can delete the info about multiple parent companies in the Operator section just by clicking the `-` sign in the section headers labelled "Parent Company 2", "Parent Company 3", etc. (not true of the first parent company).

As an internal user viewing an Operation with a "Pending" status, I can add additional parent companies in the Operation section of the form because the "Add another parent company" button is displayed and enabled. This button shouldn't be rendered for internal users, and shouldn't be rendered in the Operation form for any user (if an external user wants to edit info about their Operator, they need to do that in the Operator tile, not from the Operation form).

Internal users should not be allowed to edit any information about an Operation or Operator.

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by BCerki** [comment]
Should be fixed by: https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=parent&pane=issue&itemId=53042851

**Comment by nanyangpro** [comment]
Fixed. Closing as discussed during refinement.
