### ISSUE TITLE
BCGHG ID field disabled but required - wat? [6]

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#894]
Describe the Bug: In the form to create a new Operation, there's a field labelled "BCGHG ID*" (with a * to indicate it's mandatory) but the form field is actually readonly. The BCGHG ID field is either auto-populated (from the facility data imported from SWRS) or it's a brand new operation, in which case it won't have a BCGHG ID. There are no visual indicators on the form to suggest that it's readonly. This is confusing for external users.

I also think the BCGHG ID field is only displayed when the "Did you submit a GHG emissions reports for reporting year 2022?" field is Yes, but having that field there doesn't really make sense either. 

Probability (how likely the bug is to happen, scored from 1-5): 4
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

![Image](https://github.com/bcgov/cas-registration/assets/54914403/aab99afc-4979-4343-9656-27648a858884)

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by andrea-williams** [comment]
Flagging this for @nanyangpro and @zoeyli-46 's attention (although it was Zoey who found it). At the moment, the implementation mostly matches the wireframe (with the exception of the *). Is the "Did you submit for 2022?" field required anymore? And is there some other styling we can add to the BCGHG ID field to indicate that it's always a readonly field that may or may not be blank?

**Comment by nanyangpro** [comment]
Great questions, @andrea-williams! And thanks @zoeyli-46 for flagging it!
- In the case that the operation is new, I find the "Did you submit a GHG emissions report for reporting year 2022?" field unnecessary. However, I also don't see any documented decision for hiding the field in such scenario. I would recommend displaying the field but defaulting the selection to "No" for now, unless you have concerns doing so.
- We'd love to have consistent styling for read-only forms/fields across the app. How about hiding the border of the input box and simply display the field value (if there is)?

**Comment by dleard** [comment]
This should be solved by #937

**Comment by nanyangpro** [comment]
Re: Refinement discussion - Closing. Please see the comments above.

Additional context from Emilie/Maral/Jairo: The Reporting team (Qinghan included) will be leaving IRC as part of the re-organization. We should re-evaluate the "BCGHG ID" process. @hannavovk 

@dleard suggested we have a discussion session post release with SMEs.
