### ISSUE TITLE
Write Tests for Django Models

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#90]
#### Describe the task

This task is to write tests for the existing Django models that include:
- all columns exist
- create record??
- suggest pytest

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by Sepehr-Sobhani** [comment]
Might be more convenient to use Django specific plugin for this: https://pytest-django.readthedocs.io/en/latest/index.html#
