### ISSUE TITLE
Redirect to Dashboard after submitting updated personal information? [6]

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#907]
Describe the Bug: When updating my personal information (e.g., logging in for the first time) the "success" button flashes but is greyed out, and is very easy to miss. Are we missing a redirect?

Probability (how likely the bug is to happen, scored from 1-5): 4
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by andrea-williams** [comment]
I'm kind of guessing that we'll want to add a redirect back to the dashboard after successful submission of personal info, but I'll defer to @nanyangpro 's judgement.

**Comment by nanyangpro** [comment]
Good suggestion, @andrea-williams! - Let's go for it.
