### ISSUE TITLE
CAS users are not able to see operations detail page[8]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-registration#924]
Describe the Bug: 
CAS users cannot view the operation detail page, most likely due to the absence of `[formSection]` in the NextJS routes.

Probability (how likely the bug is to happen, scored from 1-5): 3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 5
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
Log in to the operations page as a cas admin or analyst using IDIR, and select any operation from the table.

Screenshots:

![Image](https://github.com/bcgov/cas-registration/assets/52381975/b4d4ab20-6794-4261-bd02-f04bc5252a39)

Additional information:

Browser: [e.g. chrome, safari]
Version: [e.g. 22]
Additional context

**Comment by andrea-williams** [comment]
Closing this one - it's already been fixed in another ticket.
