### ISSUE TITLE
IRC staff can't approve prime admin requests for existing Operators [8]

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#931]
Describe the Bug:
We've introduced a regression somewhere in our logic, where internal users can no longer approve admin requests from external users requesting access to existing (imported) Operators. The Operator's status will be "Draft", but that should not prevent IRC staff from approving the admin request. Because the Operator isn't new (`is_new=False`), there's no option in the form for internal users to approve the Operator, so the admin request is completely blocked.

Probability (how likely the bug is to happen, scored from 1-5): 4
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 4
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
1. Log in as an external user, and request prime admin access for an existing Operator
2. Log out, then log in as an internal user
3. Navigate to the admin access request you just created, and click "View Details"
4. Click "Approve" in the User Information section - this is where the error message will trigger.

Screenshots:

![Image](https://github.com/bcgov/cas-registration/assets/54914403/4f2b3e9a-9959-479b-9ecc-d005062aef63)

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by BCerki** [comment]
@dleard , I think we can close this one since https://github.com/bcgov/cas-registration/pull/958 covers the draft workflows?

**Comment by nanyangpro** [comment]
Added "Deletion Candidate" as suggested by @BCerki and @dleard.
