### ISSUE TITLE
Identify how and where LFO's see their facility data across reg/reporting.

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-registration#945]
LFOs will need to provide information about all their facilities. Some of that information will be entered in registration and some in reporting. 

This ticket relates to and is blocked by work being done in Registration, including #865 and #868 

In order to create similar artifacts for Reporting, Registration Part 2 will need to be validated. 

We want to understand where to put facility data LFO's will see between registration and reporting, so the scope of what is in registration versus reporting is clarified. Questions we want to answer include:
- Where do LFOs report types of activities and products?
- How will facility data separated between registration and reporting, what are the dependency and relationships between facility data?
- What is the first step in reporting?

**Acceptance Criteria**
- [x] Review with Harnav and the 'Registration fields' spreadsheet
- [ ] Validating specific facility-level fields and the flow of where it is gathered 

**Blockers**
- [ ] Workflow diagram for Registration Part 2 will likely clarify the AC for this ticket

**Discussion considerations**
- One way of deciding what data is collected/used where is putting facility fields that is likely to change year to year in reporting, and the rest in registration

**Comment by zoeyli-46** [comment]
Do we see ticket #854 being a blocker to this? 

" in the user story map some things are right on the line between Reg/Reporting and not sure from the users perspective if what lives where." what do we mean by where does it live? Do we mean, if the data is input in the emissions report or if the data is input in the operator information? 
"What is actually the first step in reporting?" In SWRS its where they pick a report type?

**Comment by patriciarussellCAS** [comment]
Hey @zoeyli-46 could we move this ticket into the moose board (and just add a Giraffe tag for visibility)?
 I think it makes sense for it to live there. Thanks!

**Comment by zoeyli-46** [comment]
That makes sense I'll move it over, thanks Patricia!

**Comment by zoeyli-46** [comment]
As advised by business area (Emilie) operation level products and activities are collected in registration, but facility level product and activities information are collected at reporting. @hannavovk we are closing this ticket with this conclusion, however, if you believe this should stay open we can reopen it.
