### ISSUE TITLE
Update Physical and Mailing address when updating operators[7]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-registration#959]
Describe the Bug:

When updating the operator in the `save_operator` function, make sure to update their physical and mailing addresses instead of creating new ones. Otherwise, many orphaned addresses may be created.

Probability (how likely the bug is to happen, scored from 1-5): 3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 4
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by BCerki** [comment]
#661 ~should fix this
