### ISSUE TITLE
Add documentation to API endpoints [10]

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#962]
### Description of the Tech Debt ###

Blocked on endpoint renaming: #1077 

We stopped adding any documentation for our API endpoints months ago, and because of that our Swagger docs are extremely lackluster. This is very inconsiderate to any future developers, and also will impact current devs in the long-term.

### Tech Debt Triage ###
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |    1   |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |     2  |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |  1     |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |   3    |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |     3  |
| TOTAL SCORE:                                                                                                                  |       |   10    |

**Comment by Sepehr-Sobhani** [comment]
Suggest adding tags to endpoints to make our OpenAPI docs more organized: https://django-ninja.dev/reference/operations-parameters/?h=tags#tags

**Comment by pbastia** [comment]
Endpoint naming best practices: https://www.geeksforgeeks.org/best-practices-for-naming-api-endpoints-in-a-restful-architecture/ (from Sepehr)
