### ISSUE TITLE
Forced logout after a period of inactivity

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#971]
**Background:**
Keycloak authentication server provides a flow for issuing an access token, the expiration time of the access token, and a refresh token to be used to request a new access token once that token has expired,`access_token`; `expires_at`,`refresh_token`, which can be used to determine access to the protected resources needed by our application users.

Previously we had implemented a [refresh token strategy](https://next-auth.js.org/v3/tutorials/refresh-token-rotation) from Keycloak but, decision to remove it as an implementation bug was causing a forced logout after 30 minutes and a resolution of the bug would essential just keep refreshing the token without reusing the token's refreshed information.
Currently, we use the token from a successful client authentication with the Keycloak authentication server in `client/middlewares/withAuthorization.tsx` to access user information `app_role` for front end protection and  `user_guid` and 
 for API protection but, **we do not use** `access_token`; `expires_at`,`refresh_token`.

As such, we need to discuss using or not using of the Keycloak `access_token`; `expires_at`,`refresh_token` for user access to the protected resources:

- If we do not use the `access_token` for protecting resources do we need to implement a refresh token strategy?
- Should we implement a forced session logout after some x interval?

**Forced Session Logout**

**Background:**
A session is initiated when a user logs in or starts interacting with the application and is typically terminated when the user logs out or after a period of inactivity. 

These are the main components of a session:

- Session Identifier (Session ID): A unique string that distinguishes one session from another. It is sent by the server to the client after successful login and is usually stored in a cookie on the client side.
- Session Store: A storage mechanism, often on the server side, where session data, such as user details and preferences, are stored. This could be in-memory storage, a database, a file system, or a distributed cache, depending on the application's requirements.
- Session Data: Information stored in the session, often including user preferences, user identification and authentication data, and temporary application state. This data is used to personalize the user experience and to maintain the state of the application between different requests from the client.
- Session Cookie: A type of HTTP cookie sent from the server to the client’s browser to store the session ID.
- **Session Timeout:** A mechanism to terminate sessions after a predefined period of inactivity to minimize the risk of unauthorized access. Once a session is timed out, the user needs to re-authenticate to continue interacting with the application.

Suggesting v1 is implementation of **session timeout** - forced logout after a **period of inactivity**

Next-Auth `session.maxAge` defines the actual session expiry time. The default session session.maxAge value is 30 days (defined 30 * 24 * 60 * 60 seconds).  The  `session.maxAge` expiry time is updated on useSession hook triggered from user app activity, app inactivity will trigger next-auth to delete session cookies (sign out) after maxAge expires.

**DEV TASKS**

- [x] configure Next-Auth `session.maxAge`  expiration to **match** (or exceed) Keycloak expiration of 30 minutes 

**AC**
- [ ] nextauth `getServerSession` and `useSession` will manage/rotate the  `maxAge` expiration time if there is user interaction with the app; so, users interacting with the app for more than 30 minutes will NOT  be logged out
- [ ] exceeding `maxAge` value, due to inactivity, will sign out the user from next-auth session
- [ ] Logged out users will be redirected to home page
- [ ] Users can log back in using Keycloak

**Comment by dleard** [comment]
A few thoughts here:
After 30 minutes of inactivity the user should be logged out
The session should live a maximum of 12 hours
I think we should consider incorporating the keycloak access token & refresh action into our current implementation.
There is a gist that has a good example of using both nextauth and keycloak with access/refresh tokens [here](https://gist.github.com/degitgitagitya/db5c4385fc549f317eac64d8e5702f74)
