### ISSUE TITLE
Bceid users table requires refresh [6]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#978]
Describe the Bug:

The users table doesn't update to show the new status after approve/deny/undo until the user refreshes, so it looks like the button didn't work.

https://www.loom.com/share/e186eed24e504d298070fadc1e114a7e

Probability (how likely the bug is to happen, scored from 1-5): 3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by shon-button** [comment]
@BCerki I believe this bug will be resolved by #870
