### ISSUE TITLE
Catch Suha up on UX/UI design side of work so far

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-registration#98]
#### Goal of Ticket
Onboard Suha to OBPS, and prepare her for the upcoming UX/UI work while Nan is away.

#### Describe the task
Shortly after Suha is back on Mon, Sep 18, Nan will be away from Mon, Oct 2 to Thu, Nov 9. This ticket is to support onboarding Suha, especially to catch her up on the UX/UI design side of work so far for the Registration app.

#### Acceptance Criteria
- [x] Schedule and provide a walkthrough of the **Registration app wireframes and interactive prototypes** in Figma for Suha/Mike, including Nicole as suggested by Hanna
- [x] Schedule meeting(s) for discussing with Suha, service designers and POs to align on next steps
- [x] Grant Suha **Editor** access to Figma
- [x] Unblock Suha as requested

**Comment by nanyangpro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-registration/98?planning-poker) with Zenhub @jaimiebutton @nanyangpro @NicoleGovvy

**Comment by nanyangpro** [comment]
Hi @suhafa - Thanks for the chat this morning! As discussed, the following meetings are scheduled for this and next week for us to connect on different purposes:
- **First UX'ers Catch-up** (Tuesday, September 19)
- **Q&A and Figma Detailed Walkthrough** for Suha (Friday, September 22)
- **UX/UI Tickets Walkthrough** for Suha (Monday, September 25)
- **UX/UI Next Steps Discussion** (Wednesday, September 27)
- **Last Check-in** - Suha & Nan (Friday, September 29)

Looking forward to them!

**Comment by suhafa** [comment]
Thank you for booking the meetings in @nanyangpro, looking forward to them myself! As promised, I am compiling my questions [here](https://miro.com/app/board/uXjVMYXJ1kc=/?moveToWidget=3458764564413894040&cot=14) for visibility

**Comment by nanyangpro** [comment]
Hi @hannavovk - This ticket is ready for you to review and can be closed with all the hand-off meetings above conducted, along with @suhafa's confirmation in our last check-in. :)
