### ISSUE TITLE
Operations\Create\Upload attachment field is cleared on template download [5]

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#986]
Describe the Bug:
When completing the `Operation` form, after uploading an attachment, clicking the `(Download [template])` link clears the attachment name and displays `No attachment was uploaded`
![image](https://github.com/bcgov/cas-registration/assets/120038448/d7f4b8e8-6e25-4d24-a5cc-4b70a6bb33d8)

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by hannavovk** [comment]
Nice job @Sepehr-Sobhani! Looking good to me now - says "reupload attachment" now instead of the error
