### ISSUE TITLE
Operator prime admin request Decline displays incorrect message [2]

### ISSUE THREAD

**Issue by shon-button** [bcgov/cas-registration#987]
Describe the Bug:
When approving `Operations` prime admin request clicking `Decline` shows message `Operator must be approved before approving users.`
**Note** No db data mutations
![image](https://github.com/bcgov/cas-registration/assets/120038448/db9701a0-a41f-4951-a1c5-f93c0a506565)

Probability (how likely the bug is to happen, scored from 1-5): 1
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 1
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by BCerki** [comment]
I think this is higher than a 2--this probably prevents users from declining users
