### ISSUE TITLE
Backend image runs in openshift

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-registration#99]
Split from #35
We need to be able to deploy the backend image to openshift. This means adding helm templates to our bcgov-c argoCD manifest repository.

- [x] Add a template to deploy the backend from our image
- [x] The backend image runs on openshift
- [x] The backend can communicate with the postgres cluster (network policies, connection string)
- [x] Resource tuning if necessary
- [x] Image is updated from source repo (add update-manifests action to source)
- [x] Documentation

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Moose-Sprint-Board-60d216175a2689000ec774d0/issues/bcgov/cas-registration/99?planning-poker) with Zenhub @andrea-williams @BCerki @dleard @JoshLarouche @Sepehr-Sobhani

**Comment by Dianadec** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Moose-Sprint-Board-60d216175a2689000ec774d0/issues/bcgov/cas-registration/99?planning-poker) with Zenhub @joshgamache
