### ISSUE TITLE
Input Gathering & Alignment Sessions for the Envisioned Reg Pt II Workflow & IA

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-registration#996]
**The context**: [Envisioned Registration Part II workflows](https://miro.com/app/board/uXjVNtgEVCs=/?moveToWidget=3458764578941575996&cot=14) and [Information Architecture](https://miro.com/app/board/uXjVNtgEVCs=/?moveToWidget=3458764580339379996&cot=14) were created.

**The goal:** Gather input and set alignment across the teams.

 **Acceptance criteria**
- [x] Schedule and host internal alignment workshop with Moose core team to bring awareness of the artifacts and gather input
    - [x] Fri, Mar 1, 1:00 p.m. - 2:00 p.m.
    - [x] Tue, Mar 12, 2:00 p.m. - 3:30 p.m.
- [x] Schedule and host alignment workshop with broader groups including Giraffe and SMEs
    - [x] Thu, Mar 14, 10:30 a.m. -12:00 p.m.
- [x] Address the input gathered and reflect the changes in the artifacts

**Comment by nanyangpro** [comment]
Hi @zoeyli-46 - This ticket is refined as discussed. Feel free to refine further or remove the "Backlog Refinement" and "Needs AC" tags and bring them into the "Sprint Backlog" as you see fit.

**Comment by nanyangpro** [comment]
Hi @hannavovk - This ticket is ready for you to review and can be closed.

- 2 moose internal alignment sessions and 1 alignment session with Giraffe and SMES were planned and hosted.
- Feedback/questions were collected and discussed during the workshop, or responded async afterwards.
- Version evolvements:
    - [**IA (Moose Final Version)**](https://miro.com/app/board/uXjVNtgEVCs=/?moveToWidget=3458764582498357805&cot=14)
    - [IA (Moose Envisioned Version)](https://miro.com/app/board/uXjVNtgEVCs=/?moveToWidget=3458764582099630908&cot=14)
    - [IA (Alternative Version 2)](https://miro.com/app/board/uXjVNtgEVCs=/?moveToWidget=3458764581607686984&cot=14)
    - [IA (Alternative Version 1)](https://miro.com/app/board/uXjVNtgEVCs=/?moveToWidget=3458764581606504901&cot=14)
    - [IA (Original Version)](https://miro.com/app/board/uXjVNtgEVCs=/?moveToWidget=3458764580339379996&cot=14)

**Comment by hannavovk** [comment]
Awesome! thanks @nanyangpro
