### ISSUE TITLE
Identify Part II Processes

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-registration#998]
**The context:** [Requirements and High-Level Process Maps](https://miro.com/app/board/uXjVNp8-wRc=/?moveToWidget=3458764579988446511&cot=14) were created for Registration Part II based on our assumptions and accumulated learnings so far.

**The goal:** To validate what we have in the Requirements table and to learn about each table row, especially the ones below **in more details** from the business area and operators
- [x] facility sales and transfers process
- [x] user management process (adding users as contacts, internal and external roles) 
- [x] reporting-only, opt-in, and new entrant registration processes and form-fields
- [x] enhancements requirements to Part I; such as change requests

 **Acceptance criteria**
- [x] Update the Registration Part II Requirements table with additional details for each row
- [x] Update the High-Level Process Map accordingly as required so that it can help inform the envisioned workflows or IA

**Comment by zoeyli-46** [comment]
Could I get your thoughts on the feasibility of this and whether it is a realistic sprint goal, based on what we know so far? @nanyangpro

**Comment by nanyangpro** [comment]
Hi @zoeyli-46 - This ticket is refined as discussed. Feel free to refine further or remove the "Backlog Refinement" and "Needs AC" tags and bring them into the "Sprint Backlog" as you see fit.

**Comment by zoeyli-46** [comment]
@hannavovk I have just moved this into the done column
